### ISSUE TITLE
Karpenter kept scheduling pod on Node which has not enough resources

### ISSUE THREAD

**Issue by ra-grover** [aws/karpenter#2309] opened 2022-08-17 20:19 UTC
## Version

**Karpenter**: v0.13.0

**Kubernetes**: v1.20.0

## Expected Behavior
Karpenter should Provision nodes, the pods were in pending state for 13 hours and the logs repeatedly said 
```2022-08-17T15:29:03.786Z	DEBUG	controller.events	Normal	{"commit": "062a029", "object": {"kind":"Pod","namespace":"payment-orchestrator","name":"payment-orchestrator-test-us-east-1-master-template-766d7c6dxml","uid":"cfa1fce9-c4d5-4b9e-a75b-93d5408c4ab0","apiVersion":"v1","resourceVersion":"381957916"}, "reason": "NominatePod", "message": "Pod should schedule on ip-10-74-7-176.ec2.internal"}```

## Actual Behavior

Karpenter should provision new nodes and not keep retrying on the batched one, if there is space/memory constraint.
The cpu left on the node was `2249m` and requested CPU by the pod was `2700m` totalling all the sidecars that are injected through the Webhooks. 
Still Karpenter kept on trying to schedule the pod on the node which didn't have much capacity.
```Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource                    Requests      Limits
  --------                    --------      ------
  cpu                         13641m (85%)  50400m (317%)
  memory                      9992Mi (35%)  27360Mi (96%)
```

## Steps to Reproduce the Problem
There should be atleast one node in the Cluster which has enough capacity to accomodate the main container of the pod but not the sidecars (This is only theory my team could come up with, not sure how exactly to reproduce )

## Resource Specs and Logs

Karpenter Controller logs:
```2022-08-17T15:29:03.786Z	DEBUG	controller.events	Normal	{"commit": "062a029", "object": {"kind":"Pod","namespace":"payment-orchestrator","name":"payment-orchestrator-test-us-east-1-master-template-766d7c6dxml","uid":"cfa1fce9-c4d5-4b9e-a75b-93d5408c4ab0","apiVersion":"v1","resourceVersion":"381957916"}, "reason": "NominatePod", "message": "Pod should schedule on ip-10-74-7-176.ec2.internal"}```

Provisioner Spec:
```
spec:
  labels:
    karpenter-provisioner-type: standard
  provider:
    apiVersion: extensions.karpenter.sh/v1alpha1
    kind: AWS
    launchTemplate: karpenter-rcp
    subnetSelector:
      purpose_app: 'true'
    tags:
      karpenter-provisioner-type: standard
  requirements:
    - key: topology.kubernetes.io/zone
      operator: In
      values:
        - us-east-1a
        - us-east-1b
        - us-east-1c
    - key: kubernetes.io/arch
      operator: In
      values:
        - amd64
    - key: karpenter.sh/capacity-type
      operator: In
      values:
        - on-demand
        - spot
    - key: node.kubernetes.io/instance-type
      operator: NotIn
      values:
        - a1.2xlarge
        - a1.large
        - a1.medium
        - a1.xlarge
        - c1.medium
        - <BIG_LIST>
  ttlSecondsAfterEmpty: 30
  ttlSecondsUntilExpired: 2592000
````

Pod Containers:
```
kubectl -n payment-orchestrator get pod payment-orchestrator-test-us-east-1-master-template-766d7c6dxml -o yaml |grep req -A2
      requests:
        cpu: 100m
        memory: 128Mi
--
      requests:
        cpu: "2"
        memory: 6Gi
--
      requests:
        cpu: 250m
        memory: 64Mi
--
      requests:
        cpu: 250m
        memory: 64Mi
--
      requests:
        cpu: 100m
        memory: 128Mi
```

Pod events screenshot:
As you can see the event count is `721` and it kept on retrying.
<img width="727" alt="Screenshot 2022-08-17 at 1 44 53 PM" src="https://user-images.githubusercontent.com/93419161/185235000-1e3026ba-f6ec-4f62-92f2-2afcdb170f68.png">

**Comment by tzneal** [comment] 2022-08-17 20:26
Can you provide the full pod spec and the allocatable section of the resources from the node?

**Comment by ra-grover** [comment] 2022-08-17 20:41
Pod Spec:
Few values are Redacted. Dont have the pod spec for that same pod, but for another which was also in the same state and was under same ReplicaSet so it has same spec.
```
apiVersion: v1
kind: Pod
metadata:
  name: payment-orchestrator-test-us-east-1-master-template-cb855cq7x2f
  generateName: payment-orchestrator-test-us-east-1-master-template-cb855cbc5-
  namespace: payment-orchestrator
  uid: 7b414f42-8ea1-467a-aaf4-e4f5ae86893e
  resourceVersion: '382064789'
  creationTimestamp: '2022-08-17T05:30:49Z'
  labels:
    admission.datadoghq.com/enabled: 'true'
    app: payment-orchestrator--test-us-east-1-master
    app.expediagroup.com/asset-protection-level: '99'
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: payment-orchestrator
    app.kubernetes.io/version: d2045fa78b728936ccabd1fc59c765fccb8359d5
    helm.sh/chart: paved-road-service-7.0.0
    island.expediagroup.com/name: orders
    k8s.expediagroup.com/installation-name.short: payment-orchestrator--branch-master
    k8s.expediagroup.com/installation-name.structured.application: payment-orchestrator
    k8s.expediagroup.com/installation-name.structured.classifier.branch: master
    k8s.expediagroup.com/instance: master
    k8s.expediagroup.com/reason: branch
    k8s.expediagroup.com/release: test-us-east-1
    pod-template-hash: cb855cbc5
    product.expediagroup.com/name: payment-orchestrator
    progressivedeployment.expediagroup.com/variant: template
    security.istio.io/tlsMode: istio
    service.istio.io/canonical-name: payment-orchestrator
    service.istio.io/canonical-revision: d2045fa78b728936ccabd1fc59c765fccb8359d5
    tags.datadoghq.com/service: payment-orchestrator
    tags.datadoghq.com/slug: us-east-1-template
    tags.datadoghq.com/version: d2045fa78b728936ccabd1fc59c765fccb8359d5
    team.expediagroup.com/cost-center: '95193'
    version: d2045fa78b728936ccabd1fc59c765fccb8359d5
  annotations:
    app.expediagroup.com/data-classification: '<REDACTED>'
    app.expediagroup.com/service-tier: '<REDACTED>'
    capability.expediagroup.com/name: '<REDACTED>'
    domain.expediagroup.com/name: '<REDACTED>'
    island.expediagroup.com/account: '<REDACTED>'
    k8s.expediagroup.com/inject-vars: payment-orchestrator
    k8s.expediagroup.com/inject-vars-type: '<REDACTED>'
    k8s.expediagroup.com/installation-name.full: payment-orchestrator--branch-master
    kubectl.kubernetes.io/default-container: payment-orchestrator
    kubectl.kubernetes.io/default-logs-container: payment-orchestrator
    kubernetes.io/psp: eks.privileged
    prometheus.io/path: /stats/prometheus
    prometheus.io/port: '15020'
    prometheus.io/scrape: 'true'
    sidecar.istio.io/status: >-
      {"initContainers":["istio-init"],"containers":["istio-proxy"],"volumes":["workload-socket","workload-certs","istio-envoy","istio-data","istio-podinfo","istio-token","istiod-ca-cert"],"imagePullSecrets":null,"revision":"default"}
    splunk.com/index: ecp-ord-oms
    team.expediagroup.com/name: '<REDACTED>'
    vault.hashicorp.com/agent-init-first: 'true'
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/agent-inject-perms-secrets.json: '0664'
    vault.hashicorp.com/agent-inject-secret-secrets.json: orders/payment-orchestrator/kv-v2/data/payment-orchestrator/secrets
    vault.hashicorp.com/agent-inject-status: injected
    vault.hashicorp.com/agent-inject-template-secrets.json: >-
      {{- with secret
      "orders/payment-orchestrator/kv-v2/data/payment-orchestrator/secrets" }}
         {{- .Data.data | toUnescapedJSON }}
      {{- end }}         
    vault.hashicorp.com/agent-inject-token: 'false'
    vault.hashicorp.com/agent-run-as-user: '100'
    vault.hashicorp.com/namespace: lab/islands
    vault.hashicorp.com/role: payment-orchestrator.payment-orchestrator-test-us-east-1-master-template
  ownerReferences:
    - apiVersion: apps/v1
      kind: ReplicaSet
      name: payment-orchestrator-test-us-east-1-master-template-cb855cbc5
      uid: dcde033c-3899-42d0-aa3e-a1842f05d61b
      controller: true
      blockOwnerDeletion: true
  selfLink: >-
    /api/v1/namespaces/payment-orchestrator/pods/payment-orchestrator-test-us-east-1-master-template-cb855cq7x2f
spec:
  volumes:
    - name: workload-socket
      emptyDir: {}
    - name: workload-certs
      emptyDir: {}
    - name: istio-envoy
      emptyDir:
        medium: Memory
    - name: istio-data
      emptyDir: {}
    - name: istio-podinfo
      downwardAPI:
        items:
          - path: labels
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels
          - path: annotations
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.annotations
        defaultMode: 420
    - name: istio-token
      projected:
        sources:
          - serviceAccountToken:
              audience: istio-ca
              expirationSeconds: 43200
              path: istio-token
        defaultMode: 420
    - name: istiod-ca-cert
      configMap:
        name: istio-ca-root-cert
        defaultMode: 420
    - name: kube-api-access-chcnd
      projected:
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              name: kube-root-ca.crt
              items:
                - key: ca.crt
                  path: ca.crt
          - downwardAPI:
              items:
                - path: namespace
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
        defaultMode: 420
    - name: home-init
      emptyDir:
        medium: Memory
    - name: home-sidecar
      emptyDir:
        medium: Memory
    - name: vault-secrets
      emptyDir:
        medium: Memory
  initContainers:
    - name: vault-agent-init
      image: 782273268637.dkr.ecr.us-east-1.amazonaws.com/library/eg-vault:1.8.1
      command:
        - /bin/sh
        - '-ec'
      args:
        - >-
          echo ${VAULT_CONFIG?} | base64 -d > /home/vault/config.json && vault
          agent -config=/home/vault/config.json
      env:
        - name: VAULT_LOG_LEVEL
          value: info
        - name: VAULT_LOG_FORMAT
          value: standard
        - name: VAULT_CONFIG
          value: >-
            eyJhdXRvX2F1dGgiOnsibWV0aG9kIjp7InR5cGUiOiJrdWJlcm5ldGVzIiwibW91bnRfcGF0aCI6ImF1dGgva3ViZXJuZXRlcy9vcmRlcnMtZWdvcmRlcnMtdGVzdC11cy1lYXN0LTEtcmNwIiwibmFtZXNwYWNlIjoibGFiL2lzbGFuZHMiLCJjb25maWciOnsicm9sZSI6InBheW1lbnQtb3JjaGVzdHJhdG9yLnBheW1lbnQtb3JjaGVzdHJhdG9yLXRlc3QtdXMtZWFzdC0xLW1hc3Rlci10ZW1wbGF0ZSJ9fSwic2luayI6W3sidHlwZSI6ImZpbGUiLCJjb25maWciOnsicGF0aCI6Ii9ob21lL3ZhdWx0Ly52YXVsdC10b2tlbiJ9fV19LCJleGl0X2FmdGVyX2F1dGgiOnRydWUsInBpZF9maWxlIjoiL2hvbWUvdmF1bHQvLnBpZCIsInZhdWx0Ijp7ImFkZHJlc3MiOiJodHRwczovL3ZhdWx0LWVudGVycHJpc2Uuc2VjcmV0cy5ydW50aW1lLnRlc3QtY3RzLmV4cC1hd3MubmV0In0sInRlbXBsYXRlIjpbeyJkZXN0aW5hdGlvbiI6Ii92YXVsdC9zZWNyZXRzL3NlY3JldHMuanNvbiIsImNvbnRlbnRzIjoie3stIHdpdGggc2VjcmV0IFwib3JkZXJzL3BheW1lbnQtb3JjaGVzdHJhdG9yL2t2LXYyL2RhdGEvcGF5bWVudC1vcmNoZXN0cmF0b3Ivc2VjcmV0c1wiIH19XG4gICB7ey0gLkRhdGEuZGF0YSB8IHRvVW5lc2NhcGVkSlNPTiB9fVxue3stIGVuZCB9fSAgICAgICAgICIsImxlZnRfZGVsaW1pdGVyIjoie3siLCJyaWdodF9kZWxpbWl0ZXIiOiJ9fSIsInBlcm1zIjoiMDY2NCJ9XSwidGVtcGxhdGVfY29uZmlnIjp7ImV4aXRfb25fcmV0cnlfZmFpbHVyZSI6dHJ1ZX19
      resources:
        limits:
          cpu: 500m
          memory: 128Mi
        requests:
          cpu: 250m
          memory: 64Mi
      volumeMounts:
        - name: home-init
          mountPath: /home/vault
        - name: kube-api-access-chcnd
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        - name: vault-secrets
          mountPath: /vault/secrets
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
      securityContext:
        capabilities:
          drop:
            - ALL
        runAsUser: 100
        runAsGroup: 1000
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
    - name: istio-init
      image: >-
        782273268637.dkr.ecr.us-east-1.amazonaws.com/thirdparty/docker.io/istio/proxyv2:1.14.1-distroless
      args:
        - istio-iptables
        - '-p'
        - '15001'
        - '-z'
        - '15006'
        - '-u'
        - '1337'
        - '-m'
        - REDIRECT
        - '-i'
        - '*'
        - '-x'
        - ''
        - '-b'
        - '*'
        - '-d'
        - 15090,15021,15020
      env:
        - name: BOOTSTRAP_XDS_AGENT
          value: 'true'
      resources:
        limits:
          cpu: '2'
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 128Mi
      volumeMounts:
        - name: vault-secrets
          mountPath: /vault/secrets
        - name: kube-api-access-chcnd
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
            - NET_RAW
          drop:
            - ALL
        privileged: false
        runAsUser: 0
        runAsGroup: 0
        runAsNonRoot: false
        readOnlyRootFilesystem: false
        allowPrivilegeEscalation: false
  containers:
    - name: istio-proxy
      image: >-
        <REDACTED>.dkr.ecr.us-east-1.amazonaws.com/thirdparty/docker.io/istio/proxyv2:1.14.1-distroless
      args:
        - proxy
        - sidecar
        - '--domain'
        - $(POD_NAMESPACE).svc.cluster.local
        - '--proxyLogLevel=warning'
        - '--proxyComponentLogLevel=misc:error'
        - '--log_output_level=default:info'
        - '--concurrency'
        - '4'
      ports:
        - name: http-envoy-prom
          containerPort: 15090
          protocol: TCP
      env:
        - name: JWT_POLICY
          value: third-party-jwt
        - name: PILOT_CERT_PROVIDER
          value: istiod
        - name: CA_ADDR
          value: istiod.istio-system.svc:15012
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.serviceAccountName
        - name: HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: PROXY_CONFIG
          value: >
            {"concurrency":4,"tracing":{"datadog":{"address":"datadog-agent.datadog.svc.cluster.local:8126"},"maxPathTagLength":256,"sampling":1},"proxyMetadata":{"BOOTSTRAP_XDS_AGENT":"true"},"holdApplicationUntilProxyStarts":true}
        - name: ISTIO_META_POD_PORTS
          value: |-
            [
                {"name":"http","containerPort":8080,"protocol":"TCP"}
            ]
        - name: ISTIO_META_APP_CONTAINERS
          value: payment-orchestrator
        - name: ISTIO_META_CLUSTER_ID
          value: Kubernetes
        - name: ISTIO_META_INTERCEPTION_MODE
          value: REDIRECT
        - name: ISTIO_META_WORKLOAD_NAME
          value: payment-orchestrator-test-us-east-1-master-template
        - name: ISTIO_META_OWNER
          value: >-
            kubernetes://apis/apps/v1/namespaces/payment-orchestrator/deployments/payment-orchestrator-test-us-east-1-master-template
        - name: ISTIO_META_MESH_ID
          value: orders.test.exp-aws.net
        - name: TRUST_DOMAIN
          value: orders.test.exp-aws.net
        - name: BOOTSTRAP_XDS_AGENT
          value: 'true'
        - name: ISTIO_KUBE_APP_PROBERS
          value: >-
            {"/app-health/payment-orchestrator/livez":{"httpGet":{"path":"/healthcheck/status","port":8080,"scheme":"HTTP"},"timeoutSeconds":20},"/app-health/payment-orchestrator/readyz":{"httpGet":{"path":"/healthcheck/status","port":8080,"scheme":"HTTP"},"timeoutSeconds":20},"/app-health/payment-orchestrator/startupz":{"httpGet":{"path":"/healthcheck/status","port":8080,"scheme":"HTTP"},"timeoutSeconds":20}}
      resources:
        limits:
          cpu: '2'
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 128Mi
      volumeMounts:
        - name: workload-socket
          mountPath: /var/run/secrets/workload-spiffe-uds
        - name: workload-certs
          mountPath: /var/run/secrets/workload-spiffe-credentials
        - name: istiod-ca-cert
          mountPath: /var/run/secrets/istio
        - name: istio-data
          mountPath: /var/lib/istio/data
        - name: istio-envoy
          mountPath: /etc/istio/proxy
        - name: istio-token
          mountPath: /var/run/secrets/tokens
        - name: istio-podinfo
          mountPath: /etc/istio/pod
        - name: vault-secrets
          mountPath: /vault/secrets
        - name: kube-api-access-chcnd
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      readinessProbe:
        httpGet:
          path: /healthz/ready
          port: 15021
          scheme: HTTP
        initialDelaySeconds: 1
        timeoutSeconds: 3
        periodSeconds: 2
        successThreshold: 1
        failureThreshold: 30
      lifecycle:
        postStart:
          exec:
            command:
              - pilot-agent
              - wait
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
      securityContext:
        capabilities:
          drop:
            - ALL
        privileged: false
        runAsUser: 1337
        runAsGroup: 1337
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
    - name: payment-orchestrator
      image: >-
        <REDACTED>/library/payment-orchestrator:d2045fa78b728936ccabd1fc59c765fccb8359d5
      ports:
        - name: http
          containerPort: 8080
          protocol: TCP
      env:
        - name: AWS_REGION
          value: us-east-1
        - name: DD_LOGS_INJECTION
          value: 'true'
        - name: DD_TRACE_DB_CLIENT_SPLIT_BY_DOMAIN
          value: 'true'
        - name: DD_TRACE_DB_CLIENT_SPLIT_BY_INSTANCE
          value: 'true'
        - name: DD_TRACE_SPLIT_BY_TAGS
          value: >-
            aws.service,aws.bucket.name,aws.table.name,aws.queue.name,aws.stream.name
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: FLAVOR
          value: test-us-east-1
        - name: DD_TAGS
          value: slug:us-east-1
        - name: DEP_TYPE
          value: rcp
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: DD_ENTITY_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
        - name: DD_SERVICE
          value: payment-orchestrator
        - name: DD_VERSION
          value: d2045fa78b728936ccabd1fc59c765fccb8359d5
      resources:
        limits:
          cpu: '2'
          memory: 9Gi
        requests:
          cpu: '2'
          memory: 9Gi
      volumeMounts:
        - name: kube-api-access-chcnd
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        - name: vault-secrets
          mountPath: /vault/secrets
      livenessProbe:
        httpGet:
          path: /app-health/payment-orchestrator/livez
          port: 15020
          scheme: HTTP
        initialDelaySeconds: 120
        timeoutSeconds: 20
        periodSeconds: 60
        successThreshold: 1
        failureThreshold: 10
      readinessProbe:
        httpGet:
          path: /app-health/payment-orchestrator/readyz
          port: 15020
          scheme: HTTP
        initialDelaySeconds: 120
        timeoutSeconds: 20
        periodSeconds: 60
        successThreshold: 1
        failureThreshold: 7
      startupProbe:
        httpGet:
          path: /app-health/payment-orchestrator/startupz
          port: 15020
          scheme: HTTP
        initialDelaySeconds: 120
        timeoutSeconds: 20
        periodSeconds: 60
        successThreshold: 1
        failureThreshold: 3
      lifecycle:
        preStop:
          exec:
            command:
              - /bin/sleep
              - '10'
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
    - name: vault-agent
      image: 782273268637.dkr.ecr.us-east-1.amazonaws.com/library/eg-vault:1.8.1
      command:
        - /bin/sh
        - '-ec'
      args:
        - >-
          echo ${VAULT_CONFIG?} | base64 -d > /home/vault/config.json && vault
          agent -config=/home/vault/config.json
      env:
        - name: VAULT_LOG_LEVEL
          value: info
        - name: VAULT_LOG_FORMAT
          value: standard
        - name: VAULT_CONFIG
          value: >-
            eyJhdXRvX2F1dGgiOnsibWV0aG9kIjp7InR5cGUiOiJrdWJlcm5ldGVzIiwibW91bnRfcGF0aCI6ImF1dGgva3ViZXJuZXRlcy9vcmRlcnMtZWdvcmRlcnMtdGVzdC11cy1lYXN0LTEtcmNwIiwibmFtZXNwYWNlIjoibGFiL2lzbGFuZHMiLCJjb25maWciOnsicm9sZSI6InBheW1lbnQtb3JjaGVzdHJhdG9yLnBheW1lbnQtb3JjaGVzdHJhdG9yLXRlc3QtdXMtZWFzdC0xLW1hc3Rlci10ZW1wbGF0ZSJ9fSwic2luayI6W3sidHlwZSI6ImZpbGUiLCJjb25maWciOnsicGF0aCI6Ii9ob21lL3ZhdWx0Ly52YXVsdC10b2tlbiJ9fV19LCJleGl0X2FmdGVyX2F1dGgiOmZhbHNlLCJwaWRfZmlsZSI6Ii9ob21lL3ZhdWx0Ly5waWQiLCJ2YXVsdCI6eyJhZGRyZXNzIjoiaHR0cHM6Ly92YXVsdC1lbnRlcnByaXNlLnNlY3JldHMucnVudGltZS50ZXN0LWN0cy5leHAtYXdzLm5ldCJ9LCJ0ZW1wbGF0ZSI6W3siZGVzdGluYXRpb24iOiIvdmF1bHQvc2VjcmV0cy9zZWNyZXRzLmpzb24iLCJjb250ZW50cyI6Int7LSB3aXRoIHNlY3JldCBcIm9yZGVycy9wYXltZW50LW9yY2hlc3RyYXRvci9rdi12Mi9kYXRhL3BheW1lbnQtb3JjaGVzdHJhdG9yL3NlY3JldHNcIiB9fVxuICAge3stIC5EYXRhLmRhdGEgfCB0b1VuZXNjYXBlZEpTT04gfX1cbnt7LSBlbmQgfX0gICAgICAgICAiLCJsZWZ0X2RlbGltaXRlciI6Int7IiwicmlnaHRfZGVsaW1pdGVyIjoifX0iLCJwZXJtcyI6IjA2NjQifV0sInRlbXBsYXRlX2NvbmZpZyI6eyJleGl0X29uX3JldHJ5X2ZhaWx1cmUiOnRydWV9fQ==
      resources:
        limits:
          cpu: 500m
          memory: 128Mi
        requests:
          cpu: 250m
          memory: 64Mi
      volumeMounts:
        - name: kube-api-access-chcnd
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        - name: home-sidecar
          mountPath: /home/vault
        - name: vault-secrets
          mountPath: /vault/secrets
      lifecycle: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
      securityContext:
        capabilities:
          drop:
            - ALL
        runAsUser: 100
        runAsGroup: 1000
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  nodeSelector:
    karpenter-provisioner-type: standard
  serviceAccountName: payment-orchestrator-test-us-east-1-master-template
  serviceAccount: payment-orchestrator-test-us-east-1-master-template
  securityContext:
    fsGroup: 1337
  imagePullSecrets:
    - name: <REDACTED>
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: payment-orchestrator
                k8s.expediagroup.com/instance: master
                k8s.expediagroup.com/release: test-us-east-1
                progressivedeployment.expediagroup.com/variant: template
            topologyKey: kubernetes.io/hostname
  schedulerName: default-scheduler
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
  priority: 0
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: payment-orchestrator
          k8s.expediagroup.com/instance: master
          k8s.expediagroup.com/release: test-us-east-1
          progressivedeployment.expediagroup.com/variant: template
```

**Comment by ra-grover** [comment] 2022-08-17 20:41
Allocatable sections of the node:
```
osting ready status
Addresses:
  InternalIP:   10.74.7.176
  Hostname:     ip-10-74-7-176.ec2.internal
  InternalDNS:  ip-10-74-7-176.ec2.internal
Capacity:
  attachable-volumes-aws-ebs:  25
  cpu:                         16
  ephemeral-storage:           104845292Ki
  hugepages-1Gi:               0
  hugepages-2Mi:               0
  memory:                      32062752Ki
  pods:                        234
Allocatable:
  attachable-volumes-aws-ebs:  25
  cpu:                         15890m
  ephemeral-storage:           95551679124
  hugepages-1Gi:               0
  hugepages-2Mi:               0
  memory:                      29063456Ki
  pods:                        234
```

**Comment by ra-grover** [comment] 2022-08-17 20:46
We have Karpenter installed in `100s` of EKS clusters and we were intermittently facing issues where the older version `0.10.1` was not responding to Pending pods at all. 
We validated via Api server logs too, there were events that the pod is pending and Karpenter kicked in only after hours. This is just one example, we have our customers reporting several of those in Prod and becomes blocker for our customers.

We decided to upgrade it yesterday to `0.13.2` after we couldn't relate the Issue with the insight through the metrics, and now we landed into this issue.

**Comment by tzneal** [comment] 2022-08-17 21:31
Pods are scheduled based off of the effective requests, defined [here](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#resources).  In this pod's case, since the sum of the non-init container requests is larger than the init container requests, that's the resource request used which is 2350m CPU.  For some reason we apparently thought it would schedule on the node.  There are a few potential causes related to either not identifying that the node is fully initialized yet or an error in calculating the number of resources that are scheduled against the node.

Does that node have a `karpenter.sh/initialized: "true"` label applied?

**Comment by cebernardi** [comment] 2022-08-18 08:58
relates to https://github.com/aws/karpenter/issues/2250

**Comment by ra-grover** [comment] 2022-08-18 13:10
Heya,
Yes the node has the initialised label on it. More details regarding instance type:
```  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/instance-type: c5.4xlarge
    beta.kubernetes.io/os: linux
    failure-domain.beta.kubernetes.io/region: us-east-1
    failure-domain.beta.kubernetes.io/zone: us-east-1a
    k8s.io/cloud-provider-aws: ad5a582408e1a88def9b3134c6b134d3
    karpenter-provisioner-type: standard
    karpenter.sh/capacity-type: spot
    karpenter.sh/initialized: "true"
    karpenter.sh/provisioner-name: general-provisioner
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: ip-10-74-7-176.ec2.internal
    kubernetes.io/os: linux
    node.kubernetes.io/instance-type: c5.4xlarge
    topology.ebs.csi.aws.com/zone: us-east-1a
    topology.kubernetes.io/region: us-east-1
    topology.kubernetes.io/zone: us-east-1a
    ```

**Comment by cebernardi** [comment] 2022-08-18 15:14
We noticed that we have some daemonsets with either no resources requests nor limits specified. 
Could this interfere with Karpenter calculation of the available resources on a node?

**Comment by ra-grover** [comment] 2022-08-18 15:27
Does this work or I can redact the names for you. 

<img width="518" alt="Screenshot 2022-08-18 at 11 25 29 AM" src="https://user-images.githubusercontent.com/93419161/185433449-58730c69-e7b3-42f2-b1ef-44d9f47def4a.png">

**Comment by tzneal** [comment] 2022-08-18 15:28
That's good, I just needed the numbers.  Thanks!

**Comment by tzneal** [comment] 2022-08-18 15:29
@ra-grover Is that the same node that shows CPU request total of 13641m?

**Comment by ra-grover** [comment] 2022-08-18 15:30
I am aslo trying to reproduce the issue, to bring it to a state where the pending pods is there and I can connect the Karpenter controller locally then to debug the calculations.

**Comment by ra-grover** [comment] 2022-08-18 15:31
> @ra-grover Is that the same node that shows CPU request total of 13641m?

Yes its the same node.

**Comment by ra-grover** [comment] 2022-08-18 15:34
<img width="520" alt="Screenshot 2022-08-18 at 11 34 19 AM" src="https://user-images.githubusercontent.com/93419161/185435424-95690de3-69ab-46ec-a821-3a3ac22dd830.png">

No its a little less, some pod may have moved.

**Comment by tzneal** [comment] 2022-08-18 15:41
Do you use limit ranges on your namespaces?

**Comment by ra-grover** [comment] 2022-08-18 15:46
No we dont.
Correct me if I am wrong @cebernardi .

**Comment by cebernardi** [comment] 2022-08-18 15:52
I confirm we don't

**Comment by tzneal** [comment] 2022-08-18 15:57
If you see it happen again, can you provide the list of pod requests, the matching summary and the node capacity/allocatable while it's occurring?  I haven't been able to reproduce it here and looking at the code don't see anything yet related to how we could compute the resources incorrectly.

**Comment by cebernardi** [comment] 2022-08-18 16:00
The CPU requests sum up for me

**Comment by tzneal** [comment] 2022-08-18 18:55
Any chance you are using pod overhead? https://kubernetes.io/docs/concepts/scheduling-eviction/pod-overhead/

**Comment by ra-grover** [comment] 2022-08-18 19:22
Nopes. So I have been able to reproduce it just now on the same host. 
```
  ~ k get pod REDACTED -n payment-orchestrator -o yaml  |grep req -A2
      requests:
        cpu: 100m
        memory: 128Mi
--
      requests:
        cpu: 3101m
        memory: 9Gi
--
      requests:
        cpu: 250m
        memory: 64Mi
--
      requests:
        cpu: 250m
        memory: 64Mi
--
      requests:
        cpu: 100m
        memory: 128Mi
```
`k describe node ip-10-74-7-176.ec2.internal` => 
```
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource                    Requests      Limits
  --------                    --------      ------
  cpu                         12441m (78%)  43900m (276%)
  memory                      8200Mi (28%)  23776Mi (83%)
  ephemeral-storage           0 (0%)        0 (0%)
  hugepages-1Gi               0 (0%)        0 (0%)
  hugepages-2Mi               0 (0%)        0 (0%)
  attachable-volumes-aws-ebs  0             0
```
```
Allocatable:
  attachable-volumes-aws-ebs:  25
  cpu:                         15890m
  ephemeral-storage:           95551679124
  hugepages-1Gi:               0
  hugepages-2Mi:               0
  memory:                      29063456Ki
  pods:                        234
```
3449 is left on the node, while the pod request for 3801.

**Comment by ra-grover** [comment] 2022-08-18 19:23
And its again stuck on:
```2022-08-18T19:18:14.261Z	DEBUG	controller.events	Normal	{"commit": "062a029", "object": {"kind":"Pod","namespace":"REDACTED","name":"REDACTED-test-us-east-1-master-template-7d544bg9wgr","uid":"abf3bac2-63f3-422b-8965-14132b41bc93","apiVersion":"v1","resourceVersion":"384328637"}, "reason": "NominatePod", "message": "Pod should schedule on ip-10-74-7-176.ec2.internal"}
```

**Comment by tzneal** [comment] 2022-08-18 19:47
Can you show the pods cpu/memory requests that are scheduled to the node at the same time as the node resource request summary?

**Comment by ra-grover** [comment] 2022-08-18 19:52
<img width="567" alt="Screenshot 2022-08-18 at 3 51 05 PM" src="https://user-images.githubusercontent.com/93419161/185482410-1bdb9c6c-650b-4e05-999b-28f7f7e11ebd.png">

<img width="470" alt="Screenshot 2022-08-18 at 3 51 46 PM" src="https://user-images.githubusercontent.com/93419161/185482526-4348ae69-3d23-4fb8-a56c-60fee0e60b07.png">

Let me know if anything else is needed.

**Comment by ra-grover** [comment] 2022-08-18 19:56
I have a local debugger attached to the remote Cluster, this is a test cluster of a customer but I can afford not more than 30 mins to have this test app down. 
Would you like to hop on to a call and debug any calculations with me if you want ?

**Comment by tzneal** [comment] 2022-08-19 19:12
Fixed with https://github.com/aws/karpenter/pull/2322

**Closed by tzneal** 2022-08-19 19:12 UTC
Labels: bug
