### ISSUE TITLE
dynamic volume size based on instance size

### ISSUE THREAD

**Issue by cburroughs** [aws/karpenter#4302] opened 2023-07-19 18:05 UTC
### Description

**What problem are you trying to solve?**

Pulling https://github.com/aws/karpenter/issues/939#issuecomment-1401958630 into an open issue.

"Bigger" instances tend to use more space (if only for the variety of images they accumulate) but the size of the  volume is fixed per node template.  Sometimes the biggest instances run out of space while the smaller ones have mostly empty disks.

We could have small/medium/large (node-template, provisioner) pairs, but that is a bunch of extra management overhead to vary a single value.  If it would be nice if instead the volume size could varry with the "size" of the instance.

**How important is this feature to you?**

Nice to have, until over-provisioning becomes a cost problem.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment] 2023-07-19 21:23
@cburroughs Closing this as a duplicate of #2394. Feel free to add your thoughts in that issue 👍

**Closed by jonathan-innis** 2023-07-19 21:23 UTC
Labels: feature
