### ISSUE TITLE
How should I be forcing an update of all my nodes?

### ISSUE THREAD

**Issue by domgoodwin** [aws/karpenter#4256] opened 2023-07-11 15:26 UTC
### Description

**How can the docs be improved?**

If I upgrade a Kubernetes version or change my node user data, how should I trigger a node refresh - draining and evicting nodes one by one - without having to `kubectl delete` each node.

In a previous version I was setting `karpenter.sh/voluntary-disruption="drifted"` onto all nodes and letting Karpenter drain and replace them. It now seems if a node isn't actually due an update Karpenter removes this annotation from nodes.

I have found success in setting `ttlSecondsUntilExpired` to a very low amount so all nodes are cycled and then quickly changing it back (but I worry about potentially leaving this low).

This might be a feature request if there isn't a nice way to do this, but I figure there is a way it just needs documenting?
I'm basically looking for the equivalent of an ASG instance refresh.

**Comment by engedaam** [comment] 2023-07-12 15:24
We are in the progress of adding instance refresh for userData https://karpenter.sh/docs/concepts/deprovisioning/#drift. In v0.29.0, we added security group and subnet drift. We expect to release to more fields karpenter will respect for instance refresh.

**Comment by njtran** [comment] 2023-07-14 17:37
Closing as a duplicate of https://github.com/aws/karpenter/issues/4231

**Closed by njtran** 2023-07-14 17:37 UTC
Labels: question
