### ISSUE TITLE
Issue with leader election, context deadline exceeded

### ISSUE THREAD

**Issue by sidick** [aws/karpenter#3586] opened 2023-03-13 15:16 UTC
### Version

__Karpenter Version:__ v0.26.1

__Kubernetes Version:__ v1.23.16-eks-48e63af

### Expected Behavior

Karpenter should run with no issues and have no problems with k8s leadership elections

### Actual Behavior

We have three clusters which are deployed via code and are identical in most respects. On one cluster (our production one), we see Karpenter often panic due to a timeout while performing the leadership election. 

### Steps to Reproduce the Problem

On this one cluster it happens frequently (multiple times per day), but I've not managed to reproduce it on any other cluster.

### Resource Specs and Logs

Karpenter is running on Fargate in an EKS cluster (v1.23 eks.6, identical version to the other clusters), there are no limits introduced with the Helm deployment. 
```
NAME                         READY   STATUS             RESTARTS       AGE
karpenter-6c45f79d55-cv528   0/1     CrashLoopBackOff   25 (83s ago)   90m
```
This can happen anytime, either when starting or after the pod has been up for a few hours
[karpenter_1_log.txt](https://github.com/aws/karpenter/files/10958774/karpenter_1_log.txt)

When running two replicas they both has this issue.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by sidick** [comment] 2023-03-13 20:15
> Can you share details on your controller pod spec resource requests/limits? Typically, I've seen this issue primarily when Karpenter doesn't have enough CPU cores attributed to it to run and the go thread that is refreshing the leader lease isn't able to refresh the lease before the context timeout ends.

Yep sure. I'm using the standard helm chart and not specifying any limits so it's using the lowest Fargate instance with nothing added to the limits section.

**Comment by sidick** [comment] 2023-03-14 14:08
I'm going to cautiously say this was fixed by actually setting a limit to ensure Fargate gave us a powerful enough node, it seems 0.25 vcpu isn't enough for our production environment :)

**Comment by sidick** [comment] 2023-03-14 17:12
OK, it's been 5 hours now with no issues, I'll close this as it looks like the initial idea was correct, by default fargate will give too small a node unless there are some limits specified.

**Comment by jonathan-innis** [comment] 2023-03-15 20:49
I'm going to re-open this because I've still seen issues like this with large-scale-ups where the scheduling loop takes quite long. Even with a core requested/limited on Karpenter's deployment, I've seen the controller crash because it can't renew its lease

**Comment by jonathan-innis** [comment] 2023-07-05 18:53
Closing as a duplicate of #4168

**Closed by jonathan-innis** 2023-07-05 18:53 UTC
Labels: bug
