### ISSUE TITLE
v1beta1 Laundry List

### ISSUE THREAD

**Issue by ellistarn** [aws/karpenter#1327] opened 2022-02-11 20:28 UTC
**Tell us about your request**
This issue contains a list of breaking API changes for v1beta1.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment] 2022-02-11 20:28
Fix casing on capacity type to conform w/ k8s value casing:
`on-demand` -> `OnDemand`
`spot` -> `Spot`

**Comment by ellistarn** [comment] 2022-02-11 20:32
I'd love to explore separating the `spec.provider` into a separate vendor specific CRD and using something like `spec.providerRef`.

**Comment by ellistarn** [comment] 2022-02-11 20:34
I'd like to rename `spec.kubeletConfiguration` to `spec.kubelet`

**Comment by ellistarn** [comment] 2022-02-11 20:36
I'd like to explore creating a decoupled `Deprovisioner` resource with `spec.selector` that encapsulates `spec.ttlSecondsAfterEmpty`, `spec.ttlSecondsAfterExpired`, and #1091.

**Comment by felix-zhe-huang** [comment] 2022-02-11 20:45
I'd like to explore adding `spec.preferenceWeight` to indicate the preference of which provisioner should be selected when multiple are compatible to the pod spec.

**Comment by ellistarn** [comment] 2022-02-11 20:53
> I'd like to explore adding `spec.preferenceWeight` to indicate the preference of which provisioner should be selected when multiple are compatible to the pod spec.

Check out the related discussion here: https://github.com/aws/karpenter/issues/783

**Comment by felix-zhe-huang** [comment] 2022-02-16 01:45
Another thought. Remove provisioner labels. Everything will be described as requirements. When Karpenter launches new nodes, a label will be added to the node with a valid value from the combined requirements (provisioner + pods).

**Comment by robertd** [comment] 2022-02-18 23:09
Thanks for the transparency ... I'll definitely be monitoring this issue for changes that need to be applied to the cdk-karpenter: https://www.npmjs.com/package/cdk-karpenter 👍

**Comment by ellistarn** [comment] 2022-03-01 17:47
Remove kubeletconfiguration.clusterdnsip in favor of discovery https://github.com/aws/karpenter/issues/1241#issuecomment-1055697350

**Comment by stevehipwell** [comment] 2022-03-10 12:54
> I'd like to explore separating the spec.provider into a separate vendor specific CRD and using something like spec.providerRef.

Like `IngressClassParams`?

We set these options via LTs currently (good defaults could mitigate some of them), I'm happy to open separate issues for any of these which warrant it.

- `spec.kubelet.maxPods`
- `spec.kubelet.kubeletReserved`
- Registry credentials (set in _/var/lib/kubelet/config.json_ for AL2 and in TOML as of last BottleRocket release)
- AWS provider container runtime for AL2

I've listed a couple of items above related to the ones already listed, but I think there might need to be some additional thought given to generic K8s settings vs provider settings. For example I'd suggest that `spec.kubelet.maxPods` should default to `110` and `spec.kubelet.kubeletReserved` should default to a dynamic calculation (the GKE one) but be overridable; the AWS provider might override these defaults based on it's settings (constraining down set values might also be desired).

**Comment by vumdao** [comment] 2022-04-01 08:23
I'd like to add detailed property for `provider` in CRD https://github.com/aws/karpenter/blob/main/charts/karpenter/crds/karpenter.sh_provisioners.yaml so that I can import it into CDK8S API
```
cdk8s import https://raw.githubusercontent.com/aws/karpenter/main/charts/karpenter/crds/karpenter.sh_provisioners.yaml
```

Current property of provider is useless to reference
```
  /**
   * Provider contains fields specific to your cloudprovider.
   *
   * @schema ProvisionerSpec#provider
   */
  readonly provider?: any;
```

**Comment by ellistarn** [comment] 2022-04-20 00:16
@stevehipwell is https://github.com/aws/karpenter/issues/1327#issuecomment-1036613965 still useful to you? We were curious about what the specific use case is. It's pretty straightforward to implement, but we weren't sure it was still necessary.

**Comment by ellistarn** [comment] 2022-04-20 00:34
Related: https://github.com/aws/karpenter/issues/967

**Comment by stevehipwell** [comment] 2022-04-20 09:30
> @stevehipwell is https://github.com/aws/karpenter/issues/1327#issuecomment-1036613965 still useful to you? We were curious about what the specific use case is. It's pretty straightforward to implement, but we weren't sure it was still necessary.

@ellistarn yes this is still very important to our use case.

**Comment by stevehipwell** [comment] 2022-04-20 09:42
@ellistarn is the provisioner failure logic documented anywhere? And is the specific failure logic for AWS also documented?

**Comment by Cagafuego** [comment] 2022-04-21 14:08
> @stevehipwell is [#1327 (comment)](https://github.com/aws/karpenter/issues/1327#issuecomment-1036613965) still useful to you? We were curious about what the specific use case is. It's pretty straightforward to implement, but we weren't sure it was still necessary.

Just wanted to chime in on this with a use case I have, hope that is ok. We are setting up a multi-architecture cluster that supports both amd64 and arm64. Because of certain requirements we have on our end, we have to use custom launch templates and cannot allow Karpenter to generate them for us. Since we want to use multiple architectures, we then need to have multiple launch templates since the AMI will be different for each. That means we need multiple provisioners. If we have a pending pod that supports both architectures, we would like for Karpenter to prefer the arm64 nodes. 

What we would ultimately want would be for Karpenter to select the cheapest option when multiple provisioners match with a pending pod or pods. However, just having a simple priority mechanism would be enough to get us most of the way there.


> @stevehipwell is [#1327 (comment)](https://github.com/aws/karpenter/issues/1327#issuecomment-1036613965) still useful to you? We were curious about what the specific use case is. It's pretty straightforward to implement, but we weren't sure it was still necessary.

Just wanted to chime in on this with a use case I have, hope that is ok. We are setting up a multi-architecture cluster that supports both amd64 and arm64. Because of certain requirements we have on our end, we have to use custom launch templates and cannot allow Karpenter to generate them for us. Since we want to use multiple architectures, we then need to have multiple launch templates since the AMI will be different for each. That means we need multiple provisioners. If we have a pending pod that supports both architectures, we would like for Karpenter to prefer the arm64 nodes. 

What we would ultimately want would be for Karpenter to select the cheapest option when multiple provisioners match with a pending pod or pods. However, just having a simple priority mechanism would be enough to get us most of the way there.

**Comment by stevehipwell** [comment] 2022-04-21 14:17
@Cagafuego I think there is a discussion somewhere with requests to move capabilities out of custom LTs you might want to add your requirements there?

**Comment by tzneal** [comment] 2022-04-21 14:20
Thanks @stevehipwell  Yes, there is a PR with a doc at https://github.com/aws/karpenter/pull/1691 that talks about what we are looking at exposing to hopefully eliminate the need to use custom LTs.  Feel free to add questions/comments there.

Ping @suket22

**Comment by stevehipwell** [comment] 2022-05-13 15:32
@tzneal I've looked over [custom-user-data-and-amis.md](https://github.com/aws/karpenter/blob/main/designs/aws/custom-user-data-and-amis.md) and have some feedback.

- We need the ability to provide an AMI per architecture otherwise we need to duplicate provisioners
- We need the ability to set kube reserved dynamically as it's a function of the node resources (see #1803)

**Comment by ellistarn** [comment] 2022-05-23 16:39
I hate to relitigate this, but the syntactic sugar of `aws-ids` doesn't sit well with me due to the "comma-separated-string" semantic. I'd like to explore strongly typing this with something like:
```
securityGroupIDs:
 - ...
 - ...
subnetIDs:
  - ...
  - ...
```

**Comment by stevehipwell** [comment] 2022-05-23 16:43
> I hate to relitigate this, but the syntactic sugar of aws-ids doesn't sit well with me due to the "comma-separated-string" semantic. This creates nested formatting within our yaml, which is tricky to read, write, and parse.

@ellistarn I agree with your view on this; I'd also add that the ID should be preferred for AWS resources with an ID. I think the launch template lookup is currently on name only?

**Comment by ellistarn** [comment] 2022-05-23 16:47
> @ellistarn I agree with your view on this; I'd also add that the ID should be preferred for AWS resources with an ID. I think the launch template lookup is currently on name only?

We prefer user controlled identifiers (names, tags) rather than system controlled identifiers (ids) since it removes a serialized creation requirement where each resource needs to know the output of its dependencies (i.e. "wire it up"). This enables static config files and minimizes logic for things like cfn/terraform. 

The securitygroup/subnet ID problem emerged from a limitation on shared VPCs where tags could not be read, which broke the selector semantic.

**Comment by stevehipwell** [comment] 2022-05-23 16:55
@ellistarn I'm not sure of any benefits to using names, but can see lots of limitations. By providing an ID I'm guaranteed that if something significant changes I'll get an error and not unexpected behaviour. Names are effectively sliding identifiers in AWS so just as you wouldn't use the `latest` tag for an OCI image in production a resource name shouldn't be used in a desired state system.

In addition to the above infrastructure is likely to be layered, so adding a tag to a subnet for Karpenter isn't going to be possible or even desirable for a lot of people. I personally tried adding Karpenter to an EKS cluster built with a complex Terraform module and not being able to use ID for everything breaks our architecture practices.

**Comment by ellistarn** [comment] 2022-07-19 20:17
Add `node.k8s.aws/instance-category` and `node.k8s.aws/instance-generation` to the AWS cloud provider.
Consider defaulting them in the provisioner to avoid potential breaking changes to existing production infrastructure upon release of new categories and generations.

**Comment by ellistarn** [comment] 2022-07-21 21:00
Deprecate these: https://github.com/aws/karpenter/blob/main/pkg/cloudprovider/aws/apis/v1alpha1/register.go#L76

**Comment by bwagner5** [comment] 2022-07-22 18:31
Include properly nested image attributes in the helm chart: 
https://github.com/aws/karpenter/pull/1737
https://github.com/aws/karpenter/issues/2151

**Comment by ellistarn** [comment] 2022-07-26 15:06
Invert polarity of config booleans: aws-eni-limited-pod-density

**Comment by ellistarn** [comment] 2022-08-01 21:16
Rename AWSNodeTemplate to NodeTemplate under the api group karpenter.k8s.aws. This allows for `k get nodetemplates` regardless which cloud you're on.

**Comment by tzneal** [comment] 2022-08-22 16:09
Look at being more opinionated on instance types (e.g. exclude d3 unless specifically requested)

**Comment by ellistarn** [comment] 2022-10-31 15:46
Consider renaming Provisioner -> NodeAutoscaler. Provisioners go both up and down, and the name collides with other provisioner concepts (e.g. https://kubernetes.io/docs/concepts/storage/storage-classes/#provisioner)

**Comment by vadimgusev-codefresh** [comment] 2022-11-15 19:09
Switch to [Go Duration](https://pkg.go.dev/time#Duration) format: `ttlSecondsUntilExpired: 604800` -> `ttlUntilExpired: 1w`

**Comment by grosser** [comment] 2022-11-16 04:36
> Switch to [Go Duration](https://pkg.go.dev/time#Duration) format: `ttlSecondsUntilExpired: 604800` -> `ttlUntilExpired: 1w` for a weekly node refresh.
also: `ttlUntilExpired` is a bit duplicated, something like `expirationTimeout` or just `ttl` might be cleaner

**Comment by ellistarn** [comment] 2022-11-16 18:16
>  just ttl might be cleaner

Agree. However, we do need to consider this field in the context of the emptinessTTL. Maybe `expirationTTL` is a good happy medium?

**Comment by ellistarn** [comment] 2022-11-17 23:55
https://github.com/aws/karpenter/issues/1327#issuecomment-1036595464 is no longer relevant, since they are now label values, not enum values.

**Comment by jonathan-innis** [comment] 2023-02-22 00:19
> Rename AWSNodeTemplate to NodeTemplate under the api group karpenter.k8s.aws. This allows for `k get nodetemplates` regardless which cloud you're on, and the API group varies.

You could do this with short names, without having to rename the CRD name

**Comment by ellistarn** [comment] 2023-03-02 21:20
@jonathan-innis , I was thinking about the idea of moving from instanceProfile -> iamRole. Instance Profiles are kind of awkward, since they don't appear in the AWS console, and are specific to EC2 instance launches. 

You could imagine that we automatically create an instance profile per AWSNodeTemplate, and attach the corresponding IAMRole to it. Users would specify the IAMRole at the global configmap or Provisioner CRD level. 

Related: https://github.com/aws/karpenter/issues/3051

**Comment by sftim** [comment] 2023-03-02 21:42
We can tag the instance profile too. I think that's a helpful thing to do.

I might want to have different roles for different provisioners though. For example, nodes made through the the monkey-of-chaos provisioner are allowed to invoke  `ec2:SendDiagnosticInterrupt` to themselves (and only to themselves). The other nodes aren't allowed to use that API at all.

Does this change limit my options there? I know I could use a DaemonSet, but IRSA gives all the Pods in a DaemonSet the same role - and no node-level identity.

**Comment by sftim** [comment] 2023-03-02 21:43
(answering my own query - I think I can have 2 provisioners that use two different AWSNodeTemplates, and all is good)

**Comment by mbevc1** [comment] 2023-03-03 18:22
@ellistarn yeah instanceProfile is an odd one not being properly reflected actoss API/console :roll_eyes: . Using IAM roles could work nicely and offer better visibility :+1: . But also at the same time, not super bothered by profiles either :shrug:

**Comment by tzneal** [comment] 2023-03-14 20:40
Consider defaulting to Bottlerocket if not specified for v1beta1?

**Comment by sftim** [comment] 2023-03-14 21:16
If it's feasible, leave the defaulting to be separate from the API - either default at admission time with a mutating admission controller, or have a config option for the controller, something like that.

I'm asking because I'd the API to be especially unopinionated about cloud providers, whilst still giving cluster operators the option.
A _Helm chart_ or whatever can absolutely have an opinion on Bottlerocket; I hope that the API itself does not.

**Comment by jonathan-innis** [comment] 2023-03-14 22:21
> I hope that the API itself does not

I think the defaulting mechanism would live inside the AWS-specific cloudprovider defaulting logic so that it wouldn't be a default across cloudproviders. 

> leave the defaulting to be separate from the API

What do you mean by this, you mean don't contain it in the CRD definition?

**Comment by jonathan-innis** [comment] 2023-03-14 22:23
Consider pulling out [tag-based AMI requirements](https://karpenter.sh/preview/concepts/node-templates/#ami-selection). The assumption is that there are _very_ few users that are doing this, if any at all and those who want to achieve something similar should be able to do so by creating different provisioners.

**Comment by sftim** [comment] 2023-03-15 00:04
> What do you mean by this, you mean don't contain it in the CRD definition?

Yep, exactly. APIs are not the best home for opinions.

**Comment by jonathan-innis** [comment] 2023-03-31 19:28
> APIs are not the best home for opinions

I think in this case, you would probably want defaulting to expose it so that it's more clear what you are using. IMO, it seems more ambiguous if the default isn't propagated through to the api-server by the time the CRD is applied. i.e. having an empty string for AMIFamily and, in code, defaulting to BR

**Comment by engedaam** [comment] 2023-04-04 01:08
Deprecate the following labels in favor of:
- karpenter.k8s.aws/instance-gpu-name ->  karpenter.k8s.aws/instance-accelerator-name
- karpenter.k8s.aws/instance-gpu-memory ->  karpenter.k8s.aws/instance-accelerator-memory
- karpenter.k8s.aws/instance-gpu-manufacturer ->  karpenter.k8s.aws/instance-accelerator-manufacturer
- karpenter.k8s.aws/instance-gpu-count ->  karpenter.k8s.aws/instance-accelerator-count

**Comment by ellistarn** [comment] 2023-05-12 17:14
Consider renaming `karpenter.sh/capacity-type` to `karpenter.sh/purchase-type` or `karpenter.sh/purchase-option`. Right now `capacity-type` implies compute platform like ec2, lambda, or fargate.

**Comment by sftim** [comment] 2023-05-14 16:19
> Consider renaming `karpenter.sh/capacity-type` to `karpenter.sh/purchase-type` or `karpenter.sh/purchase-option`. Right now `capacity-type` implies compute platform like ec2, lambda, or fargate.

“purchase” isn't always right either. For example, you might be choosing between capitalalised, on-prem equipment vs. bursted capacity in the cloud.

**Comment by jonathan-innis** [comment] 2023-05-17 07:15
Change `karpenter.sh/do-not-evict` to `karpenter.sh/do-not-disrupt`. This aligns the concept of "disruption" across Karpenter and is more accurate, since the action that we are actually preventing with this annotation is voluntary disruption.

**Comment by ellistarn** [comment] 2023-06-04 01:36
Should we deprecate `do-not-consolidate` as part of #1302?

**Comment by jonathan-innis** [comment] 2023-08-08 22:22
Consider removing the `karpenter-global-settings` ConfigMap in favor of static deployment configuration in environment variables and CLI arguments.

**Comment by ellistarn** [comment] 2023-08-09 03:22
> Change karpenter.sh/do-not-evict to karpenter.sh/do-not-disrupt. This aligns the concept of "disruption" across Karpenter and is more accurate, since the action that we are actually preventing with this annotation is voluntary disruption.

Worth considering this in the context of Cluster Autoscaler annotations

**Comment by sftim** [comment] 2023-08-09 07:37
_Scheduling_, _preemption_ and _eviction_ are things that happen to Pods; _disruption_ happens to workloads.

The thing you disrupt (or not) is a _set_ of Pods. So, I'd call the label `exclude-from-disruption` not `do-not-disrupt`.

**Comment by jonathan-innis** [comment] 2023-10-31 19:32
v0.32.1 is the latest beta version! We've officially launched beta so I'm going to close this issue and make a v1 laundry list now!

**Closed by jonathan-innis** 2023-10-31 19:32 UTC
Labels: feature, roadmap, v1

**Comment by jonathan-innis** [comment] 2023-10-31 19:33
If you have further breaking changes that you want to see be made in Karpenter, these can be added to the new #4933 issue
