### ISSUE TITLE
Drift consolidation removing nodes it should not

### ISSUE THREAD

**Issue by andrewhibbert** [aws/karpenter#3206] opened 2023-01-12 12:28 UTC
### Version

__Karpenter Version:__ v0.22.0

__Kubernetes Version:__ v1.0.0

### Expected Behavior

Only removes out of date nodes

### Actual Behavior

Newly launched node:

```
karpenter-77448c4485-59qnt controller 2023-01-12T10:50:08.223Z	INFO	controller.deprovisioning	launching node with 1 pods requesting {"cpu":"3491m","memory":"10419421696","pods":"11"} from types c5.2xlarge, m5.4xlarge, m6a.2xlarge, m5a.4xlarge, m5.2xlarge and 25 other(s)	{"commit": "038d219-dirty", "provisioner": "default-ondemand1"}
karpenter-77448c4485-59qnt controller 2023-01-12T10:50:10.007Z	INFO	controller.deprovisioning.cloudprovider	launched new instance	{"commit": "038d219-dirty", "provisioner": "default-ondemand1", "launched-instance": "i-01dc235185674b11c", "hostname": "ip-10-138-109-255.eu-west-1.compute.internal", "type": "m5a.xlarge", "zone": "eu-west-1c", "capacity-type": "on-demand"}
```

Deprovisioned via drift:

```
karpenter-77448c4485-59qnt controller 2023-01-12T12:23:15.461Z	INFO	controller.deprovisioning	deprovisioning via drift delete, terminating 1 nodes ip-10-138-109-255.eu-west-1.compute.internal/m5a.xlarge/on-demand	{"commit": "038d219-dirty"}
karpenter-77448c4485-59qnt controller 2023-01-12T12:23:15.620Z	INFO	controller.termination	cordoned node	{"commit": "038d219-dirty", "node": "ip-10-138-109-255.eu-west-1.compute.internal"}
karpenter-77448c4485-59qnt controller 2023-01-12T12:23:27.985Z	INFO	controller.termination	deleted node	{"commit": "038d219-dirty", "node": "ip-10-138-109-255.eu-west-1.compute.internal"}
```

Another example:

```
 $ kubectl describe node ip-10-138-103-32.eu-west-1.compute.internal
Name:               ip-10-138-103-32.eu-west-1.compute.internal
Roles:              <none>
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=m5a.xlarge
                    beta.kubernetes.io/os=linux
                    failure-domain.beta.kubernetes.io/region=eu-west-1
                    failure-domain.beta.kubernetes.io/zone=eu-west-1a
                    k8s.io/cloud-provider-aws=e86087ba30a6f3944c59fd13e20eff23
                    karpenter.k8s.aws/instance-ami-id=ami-0502b0ddb2ee6a2e1
                    karpenter.k8s.aws/instance-category=m
                    karpenter.k8s.aws/instance-cpu=4
                    karpenter.k8s.aws/instance-family=m5a
                    karpenter.k8s.aws/instance-generation=5
                    karpenter.k8s.aws/instance-hypervisor=nitro
                    karpenter.k8s.aws/instance-memory=16384
                    karpenter.k8s.aws/instance-pods=58
                    karpenter.k8s.aws/instance-size=xlarge
                    karpenter.sh/capacity-type=on-demand
                    karpenter.sh/initialized=true
                    karpenter.sh/provisioner-name=default-ondemand2
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=ip-10-138-103-32.els.vpc.local
                    kubernetes.io/os=linux
                    lifecycle=OnDemand
                    node.kubernetes.io/exclude-from-external-load-balancers=karpenter
                    node.kubernetes.io/instance-type=m5a.xlarge
                    provisioner=default-ondemand2
                    topology.ebs.csi.aws.com/zone=eu-west-1a
                    topology.kubernetes.io/region=eu-west-1
                    topology.kubernetes.io/zone=eu-west-1a
                    vpc.amazonaws.com/eniConfig=eu-west-1a
Annotations:        csi.volume.kubernetes.io/nodeid: {"ebs.csi.aws.com":"i-042541b429339668f"}
                    karpenter.sh/voluntary-disruption: drifted
                    node.alpha.kubernetes.io/ttl: 15
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Thu, 12 Jan 2023 11:01:34 +0000
```

AWSNodeTemplate:

```
$ kubectl get awsnodetemplate default-ondemand2 -o yaml
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"karpenter.k8s.aws/v1alpha1","kind":"AWSNodeTemplate","metadata":{"annotations":{},"name":"default-ondemand2"},"spec":{"amiFamily":"AL2","amiSelector":{"aws-ids":"ami-0502b0ddb2ee6a2e1"},"blockDeviceMappings":[{"deviceName":"/dev/xvda","ebs":{"deleteOnTermination":true,"encrypted":true,"iops":null,"throughput":null,"volumeSize":"80G","volumeType":"gp3"}}],"instanceProfile":null,"metadataOptions":{},"securityGroupSelector":{"Name":"nonprod-shared1.worker-node-sg","karpenter.sh/discovery/nonprod-shared1":"nonprod-shared1"},"subnetSelector":{"karpenter.sh/discovery/nonprod-shared1":"nonprod-shared1"},"tags":{"ClusterName":"nonprod-shared1","Contact":"aws-h-entellect-nonprod@ets-cloud.com","CostCode":"21656","Description":"Karpenter provisioned instance","Environment":"nonprod","Name":"aws-h-entellect-nonprod-shared1.nonprod.nonprod-shared1_karpenter_default-ondemand2","Orchestration":"git@github.com:elsevier-health/entellect-terraform-aws-eks-blueprints.git/karpenter-provisioners","Product":"aws-h-entellect-nonprod-shared1","SubProduct":"aws-h-entellect-nonprod-shared1","karpenter.sh/discovery/nonprod-shared1":"nonprod-shared1","provisioner":"default-ondemand2"},"userData":"MIME-Version: 1.0\nContent-Type: multipart/mixed; boundary=\"BOUNDARY\"\n\n--BOUNDARY\nContent-Type: text/x-shellscript; charset=\"us-ascii\"\n\n#!/bin/bash\necho \"Running custom user data script\"\necho \"Configuring docker\"\nif ! command -v nvidia-smi \u0026\u003e /dev/null\nthen\n    echo \"Regular CPU instance changing /etc/docker/daemon.json\"\ncat \u003c\u003c EOT \u003e /etc/docker/daemon.json\n{\n    \"bridge\": \"none\",\n    \"log-driver\": \"journald\",\n    \"live-restore\": true,\n    \"max-concurrent-downloads\": 10,\n    \"default-ulimits\": {\n    \"memlock\": {\n      \"Hard\": -1,\n      \"Name\": \"memlock\",\n      \"Soft\": -1\n    }\n    },\n    \"registry-mirrors\": [\n      \"https://docker-default-virtual.health.artifactory.tio.systems\",\n      \"https://docker-default-virtual.bts.artifactory.tio.systems\",\n      \"https://docker-default-virtual.rt.artifactory.tio.systems\"\n    ]\n}\nEOT\nelse\n    echo \"GPU instance changing /etc/sysconfig/docker\"\n    echo 'OPTIONS=\"--bridge=none --default-ulimit nofile=2048:8192 --log-driver=journald --live-restore=true --max-concurrent-downloads=10  --registry-mirror=https://docker-default-virtual.health.artifactory.tio.systems --registry-mirror=https://docker-default-virtual.bts.artifactory.tio.systems --registry-mirror=https://docker-default-virtual.rt.artifactory.tio.systems\"' \u003e /etc/sysconfig/docker\nfi\necho \"Restarting docker\"\nsystemctl restart docker\necho \"Configuring journald\"\nmkdir /etc/systemd/journald.conf.d\ncat \u003c\u003cEOT \u003e /etc/systemd/journald.conf.d/override.conf\n[Journal]\nForwardToSyslog=no\nRateLimitInterval=30s\nRateLimitBurst=2000\nEOT\necho \"Restarting journald\"\nsystemctl restart systemd-journald\n--BOUNDARY--\n"}}
  creationTimestamp: "2022-09-05T19:29:40Z"
  generation: 16
  name: default-ondemand2
  resourceVersion: "2025626447"
  uid: 89d77b20-4f4c-42ca-8357-aaf111db69c8
spec:
  amiFamily: AL2
  amiSelector:
    aws-ids: ami-0502b0ddb2ee6a2e1
```

Seems to keep looping and drift consolidating new nodes where the AMI is the same as the provisioner. It's done it a couple of hundred times, we had less than 100 nodes and around 15 had blocking PDBs, do-not-evict annotations etc

![Screenshot 2023-01-12 at 12 58 36](https://user-images.githubusercontent.com/77166944/212072958-1107e117-e5a8-4dae-91d2-bfd7c8676edc.png)

### Steps to Reproduce the Problem

Run drift consolidation

### Resource Specs and Logs

See above

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment] 2023-01-12 21:03
This is definitely not the intended behavior. Let me try and replicate this.

**Comment by njtran** [comment] 2023-01-12 21:08
If possible can you give the output of `aws ec2 describe-images --image-ids ami-0502b0ddb2ee6a2e1`? Also, do you have any other provisioners?

**Comment by njtran** [comment] 2023-01-12 21:24
> Seems to keep looping and drift consolidating new nodes where the AMI is the same as the provisioner. It's done it a couple of hundred times, we had less than 100 nodes and around 15 had blocking PDBs, do-not-evict annotations etc

Also this seems like another bad issue. We shouldn't be deprovisioning if the PDBs would block it or the do-not-evict annotation is on a pod on the node. If this is happening, that means that means that multiple lines of code that block on this condition aren't working. I hope that this is just a logging issue, but considering that the node is being annotated as drifted i'll see if i can find anything else.

**Comment by andrewhibbert** [comment] 2023-01-12 21:52
Sorry I meant that those nodes were not rolling. Also it is possible that I've misread the instructions - https://karpenter.sh/v0.21.1/concepts/deprovisioning/#drift, I've assumed that nodes need to be annotated in order to be checked for drift, so maybe that is why

**Comment by njtran** [comment] 2023-01-12 22:19
Ah, that annotation is used by Karpenter controllers to signal to other Karpenter controllers when to deprovision nodes. If you annotate nodes as drifted, Karpenter will see that either the user or another controller wants to deprovision a node and deprovision it. So does this mean that your nodes are fine? 

Can you confirm that this is okay too? https://github.com/aws/karpenter/issues/3206#issuecomment-1381009462

**Comment by njtran** [comment] 2023-01-17 18:59
This seems like it was a misunderstanding of the existing behavior. I'll close this. Feel free to re-open if you feel it's necessary.

**Closed by njtran** 2023-01-17 18:59 UTC
Labels: bug, burning
