### ISSUE TITLE
Karpenter thrashing TTL emptiness on GPU node 

### ISSUE THREAD

**Issue by noyoshi** [aws/karpenter#4067] opened 2023-06-16 16:59 UTC
### Version

__Karpenter Version:__ v0.27.5

__Kubernetes Version:__ 1.24.13-eks-0a21954

### Expected Behavior

Karpenter should clean up node that has no non-daemonset pods on it according to the emptiness TTL

### Actual Behavior

Karpenter does not clean up the node. 

This seems to be because it keeps adding and removing the emptiness TTL from the node: See the below logs from the karpenter pod: 

```
2023-06-16T16:37:24.820Z	DEBUG	controller.node	added TTL to empty node	{"commit": "698f22f-dirty", "node": "ip-192-168-85-29.us-west-2.compute.internal"}
2023-06-16T16:38:00.070Z	DEBUG	controller.node	removed emptiness TTL from node	{"commit": "698f22f-dirty", "node": "ip-192-168-85-29.us-west-2.compute.internal"}
2023-06-16T16:40:26.998Z	DEBUG	controller	deleted launch template	{"commit": "698f22f-dirty", "launch-template": "karpenter.k8s.aws/4174709001051419229"}
2023-06-16T16:43:00.605Z	DEBUG	controller.node	added TTL to empty node	{"commit": "698f22f-dirty", "node": "ip-192-168-85-29.us-west-2.compute.internal"}
2023-06-16T16:47:23.727Z	DEBUG	controller.node	removed emptiness TTL from node	{"commit": "698f22f-dirty", "node": "ip-192-168-85-29.us-west-2.compute.internal"}
2023-06-16T16:50:10.071Z	DEBUG	controller.node	added TTL to empty node	{"commit": "698f22f-dirty", "node": "ip-192-168-67-213.us-west-2.compute.internal"}
2023-06-16T16:52:24.092Z	DEBUG	controller.node	added TTL to empty node	{"commit": "698f22f-dirty", "node": "ip-192-168-85-29.us-west-2.compute.internal"}
2023-06-16T16:53:00.236Z	DEBUG	controller.node	removed emptiness TTL from node	{"commit": "698f22f-dirty", "node": "ip-192-168-85-29.us-west-2.compute.internal"}
```

### Steps to Reproduce the Problem

Create a gpu node? This one is g5.12xlarge in us-west-2. 

### Resource Specs and Logs

```
2023-06-16T16:37:24.820Z	DEBUG	controller.node	added TTL to empty node	{"commit": "698f22f-dirty", "node": "ip-192-168-85-29.us-west-2.compute.internal"}
2023-06-16T16:38:00.070Z	DEBUG	controller.node	removed emptiness TTL from node	{"commit": "698f22f-dirty", "node": "ip-192-168-85-29.us-west-2.compute.internal"}
2023-06-16T16:40:26.998Z	DEBUG	controller	deleted launch template	{"commit": "698f22f-dirty", "launch-template": "karpenter.k8s.aws/4174709001051419229"}
2023-06-16T16:43:00.605Z	DEBUG	controller.node	added TTL to empty node	{"commit": "698f22f-dirty", "node": "ip-192-168-85-29.us-west-2.compute.internal"}
2023-06-16T16:47:23.727Z	DEBUG	controller.node	removed emptiness TTL from node	{"commit": "698f22f-dirty", "node": "ip-192-168-85-29.us-west-2.compute.internal"}
2023-06-16T16:50:10.071Z	DEBUG	controller.node	added TTL to empty node	{"commit": "698f22f-dirty", "node": "ip-192-168-67-213.us-west-2.compute.internal"}
2023-06-16T16:52:24.092Z	DEBUG	controller.node	added TTL to empty node	{"commit": "698f22f-dirty", "node": "ip-192-168-85-29.us-west-2.compute.internal"}
2023-06-16T16:53:00.236Z	DEBUG	controller.node	removed emptiness TTL from node	{"commit": "698f22f-dirty", "node": "ip-192-168-85-29.us-west-2.compute.internal"}
```

```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  annotations:
    meta.helm.sh/release-name: karpenter
    meta.helm.sh/release-namespace: karpenter
  labels:
    app.kubernetes.io/instance: karpenter
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: karpenter
    meta.helm.sh/release-namespace: karpenter
  name: gpu-large-provisioner
spec:
  labels:
    gpu: "true"
  provider:
    amiFamily: AL2
    blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        deleteOnTermination: true
        encrypted: true
        iops: 10000
        kmsKeyID: :)
        throughput: 125
        volumeSize: 460Gi
        volumeType: gp3
    securityGroupSelector:
      karpenter.sh/discovery: :)
    subnetSelector:
      karpenter.sh/discovery: :)
    tags:
      karpenter.sh/discovery: :)
  requirements:
  - key: node.kubernetes.io/instance-type
    operator: In
    values:
    - g4dn.12xlarge
    - g5.12xlarge
    - g5.24xlarge
    - g5.48xlarge
  - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - on-demand
    - spot
  - key: kubernetes.io/os
    operator: In
    values:
    - linux
  ttlSecondsAfterEmpty: 600
  ```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment] 2023-06-19 20:44
Can you share the pod spec and show the describe results of the node to see if it's fully empty? I spun up a GPU node and scaled down the deployment to make it empty and saw the emptiness check succeed.

**Comment by noyoshi** [comment] 2023-06-21 19:54
Yeah, this is only intermittent - cannot repro successfully all the time, but over the course of a week, we will see a few nodes like this. 

I'll try to grab a node description next time, but they are 100% empty (besides daemonset pods).

**Comment by noyoshi** [comment] 2023-06-21 23:06
@njtran there is no pod spec since there are no pods running on it :) (Pod-spec in terms of non daemonset pods). 

Here is a node I found today: 

```
Name:               
Roles:              <none>
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=g5.12xlarge
                    beta.kubernetes.io/os=linux
                    billing-team=predibase-karpenter-predibase-dataplane
                    failure-domain.beta.kubernetes.io/region=us-west-2
                    failure-domain.beta.kubernetes.io/zone=us-west-2a
                    gpu=true
                    k8s.io/cloud-provider-aws=
                    karpenter.k8s.aws/instance-accelerator-count=4
                    karpenter.k8s.aws/instance-accelerator-manufacturer=nvidia
                    karpenter.k8s.aws/instance-accelerator-memory=24576
                    karpenter.k8s.aws/instance-accelerator-name=a10g
                    karpenter.k8s.aws/instance-ami-id=ami-04cd3f007a9e4125a
                    karpenter.k8s.aws/instance-category=g
                    karpenter.k8s.aws/instance-cpu=48
                    karpenter.k8s.aws/instance-encryption-in-transit-supported=true
                    karpenter.k8s.aws/instance-family=g5
                    karpenter.k8s.aws/instance-generation=5
                    karpenter.k8s.aws/instance-gpu-count=4
                    karpenter.k8s.aws/instance-gpu-manufacturer=nvidia
                    karpenter.k8s.aws/instance-gpu-memory=24576
                    karpenter.k8s.aws/instance-gpu-name=a10g
                    karpenter.k8s.aws/instance-hypervisor=nitro
                    karpenter.k8s.aws/instance-local-nvme=3800
                    karpenter.k8s.aws/instance-memory=196608
                    karpenter.k8s.aws/instance-network-bandwidth=40000
                    karpenter.k8s.aws/instance-pods=737
                    karpenter.k8s.aws/instance-size=12xlarge
                    karpenter.sh/capacity-type=on-demand
                    karpenter.sh/initialized=true
                    karpenter.sh/provisioner-name=gpu-large-provisioner
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=
                    kubernetes.io/os=linux
                    node.kubernetes.io/instance-type=g5.12xlarge
                    predibase.com/engine-node=true
                    topology.ebs.csi.aws.com/zone=us-west-2a
                    topology.kubernetes.io/region=us-west-2
                    topology.kubernetes.io/zone=us-west-2a
Annotations:        alpha.kubernetes.io/provided-node-ip: 192.168.85.29
                    csi.volume.kubernetes.io/nodeid: {"ebs.csi.aws.com":""}
                    karpenter.sh/emptiness-timestamp: 2023-06-21T23:00:58Z
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Wed, 14 Jun 2023 11:16:46 -0700
Taints:             engine-node:NoExecute
Unschedulable:      false
Lease:
  HolderIdentity: 
  AcquireTime:     <unset>
  RenewTime:       Wed, 21 Jun 2023 16:04:21 -0700
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  MemoryPressure   False   Wed, 21 Jun 2023 16:01:15 -0700   Wed, 14 Jun 2023 11:17:15 -0700   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Wed, 21 Jun 2023 16:01:15 -0700   Wed, 14 Jun 2023 11:17:15 -0700   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Wed, 21 Jun 2023 16:01:15 -0700   Wed, 14 Jun 2023 11:17:15 -0700   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            True    Wed, 21 Jun 2023 16:01:15 -0700   Wed, 14 Jun 2023 11:17:39 -0700   KubeletReady                 kubelet is posting ready status
Addresses:
  InternalIP:  
  ExternalIP:  
  Hostname:     
  InternalDNS: 
  ExternalDNS:  
Capacity:
  attachable-volumes-aws-ebs:  39
  cpu:                         48
  ephemeral-storage:           482332652Ki
  hugepages-1Gi:               0
  hugepages-2Mi:               0
  memory:                      195783984Ki
  nvidia.com/gpu:              4
  pods:                        737
Allocatable:
  attachable-volumes-aws-ebs:  39
  cpu:                         47810m
  ephemeral-storage:           443444029524
  hugepages-1Gi:               0
  hugepages-2Mi:               0
  memory:                      187118896Ki
  nvidia.com/gpu:              4
  pods:                        737
System Info:
  Machine ID:                
  System UUID:                
  Boot ID:                    
  Kernel Version:             5.4.242-156.349.amzn2.x86_64
  OS Image:                   Amazon Linux 2
  Operating System:           linux
  Architecture:               amd64
  Container Runtime Version:  containerd://1.6.19
  Kubelet Version:            v1.24.13-eks-0a21954
  Kube-Proxy Version:         v1.24.13-eks-0a21954
ProviderID:                   aws:///us-west-2a/i-0b9fd2d3f9e4eaffb
Non-terminated Pods:          (7 in total)
  Namespace                   Name                                               CPU Requests  CPU Limits  Memory Requests  Memory Limits  Age
  ---------                   ----                                               ------------  ----------  ---------------  -------------  ---
  gpu-resources               dcgm-exporter-1686172320-sz2ld                     0 (0%)        0 (0%)      0 (0%)           0 (0%)         7d4h
  gpu-resources               nvidia-device-plugin-daemonset-r54tq               0 (0%)        0 (0%)      0 (0%)           0 (0%)         7d4h
  kube-system                 aws-node-qzbm4                                     25m (0%)      0 (0%)      0 (0%)           0 (0%)         7d4h
  kube-system                 ebs-csi-node-cldmn                                 30m (0%)      300m (0%)   120Mi (0%)       768Mi (0%)     7d4h
  kube-system                 kube-proxy-b7l5s                                   100m (0%)     0 (0%)      0 (0%)           0 (0%)         7d4h
  kube-system                 predibase-dataplane-nvidia-device-plugin-hj4rn     0 (0%)        0 (0%)      0 (0%)           0 (0%)         7d4h
  staging-predibase-logs      staging-predibase-grafana-agent-logs-logs-kfvbj    0 (0%)        0 (0%)      0 (0%)           0 (0%)         7d4h
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource                    Requests    Limits
  --------                    --------    ------
  cpu                         155m (0%)   300m (0%)
  memory                      120Mi (0%)  768Mi (0%)
  ephemeral-storage           0 (0%)      0 (0%)
  hugepages-1Gi               0 (0%)      0 (0%)
  hugepages-2Mi               0 (0%)      0 (0%)
  attachable-volumes-aws-ebs  0           0
  nvidia.com/gpu              0           0
Events:
  Type    Reason            Age                   From       Message
  ----    ------            ----                  ----       -------
  Normal  Unconsolidatable  12m (x687 over 7d4h)  karpenter  provisioner gpu-large-provisioner has consolidation disabled
  ```

**Comment by noyoshi** [comment] 2023-06-21 23:08
I just described the node again, no new pods, but the TTL is gone from the node. 
```
Annotations:        alpha.kubernetes.io/provided-node-ip:
                    csi.volume.kubernetes.io/nodeid: {"ebs.csi.aws.com":"i-0b9fd2d3f9e4eaffb"}
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
```

**Comment by ellistarn** [comment] 2023-06-22 16:44
Is this a daemonset? `dataplane-nvidia-device-plugin-hj4rn`

**Comment by noyoshi** [comment] 2023-06-26 18:59
So, it turns out that wasn't the issue (its a daemonset pod), but what is happening is that the `aws-csi-controller` was scheduling pods onto these nodes. This shouldn't happen, since we have explicit `NoExecute` taints on these GPU nodes so that system level pods won't get placed on them. However, it turns out that the `aws-csi-controller` pods have a universal toleration to all `NoExecute` taints. 

For whatever reason, the pods of this controller are created and deleted quite frequently, and they would sometimes get placed on the GPU nodes in our cluster, causing the karpenter label to fall off (since the node was no longer empty). 

This controller is installed via EKS and not managed by us, so can't really modify it to not have that toleration. Right now I added another taint - a "NoSchedule" one to our GPU nodes to see if that fixes this issue.

Still need to see why the controller pods are being created and deleted so frequently though.

**Comment by jonathan-innis** [comment] 2023-07-20 00:20
Is it safe to say that this is not a Karpenter issue but that this issue is being caused by another controller? @noyoshi from what you mentioned, it sounds like we can close this issue. Please re-open if you believe that this was closed erroneously.

**Closed by jonathan-innis** 2023-07-20 00:20 UTC
Labels: bug
