### ISSUE TITLE
Karpenter provisions multiple nodes when the pending pods claims for PV

### ISSUE THREAD

**Issue by sisuani-eb** [aws/karpenter#1146] opened 2022-01-14 15:11 UTC
## Version

**Karpenter**: v0.5.4

**Kubernetes**: v1.21.0

## Expected Behavior

If the incoming node has enough resource to attach the volumes of the pending pods don't provision with new ones

## Actual Behavior

Karpenter provisions multiple nodes when the incoming node(s) are not ready yet even though the incoming node has enough resource to allocate the pending pods

## Steps to Reproduce the Problem

1.- Deploy several pods with PVC
2.- Wait until karpenter provisions multiple nodes

## Resource Specs and Logs

Karpenter spec:
```
spec:
  kubeletConfiguration: {}
  limits:
    resources:
      cpu: 1k
  provider:
    apiVersion: extensions.karpenter.sh/v1alpha1
    instanceProfile: KarpenterNodeInstanceProfile-karpenter
    kind: AWS
    securityGroupSelector:
      kubernetes.io/cluster/karpenter: '*'
    subnetSelector:
      kubernetes.io/cluster/karpenter: '*'
  requirements:
  - key: node.kubernetes.io/instance-type
    operator: In
    values:
    - m5.large
    - m5.2xlarge
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - spot
  - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
  ttlSecondsAfterEmpty: 30
```
Logs:
```
2022-01-14T14:52:24.685Z	INFO	controller.provisioning	Batched 1 pods in 1.001040567s	{"commit": "7e79a67", "provisioner": "default"}
2022-01-14T14:52:24.835Z	DEBUG	controller.provisioning	Discovered subnets: [subnet-089110b62ac57e595 (us-east-1b) subnet-08850bba1bc74644b (us-east-1a) subnet-0c4911a6767620cca (us-east-1c)]	{"commit": "7e79a67", "provisioner": "default"}
2022-01-14T14:52:24.844Z	INFO	controller.provisioning	Computed packing of 1 node(s) for 1 pod(s) with instance type option(s) [m5.large m5.2xlarge]	{"commit": "7e79a67", "provisioner": "default"}
2022-01-14T14:52:24.979Z	DEBUG	controller.provisioning	Discovered security groups: [sg-083645e4aed2ff182 sg-09444145c38265949]	{"commit": "7e79a67", "provisioner": "default"}
2022-01-14T14:52:24.981Z	DEBUG	controller.provisioning	Discovered kubernetes version 1.21	{"commit": "7e79a67", "provisioner": "default"}
2022-01-14T14:52:25.051Z	DEBUG	controller.provisioning	Discovered ami ami-0e09bf993397d63d5 for query /aws/service/eks/optimized-ami/1.21/amazon-linux-2/recommended/image_id	{"commit": "7e79a67", "provisioner": "default"}
2022-01-14T14:52:25.052Z	DEBUG	controller.provisioning	Discovered caBundle, length 1066	{"commit": "7e79a67", "provisioner": "default"}
2022-01-14T14:52:25.095Z	DEBUG	controller.provisioning	Discovered launch template Karpenter-karpenter-13701584485114519280	{"commit": "7e79a67", "provisioner": "default"}
2022-01-14T14:52:28.095Z	INFO	controller.provisioning	Launched instance: i-04062994986fc53b9, hostname: ip-10-0-3-13.ec2.internal, type: m5.large, zone: us-east-1c, capacityType: spot	{"commit": "7e79a67", "provisioner": "default"}
2022-01-14T14:52:28.148Z	INFO	controller.provisioning	Bound 1 pod(s) to node ip-10-0-3-13.ec2.internal	{"commit": "7e79a67", "provisioner": "default"}
2022-01-14T14:52:28.148Z	INFO	controller.provisioning	Waiting for unschedulable pods	{"commit": "7e79a67", "provisioner": "default"}
2022-01-14T14:52:28.160Z	INFO	controller.volume	Bound persistent volume claim to node ip-10-0-3-13.ec2.internal	{"commit": "7e79a67", "resource": "app/ebs-claim-4"}
2022-01-14T14:52:29.148Z	INFO	controller.provisioning	Batched 1 pods in 1.000276267s	{"commit": "7e79a67", "provisioner": "default"}
2022-01-14T14:52:29.166Z	INFO	controller.provisioning	Computed packing of 1 node(s) for 1 pod(s) with instance type option(s) [m5.large m5.2xlarge]	{"commit": "7e79a67", "provisioner": "default"}
2022-01-14T14:52:29.167Z	DEBUG	controller.provisioning	Discovered caBundle, length 1066	{"commit": "7e79a67", "provisioner": "default"}
2022-01-14T14:52:33.382Z	INFO	controller.provisioning	Launched instance: i-03a4aada3de169ef8, hostname: ip-10-0-3-155.ec2.internal, type: m5.large, zone: us-east-1c, capacityType: spot	{"commit": "7e79a67", "provisioner": "default"}
2022-01-14T14:52:33.428Z	INFO	controller.provisioning	Bound 1 pod(s) to node ip-10-0-3-155.ec2.internal	{"commit": "7e79a67", "provisioner": "default"}
2022-01-14T14:52:33.428Z	INFO	controller.provisioning	Waiting for unschedulable pods	{"commit": "7e79a67", "provisioner": "default"}
2022-01-14T14:52:33.438Z	INFO	controller.volume	Bound persistent volume claim to node ip-10-0-3-155.ec2.internal	{"commit": "7e79a67", "resource": "app/ebs-claim-5"}
2022-01-14T14:52:34.429Z	INFO	controller.provisioning	Batched 2 pods in 1.001132157s	{"commit": "7e79a67", "provisioner": "default"}
2022-01-14T14:52:34.439Z	INFO	controller.provisioning	Computed packing of 1 node(s) for 2 pod(s) with instance type option(s) [m5.large m5.2xlarge]	{"commit": "7e79a67", "provisioner": "default"}
2022-01-14T14:52:34.440Z	DEBUG	controller.provisioning	Discovered caBundle, length 1066	{"commit": "7e79a67", "provisioner": "default"}
```

**Comment by ellistarn** [comment] 2022-01-14 17:44
Is this a duplicate of https://github.com/aws/karpenter/issues/1044

**Closed** 2022-01-14 23:39 UTC
Labels: bug
