### ISSUE TITLE
AMIs listed on node template status are incorrect

### ISSUE THREAD

**Issue by tzneal** [aws/karpenter#4243] opened 2023-07-10 12:20 UTC
### Description

**Observed Behavior**:
The correct AMIs should be listed

**Expected Behavior**:

The old, incorrect AMIs were listed.

**Reproduction Steps** (Please include YAML):

1. Look at the AWS node template
2. Upgrade your cluster version
3. Look at the AWS node template again

In my case, the AMIS on the template (even 12 hours later) are showing for the old K8s versions and not my current cluster version.

**Versions**:
- Chart Version: 
- Kubernetes Version (`kubectl version`): 

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by engedaam** [comment] 2023-07-20 19:06
@tzneal Can you share your AWSNodetemplate?

**Comment by tzneal** [comment] 2023-07-20 19:07
I think this is it, and I don't have an AMI selector.

```
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"karpenter.k8s.aws/v1alpha1","kind":"AWSNodeTemplate","metadata":{"annotations":{},"creationTimestamp":"2022-09-08T14:00:24Z","generation":26,"name":"default","resourceVersion":"214609316","uid":"60162c71-ed80-4e39-b613-17ad9752e8a4"},"spec":{"amiFamily":"AL2","securityGroupSelector":{"karpenter.sh/discovery":"tnealt-karpenter-demo"},"subnetSelector":{"karpenter.sh/discovery":"tnealt-karpenter-demo"}}}
  creationTimestamp: "2022-09-08T14:00:24Z"
  generation: 55
  name: default
  resourceVersion: "283463556"
  uid: 60162c71-ed80-4e39-b613-17ad9752e8a4
spec:
  amiFamily: AL2
  securityGroupSelector:
    karpenter.sh/discovery: tnealt-karpenter-demo
  subnetSelector:
    karpenter.sh/discovery: tnealt-karpenter-demo
status:
  amis:
  - id: ami-03c71b04d72abcaba
    name: amazon-eks-node-1.26-v20230703
    requirements:
    - key: kubernetes.io/arch
      operator: In
      values:
      - amd64
    - key: karpenter.k8s.aws/instance-gpu-count
      operator: DoesNotExist
    - key: karpenter.k8s.aws/instance-accelerator-count
      operator: DoesNotExist
  - id: ami-04b16fffebdb71b44
    name: amazon-eks-gpu-node-1.26-v20230703
    requirements:
    - key: kubernetes.io/arch
      operator: In
      values:
      - amd64
    - key: karpenter.k8s.aws/instance-accelerator-count
      operator: Exists
  - id: ami-04b16fffebdb71b44
    name: amazon-eks-gpu-node-1.26-v20230703
    requirements:
    - key: kubernetes.io/arch
      operator: In
      values:
      - amd64
    - key: karpenter.k8s.aws/instance-gpu-count
      operator: Exists
  - id: ami-0e1b6fa1064526fe3
    name: amazon-eks-arm64-node-1.26-v20230703
    requirements:
    - key: karpenter.k8s.aws/instance-accelerator-count
      operator: DoesNotExist
    - key: kubernetes.io/arch
      operator: In
      values:
      - arm64
    - key: karpenter.k8s.aws/instance-gpu-count
      operator: DoesNotExist
  securityGroups:
  - id: sg-05f88204faa8cf2d4
    name: eksctl-tnealt-karpenter-demo-cluster-ClusterSharedNodeSecurityGroup-1GYN6XLQSMHLC
  - id: sg-05c364fe5ccfc49b4
    name: eksctl-tnealt-karpenter-demo-cluster-ControlPlaneSecurityGroup-ZNWBNVJKS2ZJ
  subnets:
  - id: subnet-0ef4e49e53c6efeb8
    zone: us-west-2d
  - id: subnet-0c11eccbdb504fc8c
    zone: us-west-2a
  - id: subnet-08b2f89b5c564eef8
    zone: us-west-2d
  - id: subnet-0d1867bc726b0761e
    zone: us-west-2a
  - id: subnet-07c63b239e3635300
    zone: us-west-2c
  - id: subnet-015e9db74b0cc6b47
    zone: us-west-2c

```

**Comment by engedaam** [comment] 2023-07-20 19:13
Do you by any chance happen to have the logs? I wasn't able to replicate the issue on a new cluster

**Comment by tzneal** [comment] 2023-07-20 19:14
Nope, sorry.  Did you upgrade a cluster and it worked?

**Comment by engedaam** [comment] 2023-07-20 19:18
Yeah I upgraded the cluster from 1.24 to 1.25 It took around 5 minutes to change, but it updated

**Comment by engedaam** [comment] 2023-07-20 20:48
```
karpenter-77b97df45-bn4g5 controller 2023-07-20T19:42:18.794Z	ERROR	controller	Reconciler error	{"commit": "47446e1-dirty", "controller": "awsnodetemplate", "controllerGroup": "karpenter.k8s.aws", "controllerKind": "AWSNodeTemplate", "AWSNodeTemplate": {"name":"default"}, "namespace": "", "name": "default", "reconcileID": "26744bea-bafe-44ee-9062-9e805b6e1df5", "error": "Internal error occurred: failed calling webhook \"defaulting.webhook.karpenter.k8s.aws\": failed to call webhook: Post \"https://karpenter.karpenter.svc:8443/?timeout=10s\": dial tcp 192.168.72.57:8443: connect: connection refused"}
```
Talked offline. I wasn't able to reproduce and seems to be a webhook error. Closing for the time being.

**Closed by engedaam** 2023-07-20 20:48 UTC
Labels: bug, needs-investigation
