### ISSUE TITLE
support ordered instance type preference

### ISSUE THREAD

**Issue by grosser** [aws/karpenter#2916] opened 2022-11-22 19:41 UTC
### Tell us about your request

have a provisioner that uses instances as they are ordered in the types list

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

we want to run our clusters with m6i.16xl nodes, but we want to allow fallback to 12xl,8xl etc
when pending pods are found karpenter will spin up the smallest possible node (8xl) and do that over-and-over until we have lots of 8xl nodes
(at this point we need consolidation to get 16xl nodes, but that causes pods to get deleted which is not ideal)
so a "ordered" provisioner would be nice that picks the first available instance type from the list

### Are you currently working around this issue?

use multiple provisioners with descending weights (1 per type)
which is ugly to manage and I assume inefficient inside of karpenter since it needs to consider so many provisioners

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by FernandoMiguel** [comment] 2022-11-22 19:44
We have several provisioners and consolidation works fine.
One is a limited family provisioner with a second one being a bigger pool of hw.

**Comment by grosser** [comment] 2022-11-22 19:45
so you enable consolidation on each of the provisioners or just the "big pool" ?

**Comment by FernandoMiguel** [comment] 2022-11-22 19:58
On both provisioners

**Comment by grosser** [comment] 2022-11-22 20:02
awesome, then I'll just try that and see if it works 🎉

**Comment by grosser** [comment] 2022-11-23 00:45
let me reopen this ...
so if this works we are still looking at 12 different provisioners 🤦 
(we use 6 instance types -> 6 for capacity reservation and 6 for regular instances) that seems not fun ...

**Comment by ellistarn** [comment] 2022-11-23 01:08
Can you explain the logic behind your instance type preference? You may find that the cluster autoscaler is a better fit for this use case.

**Comment by grosser** [comment] 2022-11-23 01:15
yeah, we are trying to move from CA to karpenter :D
the preference is instance family (m6 over m5, since we see performance gains)
and size 16 over 8 (since we see reduced overhead from daemonsets and packing of pods)

**Comment by ellistarn** [comment] 2022-11-23 03:55
I'd typically let Karpenter binpack for you, rather than preferring 16 over 8. Regarding generation, I'd use provisioner weights to preference generation 6 over generation 5. Check out https://karpenter.sh/v0.19.2/tasks/scheduling/#weighting-provisioners and https://karpenter.sh/v0.19.2/tasks/scheduling/#supported-labels

**Comment by grosser** [comment] 2022-11-23 04:12
yeah I looked at weights, downside would be that I have to duplicate provisioners.
I know karpenter can binpack via consolidation but for simplicity and to lower disruption I'd like to "always get 16xls", it will also be a smoother transition from cluster-autoscaler to have 1 less thing that changes.

**Comment by FernandoMiguel** [comment] 2022-11-23 07:09
Given that it's all yaml, you can template it, so you may end up with fewer actual full blown provisioner blocks.
Just depends on what you are using to deploy them.

**Comment by grosser** [comment] 2022-11-23 16:59
Yeah I know that can work, the issue comes from "not wanting so many provisioners" in general and "setting max resources" (and maybe in the future min resources and disable which are 2 other issues we are hoping to get solved)

**Comment by FernandoMiguel** [comment] 2022-11-23 17:05
I believe the team is working to make some global values, which could include max resources for all provisioners

**Comment by ellistarn** [comment] 2022-11-25 19:23
I'd much prefer global limits and trying to architect Karpenter to be more similar to CAS. I don't see a viable path to what you're suggesting without completely breaking how Karpenter thinks about instance type flexibility.

**Comment by grosser** [comment] 2022-11-25 19:27
I was thinking that when deciding what type to pick it would have a flag to say "use the order from the requirements".

**Comment by mercuriete** [comment] 2022-12-14 10:35
I have a use case that probably will be fixed with this feature:

I have 1 container/deployment that fits on t3.small (less than 1 core and low ram usage)

When horizontal pod autoscaler kicks in...
Karpenter calculates the best fit for the new containers and fails because...
Karpenter doesn't know that lots of small instances are cheaper than a few big instances.

right now I am having c5a.large and t3.medium instances in my cluster when everything could fit in t3.small

If I restrict the instance types on the provisioner it totally works but the documentation states that I need to provide more than 30 instance types to be a good list and I feel that leaving the default list is less risky than trying to be smart.

BTW I am using SPOT instances.

summarizing,
everything could fit in t3.small but karpenter didn't try to do the cheapest fit.

**Comment by FernandoMiguel** [comment] 2022-12-14 12:35
@mercuriete i would create two provisioners.
one with just t3.small with lower weight and another with larger number of families.
that way, Karpenter will try first the lower weight provisioner and if no instance of that type is available, tries the next one

**Comment by mercuriete** [comment] 2022-12-14 13:37
@FernandoMiguel 
Thanks.
It is really a good idea and it fits perfectly my use case.
I will implement it.

**Closed** 2022-12-19 18:31 UTC
Labels: feature

**Comment by grosser** [comment] 2022-12-19 18:42
I still want this feature, because otherwise we have to manage 6+ providers for every nodegroup 😞 
(we want to have m6i.16xl,12xl,8xl,... but not karpenter boot any of the smaller instances unless aws is out off capacity)

**Comment by ellistarn** [comment] 2022-12-19 19:33
You should be able to share the same AWSNodeTemplate across multiple provisioners. 

We have a preference mechanism implemented today. It leverages a single provisioner for AND rules, and multiple provisioners for (weighted) OR rules. Changing this to a single provisioner has significant architectural complexities (i.e., impact to how weights work today), and I don't see the value in trying to collapse multiple yamls into a single yaml to achieve the same use case. Open to hearing more about why I'm wrong on this, as well as a concrete idea of what an alternative would look like.

**Comment by grosser** [comment] 2022-12-19 19:53
Yeah don't think you are wrong there, I imagine it's not easy.
I'm mostly hoping there is a way that I don't have to deal with so many provisioners.
The only alternative I can think of is making the instance type list special (maybe generic so any field could be "sort by this".

**Comment by grosser** [comment] 2022-12-19 20:14
that would not work, not sure how that question is related though

I'm suggesting a single provider with:
```
  requirements:
  - key: karpenter.sh/capacity-type
    operator: In
    values: ["on-demand"]
  - key: "node.kubernetes.io/instance-type"
    operator: In
    values: ["m6i.16xlarge", "m6i.12xlarge", "m6i.8xlarge"]
  instanceTypeSortOrder: "node.kubernetes.io/instance-type"
```
or something like that

**Comment by ellistarn** [comment] 2022-12-19 20:49
The problem is that we'd now need to revert to passing a single instance type to EC2, or use a fundamentally different pricing strategy. Neither of these fit well with karpenter's architectural assumptions, which are oriented around flexibility and instance type price analysis. Consider how this would work for Spot -- we would request instance types one at a time, and completely negate the pool depth analysis provided by the PriceCapacityOptimized algorithm of fleet. 

If you need this specific use case, the Cluster Autoscaler's architecture is a better fit for the use case. However, I'd really question the assumptions of what you're trying to achieve via prioritization. Why do need this prioritization at all? Why is karpenter's built in binpacking failing to achieve the capacity results you're looking for?

**Comment by grosser** [comment] 2022-12-19 21:21
yeah part of this is trying to stay close to CA so we can move to karpenter with minimal changes and then experiment once we are there

- we are trying to have even instance types since we know they are cost-effective (especially m6i vs m5)
- our daemonsts are tuned for the 16xl size (making them dynamic would be an option though, but more work)
- we don't want pods to be shuffled around (so ideally boot 16xl and then it just stays on there)
- for spot we'd most likely not want the prioritization since the depth is great good feature

**Comment by ellistarn** [comment] 2022-12-19 21:42
Given that it's just a point in time problem for experimentation of a migration from another tool, id recommend just using weighted provisioners.

**Comment by grosser** [comment] 2022-12-19 22:52
yeah that's my plan ... we'll see how much trouble that is
was mostly hoping it would be an easy fix to add
