### ISSUE TITLE
Maintenance Window

### ISSUE THREAD

**Issue by philslab-ninja** [aws/karpenter#3939] opened 2023-05-25 11:01 UTC
### Tell us about your request

It would be great if there was a `Maintenance Window` configurable for consolidation and node expiration

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

I really like to use the consolidation feature and ttlSecondsUntilExpired on our environments to save costs and optimizie resource utilization as well as making sure we always run the latest version of Bottlerocket without having to deploy [Brupop](https://github.com/bottlerocket-os/bottlerocket-update-operator).

However, unfortunately one of our applications is not tolerating this very well which leads to short service disruptions during node replacements.

If I could tell karpenter to only perform those tasks during some pre-defined window (for example daily 02:00 - 04:00) this would be very useful.

### Are you currently working around this issue?

I am not using the features I'd like to use

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment] 2023-05-25 12:24
The current workaround is to use something like a cronjob to enable/disable consolidation periodically.

Closing as a duplicate of the existing feature request https://github.com/aws/karpenter/issues/1302

**Closed by tzneal** 2023-05-25 12:24 UTC
Labels: feature
