### ISSUE TITLE
Cordon after amount of time

### ISSUE THREAD

**Issue by cpchiu** [aws/karpenter#4850] opened 2023-10-18 12:04 UTC
### Description

**What problem are you trying to solve?**
We have a ttlSecondsUntilExpired value set on our provisioners so we do not keep really expensive nodes alive for longer than that amount of time. Most of our tasks are short running tasks that fall within the node ttl. Sometimes we do run longer tasks that exceed the ttl. It would be great if we could specify a ttl for when the provisioner will schedule a pod onto the node. For instance, after 3 hours, no nodes will get scheduled onto a Node but all of the tasks currently running on the Node would be allowed to keep running. I have looked through the documentation and haven't been able to find a way to do this. Am I missing something?

Thanks!

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by cpchiu** [comment] 2023-10-18 12:08
Looks to be a duplicate of https://github.com/aws/karpenter/issues/4613

**Comment by njtran** [comment] 2023-10-18 17:51
closing as duplicate of https://github.com/aws/karpenter/issues/2988

**Closed by njtran** 2023-10-18 17:51 UTC
Labels: feature
