### ISSUE TITLE
Auto-discover EKS cluster endpoint by cluster name via IRSA

### ISSUE THREAD

**Issue by woehrl01** [aws/karpenter#3192] opened 2023-01-10 20:25 UTC
### Tell us about your request

Karpenter already has a IRSA to manage the EC2 instances. By increasing the scope of that role, the cluster endpoint could be automatically discovered, removing the need to provide the value during creation of the helm chart.

Endpoint to call: https://docs.aws.amazon.com/eks/latest/APIReference/API_DescribeCluster.html

Additional IAM Permission required: `"eks:DescribeCluster"` which can (and should) be scoped to the single cluster.

A suggestion would be to add another value for the helm chart `autodiscoverClusterEndpoint` which can be used for that feature.

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

We are not creating the Helm chart with terraform, but with a purely GitOps based workflow after the cluster has been created. During that phase, we usually only have the name of the cluster, but not the actual endpoint address, requiring an additional lookup and mapping of that value.

### Are you currently working around this issue?

Creating a custom mapping from cluster name to endpoint.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment] 2023-01-10 21:47
The AWS implementation of Karpenter intentionally does not rely on EKS APIs and instead relies on assumptions of the AWS Cloud Provider for Kubernetes.

**Comment by woehrl01** [comment] 2023-01-10 22:01
It's still using the aws sdk for go, isn't it? At least it's used for controlling the ec2 instances. Why can't that sdk be used for also resolving the aws specific cluster endpoint configuration?

**Comment by ellistarn** [comment] 2023-01-10 23:30
It's straightforward to make the implementation do so, the problem is that it would break for any user with a cluster on EC2 who is not using EKS. You could do partial behavior, where we attempt to discover the cluster if it's EKS and fail otherwise, but this seems like it may be more confusing for users than other users are helped by the discovery.

**Comment by woehrl01** [comment] 2023-01-11 05:30
Thanks I see, what are your thoughts on adding a eks specific subsection (under aws) into the helm chart for that flag?

**Comment by ellistarn** [comment] 2023-01-11 05:48
Can you elaborate on the use case a little bit? How much simpler is name than name/endpoint/cabundle? Does it change your installation significantly? One guess is that name is well known at config time, where endpoint/cabundle are dynamic. Does this enable you to use less tools during installation?

We've heard this ask enough times that I wonder if it's worth rethinking our stance (above), but I want to understand the use case better. 

Consider me open minded to doing this either in helm or as a runtime arg (incl. dependency on eks:DescribeCluster)

**Comment by woehrl01** [comment] 2023-01-11 19:18
Sure @ellistarn :

In this case, (for now) won't make the manual mapping a significant less effort, but it could make one in the future. The main concern is that the first usage experience. Karpenter can auto-discover "everything", except the endpoint address (for EKS), which feels strange.

Regarding less tools: For my current usage, we won't require calling the aws cli to read the cluster endpoint address during setup to populate a local mapping file, which we currently only require for this use case.

**Comment by ellistarn** [comment] 2023-01-11 20:43
👍  Chatting with the team about this today.

**Comment by woehrl01** [comment] 2023-02-04 16:22
@ellistarn is there an outcome from your discussion? Is this something you would like to support in the future? Would you be interested in a PR for this?

**Comment by ellistarn** [comment] 2023-02-05 05:31
Supportive of a PR for this. Perhaps @jonathan-innis can chime in, too?
1. cluster-endpoint is now optional
1. If cluster-endpoint is not set, discover at startup using cluster name

**Comment by jonathan-innis** [comment] 2023-02-06 17:43
Agree with @ellistarn. This seems reasonable to me. The default install could have the DescribeCluster on the single resource and auto-discover the api-endpoint.

**Comment by jonathan-innis** [comment] 2023-02-06 17:44
@woehrl01 If you're interested in opening a PR around this, I'm happy to assign this issue to you 👍

**Comment by woehrl01** [comment] 2023-02-06 17:58
@jonathan-innis Sure, would definitely give this a try. I already tried to make myself familiar in the repo. It looks like that https://github.com/aws/karpenter/blob/main/pkg/apis/settings/settings.go#L72-L93 would be the place to add the lookup, do you agree?

**Comment by jonathan-innis** [comment] 2023-02-06 19:08
@woehrl01 Yes, I think you are right. We would want to encapsulate this lookup in the settings package. I think in order to make our dependency graph look right, we may want to create a `session` package so that we generate sessions that all look the same as [this session](https://github.com/aws/karpenter/blob/main/pkg/context/context.go#L55). We can instantiate the eks api using that session and call-out to it to describe the cluster API endpoint.

**Comment by woehrl01** [comment] 2023-02-06 19:29
@jonathan-innis I looked a bit more through the repo and found the "launchtemplate" package. It looks like that this is the right place in my opinion to add the logic:

https://github.com/aws/karpenter/blob/main/pkg/cloudprovider/launchtemplate.go#L136-L160

Here, we already have access to the ec2api (so we simply add the additional API), and it won't require the whole controller to restart if there are any changes in the infrastructure. Thoughts?

**Comment by ellistarn** [comment] 2023-02-06 21:19
+1 to launchtemplate and not in settings.

**Closed** 2023-02-14 18:04 UTC
Labels: feature, good-first-issue
