### ISSUE TITLE
why so much log webhook.ValidationWebhook	Reconcile error

### ISSUE THREAD

**Issue by txjjjjj** [aws/karpenter#4813] opened 2023-10-12 09:51 UTC
### Description

env:
eks 1.25
karpenter: v0.30.0

```diff
kubectl logs -f -n karpenter -l app.kubernetes.io/name=karpenter -c controller

...
2023-10-12T04:36:36.183Z	ERROR	webhook.ValidationWebhook	Reconcile error	{"commit": "637a642", "knative.dev/traceid": "afaae6a0-d85d-4f80-b621-0e39e51b59b0", "knative.dev/key": "karpenter/karpenter-cert", "duration": "21.965µs", "error": "secret \"karpenter-cert\" is missing \"ca-cert.pem\" key"}
2023-10-12T04:36:36.185Z	ERROR	webhook.ConfigMapWebhook	Reconcile error	{"commit": "637a642", "knative.dev/traceid": "76ffdf60-d339-4aba-8b64-3632482ff1c7", "knative.dev/key": "karpenter/karpenter-cert", "duration": "13.013µs", "error": "secret \"karpenter-cert\" is missing \"ca-cert.pem\" key"}
2023-10-12T04:36:36.185Z	ERROR	webhook.DefaultingWebhook	Reconcile error	{"commit": "637a642", "knative.dev/traceid": "6239cd9a-3ba5-4142-89f2-a6f6993377ad", "knative.dev/key": "karpenter/karpenter-cert", "duration": "12.956µs", "error": "secret \"karpenter-cert\" is missing \"ca-cert.pem\" key"}
2023-10-12T04:36:36.185Z	ERROR	webhook.ValidationWebhook	Reconcile error	{"commit": "637a642", "knative.dev/traceid": "ebc9bf6a-6df7-4e47-8998-6d40f1b0b5b3", "knative.dev/key": "karpenter/karpenter-cert", "duration": "11.405µs", "error": "secret \"karpenter-cert\" is missing \"ca-cert.pem\" key"}
2023-10-12T04:36:36.241Z	ERROR	webhook.WebhookCertificates	Reconcile error	{"commit": "637a642", "knative.dev/traceid": "0d25157e-9a24-4749-bb95-85acaa44ac0f", "knative.dev/key": "karpenter/karpenter-cert", "duration": "73.658652ms", "error": "Operation cannot be fulfilled on secrets \"karpenter-cert\": the object has been modified; please apply your changes to the latest version and try again"}
```

**Comment by pete911** [comment] 2023-10-12 11:44
@txjjjjj the error is coming from kntative pkg, not from karpenter directly - https://github.com/knative/pkg/blob/main/webhook/configmaps/configmaps.go#L85

**Comment by jonathan-innis** [comment] 2023-10-12 21:38
I think this is a duplicate of #2902. I'd add context in there if the conversation in there doesn't have enough info and you still have questions. The TLDR is that we are planning to drop webhook support in favor of upstream support for validation driven through Common Expression Language soon (see https://github.com/aws/karpenter-core/issues/103)

**Closed by jonathan-innis** 2023-10-12 21:38 UTC
Labels: bug
