### ISSUE TITLE
Support for non-aws Environments

### ISSUE THREAD

**Issue by apton-sooraj** [aws/karpenter#1601] opened 2022-03-31 11:26 UTC
Hello, How can we use the karpenter on Other cloud providers ?
Any Documentations available? Is it possible to use karpenter on Other clouds?

**Comment by ellistarn** [comment] 2022-03-31 15:34
You more or less just need to implement this interface https://github.com/aws/karpenter/blob/main/pkg/cloudprovider/types.go. The harder part is long term maintenance. We want to find maintainers who are able to support the project for the long term. Once we have a plan for that, I'm happy to help with the integration.

**Comment by rtripat** [comment] 2022-04-19 23:21
Closing as duplicate of https://github.com/aws/karpenter/issues/1243

**Closed by rtripat** 2022-04-19 23:21 UTC
