### ISSUE TITLE
[AWS] Worker Nodes not Joining the Cluster when using Custom Launch Templates

### ISSUE THREAD

**Issue by vijayansarathy** [aws/karpenter#432] opened 2021-05-27 21:40 UTC
I tried provisioning worker nodes by specifying a custom launch template in the Provisioner.
What I noticed is that the IAM role, namely, **KarpenterNodeRole-${CLUSTER_NAME}**, does not get assigned to the node at all and therefore the node never joins the cluster. I am using the latest version 0.2.5. I tried with an earlier version as well and saw the same behavior. Here are the Karpenter images I used:
  
- "public.ecr.aws/karpenter/controller:v0.2.4@sha256:488133ea46bd4be3e15bfb984af5b4e217b6780b83d26a6d41e7c4769aaa720f"
- "public.ecr.aws/karpenter/controller:v0.2.5@sha256:44cf4a340637555ba46289c315d700283443533bb2b084488248cf955faf866a"

Here's the YAML for Provisioner:

```
---
apiVersion: provisioning.karpenter.sh/v1alpha1
kind: Provisioner
metadata:
  namespace: karpenter
  name: t3-custom-provisioner
spec:
  cluster:
    name: "k8s-production-cluster"
    caBundle: "XXXXXX="
    endpoint: "https://XXXXXX.gr7.us-east-1.eks.amazonaws.com"
  ttlSeconds: 30
  instanceTypes:
    - t3.large
    - t3.xlarge
    - t3.2xlarge
  labels:
    node.k8s.aws/launch-template-id: "lt-039ab354e881f2cf1"
```

**Comment by ellistarn** [comment] 2021-06-02 15:21
Thanks Viji. After our discussion on slack, it sounds like you're unblocked. Can you remind us what the root cause was for this for future readers?

**Comment by ellistarn** [comment] 2021-06-03 23:26
My guess, @vijayansarathy, is that your launch template is missing the required security group to communicate with the API servers. The expected symptom here is that the node wouldn't connect to the cluster.

**Comment by vijayansarathy** [comment] 2021-06-04 19:53
This is still not working for me. My launch templates do have security groups. In fact, they have the same set of security groups that are assigned to the self-managed worker nodes in the same EKS cluster which allow communication with the Control Plane. That did not work.

When you deploy a Provisioner without specifying any launch templates, then Karpenter appears to pick up the security groups which have been tagged with the tag **kubernetes.io/cluster/k8s-production-cluster=owned**. I tried using a launch template with the same set of security groups picked up by Karpenter. Still, no dice.

I have attached 2 images that show these.

The first image shows the node launched by Karpenter when I don't use a custom launch template and the second one is the node launched by Karpenter with a custom template. They are both assigned the same set of security groups. What I have observed every-time I used a custom template is that the node launched does not get assigned the IAM role created for Karpenter-managed nodes. Even when I manually assigned the IAM role to it (same role used by Karpenter when it launches a node with default template)

<img width="1074" alt="karpenter-defualt" src="https://user-images.githubusercontent.com/54895557/120833400-be31c680-c52f-11eb-8db6-e5b5804c6b97.png">

<img width="1082" alt="karpenter-custom" src="https://user-images.githubusercontent.com/54895557/120833406-c0942080-c52f-11eb-843f-810768dd8062.png">

**Comment by vijayansarathy** [comment] 2021-06-04 20:32
After digging around more on the worker node launched by Karpenter with a custom launch template, I believe I have found the problem. The problem is actually two fold.

The first issue is that the worker node is launched without any IAM instance profile. My launch template does not specify any IAm role and I presumed that Karpenter will attach the instance profile created with the IAM role setup for this purpose (the one named **KarpenterNodeRole-${CLUSTER_NAME}**. Here's the Kubelet log that shows that it fails to start because of the missing instance profile.

```
Jun 04 20:08:20 ip-10-0-2-55.ec2.internal kubelet[5114]: F0604 20:08:20.419093    5114 server.go:274] failed to run Kubelet: could not init cloud provider "aws": error finding instance i-071cfe813cf795e0e: "error listing A
Jun 04 20:08:20 ip-10-0-2-55.ec2.internal systemd[1]: kubelet.service: main process exited, code=exited, status=255/n/a
Jun 04 20:08:20 ip-10-0-2-55.ec2.internal systemd[1]: Unit kubelet.service entered failed state.
Jun 04 20:08:20 ip-10-0-2-55.ec2.internal systemd[1]: kubelet.service failed.
Jun 04 20:08:25 ip-10-0-2-55.ec2.internal systemd[1]: kubelet.service holdoff time over, scheduling restart.
```

The second issue is that the worker node does not have the tag **kubernetes.io/cluster/${CLUSTER_NAME}:owned** which is required by the Kubelet to start up properly. Here again is the snippet from Kubelet logs.

```
Jun 04 20:09:07 ip-10-0-2-55.ec2.internal kubelet[5748]: E0604 20:09:07.701007    5748 tags.go:97] Tag "KubernetesCluster" nor "kubernetes.io/cluster/..." not found; Kubernetes may behave unexpectedly.
Jun 04 20:09:07 ip-10-0-2-55.ec2.internal kubelet[5748]: F0604 20:09:07.701037    5748 server.go:274] failed to run Kubelet: could not init cloud provider "aws": AWS cloud failed to find ClusterID
Jun 04 20:09:07 ip-10-0-2-55.ec2.internal systemd[1]: kubelet.service: main process exited, code=exited, status=255/n/a
Jun 04 20:09:07 ip-10-0-2-55.ec2.internal systemd[1]: Unit kubelet.service entered failed state.
Jun 04 20:09:07 ip-10-0-2-55.ec2.internal systemd[1]: kubelet.service failed.
Jun 04 20:09:12 ip-10-0-2-55.ec2.internal systemd[1]: kubelet.service holdoff time over, scheduling restart.
```

Here are the tags seen on a worker node launched with a custom launch template.
<img width="743" alt="tag-missing" src="https://user-images.githubusercontent.com/54895557/120859311-06fa7700-c552-11eb-9629-a34f3257cb76.png">



OTOH, the worker node launched w/o using a launch template appears to have this tag.
<img width="849" alt="tag-present" src="https://user-images.githubusercontent.com/54895557/120859260-f64a0100-c551-11eb-922b-8da9f49fd56e.png">


After manually fixing these issues, the worker node launched with a custom template is able to join the cluster.

**Comment by bwagner5** [comment] 2021-06-21 20:53
👍 Sounds like we need updates to documentation then. Karpenter shouldn't ever mutate a user's launch template to add the necessary elements since we can't know what AMI they're using or how they're restricting permissions or configuring the kubelet. 

We could add a blurb similar to below in the aws docs page:

---

When using a custom launch template, you need to provide:

1) An IAM Instance Profile w/ a policy like this [one](https://github.com/awslabs/karpenter/blob/291e5116d778b3fe637df64dde9769534112e8ac/docs/aws/karpenter.cloudformation.yaml#L83-L87) 
2) Tag the instance with `kubernetes.io/cluster/${YOUR_CLUSTER_NAME}: owned`
3) Security Group to allow communication w/ the k8s control plane
4) AMI ID 
5) `EC2 Userdata` that will perform any necessary configuration for the AMI to start the kubelet

**Comment by geoffcline** [comment] 2021-12-02 21:52
I opened a PR to address this. https://github.com/aws/karpenter/pull/899

I apologize @vijayansarathy for not addressing it earlier. It got stuck in our docs backlog as we focused on launch. 

Responding to user issues with fast docs updates is something writers across amazon are working on improving. :)

**Comment by geoffcline** [comment] 2021-12-15 03:36
closing because https://github.com/aws/karpenter/issues/432 solved this issue for good

**Closed by geoffcline** 2021-12-15 03:36 UTC
Labels: documentation, aws
