### ISSUE TITLE
Cannot replace spot with spot (even if a smaller and cheaper instance is available)

### ISSUE THREAD

**Issue by runningman84** [aws/karpenter#3473] opened 2023-02-27 16:45 UTC
### Tell us about your request

Karpenter provisioned a r6gd instance running a simple prometheus pod which also would fit on a t4g.large (which he used for the other pod). I would imagine that karpenter notices that a r6gd instance is more expensive than a t4g.large and would replace the instance accordingly after some time. But it just tells "cannot replace spot with spot"

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

I do not want expensive instances... everything should run at minimal costs.

### Are you currently working around this issue?

na

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment] 2023-02-27 16:50
Closing as a duplicate of #2741

**Closed by tzneal** 2023-02-27 16:50 UTC
Labels: feature
