### ISSUE TITLE
Karpenter fails to provision any new nodes when a PVC is missing

### ISSUE THREAD

**Issue by centr0nix** [aws/karpenter#1795] opened 2022-05-11 10:50 UTC
## Version

**Karpenter**: v0.9.1

**Kubernetes**: v1.21

## Expected Behavior
Karpenter should provision new nodes as expected. 

## Actual Behavior
If a PVC is missing/deleted from a deployment Karpenter fails to provision any new nodes from any of the 
applied provisioners.
## Steps to Reproduce the Problem
Delete/Remove a PVC from a deployment.

## Resource Specs and Logs
The Karpenter controller logs show the following error message:
`Provisioning failed, getting volume topology requirements, getting persistent volume claim my-vol, PersistentVolumeClaim “my-“vol not found	{"commit": "a7e26e6"}`

**Comment by dewjam** [comment] 2022-05-11 17:45
Hey @centr0nix ,
Thanks for reporting this issue.  I'm going to work on reproducing this problem today.  I'll give an update once I have more info.

**Comment by dewjam** [comment] 2022-05-13 22:18
Hello again.  I believe I was able to reproduce this.  

To clarify the issue, if a PVC is missing/deleted for a single deployment or pod, Karpenter will fail to provision nodes for all future pods, even those which aren't dependent on the missing PVC.

**Comment by centr0nix** [comment] 2022-05-14 07:51
> Hello again. I believe I was able to reproduce this.
> 
> To clarify the issue, if a PVC is missing/deleted for a single deployment or pod, Karpenter will fail to provision nodes for all future pods, even those which aren't dependent on the missing PVC.

Hello! That is correct.

**Comment by dewjam** [comment] 2022-05-16 20:39
OK great.  This certainly is not intended.  I'll be working towards a fix for this shortly.

**Closed** 2022-05-24 14:42 UTC
Labels: bug
