### ISSUE TITLE
STS issues with Karpenter controller using IRSA

### ISSUE THREAD

**Issue by youwalther65** [aws/karpenter#920] opened 2021-12-05 14:32 UTC
## Version

**Karpenter**: v0.5.0

**Kubernetes**: v1.21.3 (EKS)

## Actual Behavior

Scheduling of nodes sometimes failes when using the below Terraform automation and IRSA for Karpenter controller . Some TF deployments just work others fail with:
$ kubectl logs -f -n karpenter $(kubectl get pods -n karpenter -l karpenter=controller -o name)
..
2021-12-05T14:21:06.711Z        ERROR   controller.scheduling   Failed to schedule, matched 0/0 provisioners    {"commit": "84b683b", "pod": "default/inflate-6bb5974b-d58fb"}
2021-12-05T14:21:22.474Z        ERROR   controller.controller.metrics   Reconciler error        {"commit": "84b683b", "reconciler group": "karpenter.sh", "reconciler kind": "Provisioner", "name": "default", "namespace": "", "error": "fetching instance types using ec2.DescribeInstanceTypes, WebIdentityErr: failed to retrieve credentials\ncaused by: RequestError: send request failed\ncaused by: Post \"https://sts.eu-west-1.amazonaws.com/\": dial tcp: i/o timeout"}

## Steps to Reproduce the Problem

$ cat karpenter.tf
locals {
  k8s_service_account_namespace = "karpenter"
  k8s_service_account_name      = "karpenter"
}

# dedicated Karpenter worker node role is already created during EKS setup and added to aws-auth ConfigMap

resource "helm_release" "karpenter" {
  depends_on = [
    module.irsa-karpenter,
  ]

  name             = "karpenter"
  namespace        = local.k8s_service_account_namespace
  repository       = "https://charts.karpenter.sh"
  chart            = "karpenter"
  version          = "0.5.0"
  create_namespace = true
  wait             = true

  set {
    name  = "serviceAccount.name"
    value = local.k8s_service_account_name
  }
  set {
    name  = "serviceAccount.create"
    value = true
  }
  set {
    name  = "serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn"
    value = "${module.irsa-karpenter.iam_role_arn}"
    type  = "string"
  }
  set {
    name  = "controller.clusterName"
    value = local.name
  }
  set {
    name  = "controller.clusterEndpoint"
    value = "${data.aws_eks_cluster.eks.endpoint}"
  }
}

module "irsa-karpenter" {
  source  = "terraform-aws-modules/iam/aws//modules/iam-assumable-role-with-oidc"
  version = "~> 4.0"

  create_role                   = true
  role_name                     = "KarpenterControllerRole-${local.name}"
  provider_url                  = replace(data.aws_eks_cluster.eks.identity.0.oidc.0.issuer, "https://", "")
  role_policy_arns              = [aws_iam_policy.karpenter.arn]
  oidc_fully_qualified_subjects = ["system:serviceaccount:${local.k8s_service_account_namespace}:${local.k8s_service_account_name}"]
}

resource "aws_iam_policy" "karpenter" {
  name        = "KarpenterControllerPolicy-${local.name}"
  description = "EKS Karpenter controller policy for cluster ${local.name}"
  policy      = data.aws_iam_policy_document.karpenter.json
}

data "aws_iam_policy_document" "karpenter" {
  statement {
    sid    = "karpenterWrite"
    effect = "Allow"

    actions = [
      "ec2:CreateLaunchTemplate",
      "ec2:CreateFleet",
      "ec2:RunInstances",
      "ec2:CreateTags",
      "iam:PassRole",
      "ec2:TerminateInstances",
    ]

    resources = ["*"]
  }

  statement {
    sid    = "karpenterRead"
    effect = "Allow"

    actions = [
      "ec2:DescribeLaunchTemplates",
      "ec2:DescribeInstances",
      "ec2:DescribeSecurityGroups",
      "ec2:DescribeSubnets",
      "ec2:DescribeInstanceTypes",
      "ec2:DescribeInstanceTypeOfferings",
      "ec2:DescribeAvailabilityZones",
      "ssm:GetParameter",
    ]

    resources = ["*"]
  }
}

# Karpenter provisioners
resource "kubectl_manifest" "Karpenter-Provisioner-Default" {
  yaml_body = <<YAML
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand"]
  limits:
    resources:
      cpu: 1000
  provider:
    instanceProfile: ${local.name}-node-group-profile
  ttlSecondsAfterEmpty: 30
YAML
  depends_on = [

    helm_release.karpenter,
  ]
}

AS instanceProfile I use a profile which I use for other self-managed and managed node groups as well.

**Comment by ellistarn** [comment] 2021-12-06 17:37
This looks like an IAM setup issue. This is potentially related: https://stackoverflow.com/questions/66405794/not-authorized-to-perform-stsassumerolewithwebidentity-403

**Comment by ellistarn** [comment] 2021-12-08 18:38
Hey @youwalther65 , is this a duplicate of https://github.com/aws/karpenter/issues/933

**Comment by youwalther65** [comment] 2021-12-09 13:06
No, it is a separate issue and I wasn't able to reproduce and debug it

**Comment by ellistarn** [comment] 2021-12-09 16:51
I believe that this might've occurred during the recent us-east-1 event (including IAM). Closing for now, but please reopen if you're able to reproduce.

**Closed by ellistarn** 2021-12-09 16:51 UTC
Labels: bug, troubleshooting
