### ISSUE TITLE
Node creation in infinite loop

### ISSUE THREAD

**Issue by universam1** [aws/karpenter#1905] opened 2022-06-08 07:21 UTC
## Version

**Karpenter**: v0.10.1

**Kubernetes**: v1.21.12-eks-a64ea69

## Expected Behavior
Create a new node to provide capacity, if that is unlucky stop the loop

## Actual Behavior
In 12h Karpenter scheduled 235 nodes for the very same pod. Because of missing defragmentation the problem cascades to even spread the cluster eventually in 33 of unnecessary nodes.

Problem is that the pod request `ephemeral-storage` did not actually fit into the node, which is **probably a miscalculation**,  was therefore `pending` to start and Karpenter ran into a loop of continuously creating new nodes with the same not matching storage.

## Steps to Reproduce the Problem

- create node provisioner
```yaml
  provider:
    blockDeviceMappings:
      - deviceName: /dev/xvda
        ebs:
          encrypted: true
          volumeSize: 100Gi
          volumeType: gp3
```

- create a pod with 
```yaml
│     resources:
│       requests:
│         ephemeral-storage: 100Gi 
```

The resulting node has only **98.49Gi**, not the expected 100Gi

```yaml
Capacity:
  ephemeral-storage:           113233900Ki
Allocatable:
  ephemeral-storage:           103282620244
```

## Resource Specs and Logs
```
Batched 1 pod(s) in 1.000501513s
1 pod(s) will schedule against new capacity, 0 pod(s) against existing capacity
Launched instance: i-0a3a0aad7547c6972, hostname: ip-172-16-13-98.ec2.internal, type: c5.xlarge, zone: us-east-1b, capacityType: spot
Created node with 1 pods requesting {"cpu":"2470m","ephemeral-storage":"100Gi","memory":"4566Mi","pods":"9"} from types c4.xlarge, c6a.xlarge, c5.xlarge, c6i.xlarge, c5a.xlarge and 352 other(s)
Webhook ServeHTTP request=&http.Request{Method:"POST", URL:(*url.URL)(0xc000ceaab0), Proto:"HTTP/1.1", ProtoMajor:1, ProtoMinor:1, Header:http.Header{"Accept":[]string{"application/json, */*"}, "Accept-Encoding":[]string{"gzip"}, "Content-Length":[]string{"7932"}, "Content-Type":[]string{"application/json"}, "User-Agent":[]string{"kube-apiserver-admission"}}, Body:(*http.body)(0xc00064c940), GetBody:(func() (io.ReadCloser, error))(nil), ContentLength:7932, TransferEncoding:[]string(nil), Close:false, Host:"karpenter.karpenter.svc:443", Form:url.Values(nil), PostForm:url.Values(nil), MultipartForm:(*multipart.Form)(nil), Trailer:http.Header(nil), RemoteAddr:"172.16.23.64:48740", RequestURI:"/default-resource?timeout=10s", TLS:(*tls.ConnectionState)(0xc0004fc210), Cancel:(<-chan struct {})(nil), Response:(*http.Response)(nil), ctx:(*context.cancelCtx)(0xc00064c980)}
Kind: "karpenter.sh/v1alpha5, Kind=Provisioner" PatchBytes: null
remote admission controller audit annotations=map[string]string(nil)
Webhook ServeHTTP request=&http.Request{Method:"POST", URL:(*url.URL)(0xc000ceb290), Proto:"HTTP/1.1", ProtoMajor:1, ProtoMinor:1, Header:http.Header{"Accept":[]string{"application/json, */*"}, "Accept-Encoding":[]string{"gzip"}, "Content-Length":[]string{"7932"}, "Content-Type":[]string{"application/json"}, "User-Agent":[]string{"kube-apiserver-admission"}}, Body:(*http.body)(0xc00064de40), GetBody:(func() (io.ReadCloser, error))(nil), ContentLength:7932, TransferEncoding:[]string(nil), Close:false, Host:"karpenter.karpenter.svc:443", Form:url.Values(nil), PostForm:url.Values(nil), MultipartForm:(*multipart.Form)(nil), Trailer:http.Header(nil), RemoteAddr:"172.16.23.64:48742", RequestURI:"/validate-resource?timeout=10s", TLS:(*tls.ConnectionState)(0xc0004fc630), Cancel:(<-chan struct {})(nil), Response:(*http.Response)(nil), ctx:(*context.cancelCtx)(0xc00064de80)}
remote admission controller audit annotations=map[string]string(nil)
Waiting for unschedulable pods
Bound persistent volume claim to node ip-172-16-13-98.ec2.internal
Webhook ServeHTTP request=&http.Request{Method:"POST", URL:(*url.URL)(0xc000811680), Proto:"HTTP/1.1", ProtoMajor:1, ProtoMinor:1, Header:http.Header{"Accept":[]string{"application/json, */*"}, "Accept-Encoding":[]string{"gzip"}, "Content-Length":[]string{"7932"}, "Content-Type":[]string{"application/json"}, "User-Agent":[]string{"kube-apiserver-admission"}}, Body:(*http.body)(0xc000b78140), GetBody:(func() (io.ReadCloser, error))(nil), ContentLength:7932, TransferEncoding:[]string(nil), Close:false, Host:"karpenter.karpenter.svc:443", Form:url.Values(nil), PostForm:url.Values(nil), MultipartForm:(*multipart.Form)(nil), Trailer:http.Header(nil), RemoteAddr:"172.16.23.64:48740", RequestURI:"/default-resource?timeout=10s", TLS:(*tls.ConnectionState)(0xc0004fc210), Cancel:(<-chan struct {})(nil), Response:(*http.Response)(nil), ctx:(*context.cancelCtx)(0xc000b78180)}
Kind: "karpenter.sh/v1alpha5, Kind=Provisioner" PatchBytes: null
remote admission controller audit annotations=map[string]string(nil)
Webhook ServeHTTP request=&http.Request{Method:"POST", URL:(*url.URL)(0xc000811e60), Proto:"HTTP/1.1", ProtoMajor:1, ProtoMinor:1, Header:http.Header{"Accept":[]string{"application/json, */*"}, "Accept-Encoding":[]string{"gzip"}, "Content-Length":[]string{"7932"}, "Content-Type":[]string{"application/json"}, "User-Agent":[]string{"kube-apiserver-admission"}}, Body:(*http.body)(0xc000b79300), GetBody:(func() (io.ReadCloser, error))(nil), ContentLength:7932, TransferEncoding:[]string(nil), Close:false, Host:"karpenter.karpenter.svc:443", Form:url.Values(nil), PostForm:url.Values(nil), MultipartForm:(*multipart.Form)(nil), Trailer:http.Header(nil), RemoteAddr:"172.16.23.64:48742", RequestURI:"/validate-resource?timeout=10s", TLS:(*tls.ConnectionState)(0xc0004fc630), Cancel:(<-chan struct {})(nil), Response:(*http.Response)(nil), ctx:(*context.cancelCtx)(0xc000b79340)}
remote admission controller audit annotations=map[string]string(nil)
Batched 1 pod(s) in 1.000492692s
1 pod(s) will schedule against new capacity, 0 pod(s) against existing capacity
Launched instance: i-037f438e498e68aca, hostname: ip-172-16-20-139.ec2.internal, type: c5a.xlarge, zone: us-east-1c, capacityType: spot
Created node with 1 pods requesting {"cpu":"2470m","ephemeral-storage":"100Gi","memory":"4566Mi","pods":"9"} from types c4.xlarge, c5a.xlarge, c6a.xlarge, c6i.xlarge, c5.xlarge and 352 other(s)
Webhook ServeHTTP request=&http.Request{Method:"POST", URL:(*url.URL)(0xc000b70480), Proto:"HTTP/1.1", ProtoMajor:1, ProtoMinor:1, Header:http.Header{"Accept":[]string{"application/json, */*"}, "Accept-Encoding":[]string{"gzip"}, "Content-Length":[]string{"7932"}, "Content-Type":[]string{"application/json"}, "User-Agent":[]string{"kube-apiserver-admission"}}, Body:(*http.body)(0xc000b511c0), GetBody:(func() (io.ReadCloser, error))(nil), ContentLength:7932, TransferEncoding:[]string(nil), Close:false, Host:"karpenter.karpenter.svc:443", Form:url.Values(nil), PostForm:url.Values(nil), MultipartForm:(*multipart.Form)(nil), Trailer:http.Header(nil), RemoteAddr:"172.16.23.64:48740", RequestURI:"/default-resource?timeout=10s", TLS:(*tls.ConnectionState)(0xc0004fc210), Cancel:(<-chan struct {})(nil), Response:(*http.Response)(nil), ctx:(*context.cancelCtx)(0xc000b51200)}
Kind: "karpenter.sh/v1alpha5, Kind=Provisioner" PatchBytes: null
remote admission controller audit annotations=map[string]string(nil)
Webhook ServeHTTP request=&http.Request{Method:"POST", URL:(*url.URL)(0xc000b70c60), Proto:"HTTP/1.1", ProtoMajor:1, ProtoMinor:1, Header:http.Header{"Accept":[]string{"application/json, */*"}, "Accept-Encoding":[]string{"gzip"}, "Content-Length":[]string{"7932"}, "Content-Type":[]string{"application/json"}, "User-Agent":[]string{"kube-apiserver-admission"}}, Body:(*http.body)(0xc000bc6380), GetBody:(func() (io.ReadCloser, error))(nil), ContentLength:7932, TransferEncoding:[]string(nil), Close:false, Host:"karpenter.karpenter.svc:443", Form:url.Values(nil), PostForm:url.Values(nil), MultipartForm:(*multipart.Form)(nil), Trailer:http.Header(nil), RemoteAddr:"172.16.23.64:48742", RequestURI:"/validate-resource?timeout=10s", TLS:(*tls.ConnectionState)(0xc0004fc630), Cancel:(<-chan struct {})(nil), Response:(*http.Response)(nil), ctx:(*context.cancelCtx)(0xc000bc63c0)}
Waiting for unschedulable pods
remote admission controller audit annotations=map[string]string(nil)
Bound persistent volume claim to node ip-172-16-20-139.ec2.internal
Added TTL to empty node
Batched 1 pod(s) in 1.00071552s
```

**Comment by dewjam** [comment] 2022-06-08 14:46
Hello @universam1 ,
Often the difference between `Capacity` and `Allocatable` resources is due to `kube-reserved` or `system-reserved` values being passed to Kubelet.  For example, with the EKS optimized AL2 image, 1Gi of ephemeral-storage is reserved which causes the Allocatable ephemeral-storage to report 1GB less than the actual available disk size.

I believe the issue you encountered is actually due to a problem with how Karpenter used to handle bin-packing of pods that have ephemeral-storage requests defined.  We merged a fix for this problem in https://github.com/aws/karpenter/pull/1859, which will be included in the next release.  Before this fix, it was certainly possible for nodes to be launched which could not satisfy the ephemeral-storage requirements of a given pod.

**Comment by dewjam** [comment] 2022-06-08 15:10
To take this a bit further, with #1859 the pod would remain in a pending state without any new nodes being launched, given no instance types would be able to satisfy the pod's ephemeral-storage requests.

With #1859 we take out (5GB) of storage from the actual disk size when bin-packing pods to nodes to account for "system" services, etc.  So in your case, if a pod requires 100GB of ephemeral storage, then you would want to set the block device to a minimum of 105GB.

**Comment by universam1** [comment] 2022-06-08 15:27
Thank you @dewjam for the insights and explanations - and as I can see working out a solution already!
The storage head room sounds like a practical solution, which is what I do manually now, given that without this checks as of now it can happen any time again.
Happy to see that this case is covered and should be fixed with the new release, eagerly awaiting the improvements of this new release!
I can check once the release is rolled out if this issue is closed.

**Comment by dewjam** [comment] 2022-06-08 20:39
My pleasure!  If you would like to try out the code before official release, we do have a snapshot out there:  https://kubernetes.slack.com/archives/C02SFFZSA2K/p1654563719352349

*Obviously, this should not be used for production use-cases*

---
If case you're not part of the Kubernetes Slack org, here's the process to test it out:

```
export CLUSTER_NAME="<CLUSTER_NAME>"
export COMMIT="06bd4282b6cfd2419b5f6e31340b7d32d00d167e"
export AWS_ACCOUNT_ID="$(aws sts get-caller-identity --query Account --output text)"
export KARPENTER_IAM_ROLE_ARN="arn:aws:iam::${AWS_ACCOUNT_ID}:role/${CLUSTER_NAME}-karpenter"
export CLUSTER_ENDPOINT="$(aws eks describe-cluster --name ${CLUSTER_NAME} --query "cluster.endpoint" --output text)"
```

```
helm install karpenter oci://public.ecr.aws/karpenter-snapshots/karpenter --version v0-${COMMIT} --namespace karpenter \
  --set serviceAccount.annotations."eks\.amazonaws\.com/role-arn"=${KARPENTER_IAM_ROLE_ARN} \
  --set clusterName=${CLUSTER_NAME} \
  --set clusterEndpoint=${CLUSTER_ENDPOINT} \
  --set aws.defaultInstanceProfile=KarpenterNodeInstanceProfile-${CLUSTER_NAME} \
  --wait # for the defaulting webhook to install before creating a Provisioner
```

**Comment by dewjam** [comment] 2022-06-09 20:44
Hello @universam1 ,
I'm going to go ahead and close this out, but please feel free to reopen if you find the issue is not resolved.

Thanks!

**Closed by dewjam** 2022-06-09 20:44 UTC
Labels: bug
