### ISSUE TITLE
Dynamic disk size

### ISSUE THREAD

**Issue by winnieoursbrun** [aws/karpenter#4701] opened 2023-09-26 17:40 UTC
### Description

**What problem are you trying to solve?**
For cost optimisation, we are using 80Go disk, but we need to limit the instance size because when there is too much pods the disk can be filled. So we need to double up the disk size for doubling up the instance size. So we will have 160Go for normal instance, uselessly. 

**How important is this feature to you?**
Low, not a big cost for us, so it's okay for now.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment] 2023-09-29 15:47
I'm going to close this as a duplicate of https://github.com/aws/karpenter/issues/2394. Can you include any information there that you don't think is covered?

**Closed by tzneal** 2023-09-29 15:47 UTC
Labels: feature
