### ISSUE TITLE
Clarify in v1beta1 Upgrade Guide which AWS role to use in the EC2NodeClass

### ISSUE THREAD

**Issue by billrayburn** [aws/karpenter#4827] opened 2023-10-13 02:15 UTC
### Description

Can the [v1beta1 Upgrade Guide](https://deploy-preview-4749--karpenter-docs-prod.netlify.app/preview/upgrade/upgrade-guide/#prerequisites) be more clear about which AWS role to use in Step 8?

- Step 4 said "Apply the new Karpenter policy and assign it to the existing Karpenter role". 
- Step 8 said, "Specify your AWS role where there is a your AWS role Here placeholder".

I was just following the instructions from top to bottom, so I guessed that Step 8 was referring to the AWS role created in Step 4. In my case, turns out I needed to use the existing role prepended with KarpenterNodeRole that was created following [Getting Started with Karpenter](https://karpenter.sh/docs/getting-started/getting-started-with-karpenter/).

**Comment by jonathan-innis** [comment] 2023-10-13 22:00
Appears to be a duplicate of #4820

**Closed by jonathan-innis** 2023-10-13 22:00 UTC
Labels: documentation
