### ISSUE TITLE
Scheduling configuration priority

### ISSUE THREAD

**Issue by debugger24** [aws/karpenter#2295] opened 2022-08-16 04:31 UTC
**Tell us about your request**
What do you want us to build?

Currently, we define the desired config in provisioner.

It will be nice to have set some priority like on type of instances, was region etc.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

Sometimes some class of EC2 instances are not available, like in my case, p3 was not able when I was trying to schedule, in that case would prefer to fallback to 2nd gen i.e. p2 series. Same can be for AWS region too, user may like to provision instance in their nearby location but if not available fallback to other regions.

**Are you currently working around this issue?**
How are you currently solving this problem?

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment] 2022-08-17 16:06
Closing as a duplicate of https://github.com/aws/karpenter/issues/2024. I'm totally supportive of this feature.

**Closed by ellistarn** 2022-08-17 16:06 UTC
Labels: feature

**Comment by debugger24** [comment] 2022-08-17 16:21
It's similar but Ticket #2024 talks about weighted configuration, like if it is 80:20, out of 100 20 times it will create second configuration.

In my case, we want 100% of the time use first config if available, if not available use second config.

**Comment by ellistarn** [comment] 2022-08-17 18:22
> In my case, we want 100% of the time use first config if available, if not available use second config.

This is the semantic proposed in #2024

**Comment by jonathan-innis** [comment] 2022-08-17 18:34
> In my case, we want 100% of the time use first config if available, if not available use second config.

Design for allowing this priority is proposed in #2246 and being implemented in #2307

**Comment by debugger24** [comment] 2022-08-18 06:37
Thanks @ellistarn @jonathan-innis
