### ISSUE TITLE
Be able to set instance Name via tags on a provisioner

### ISSUE THREAD

**Issue by andrewhibbert** [aws/karpenter#4314] opened 2023-07-20 17:35 UTC
### Description

**What problem are you trying to solve?**

I'd like to be able to set a custom Name for an instance created by Karpenter, without this coming from `AWSNodeTemplate`. Then we can have multiple Provisioners pointing at one AWSNodeTemplate

**How important is this feature to you?**

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment] 2023-07-20 18:20
Sounds related to #4228. If this is a duplicate, could you add details around your use-case there and we can close this feature in favor of that one?

**Comment by njtran** [comment] 2023-07-21 17:41
Like @jonathan-innis mentioned, closing as a duplicate of the linked issue. Feel free to re-open if you think otherwise!

**Closed by njtran** 2023-07-21 17:41 UTC
Labels: feature
