### ISSUE TITLE
pod in ImagePullBackOff with "do-not-evict" should be drifted

### ISSUE THREAD

**Issue by jess-belliveau** [aws/karpenter#4641] opened 2023-09-18 03:46 UTC
### Description

**What problem are you trying to solve?**
I've noted behaviour with the "do-not-evict" annotation that if a pod reaches a state like `ImagePullBackOff` - Karpenter will still honour the annotation and not evict the pod. Meaning the node remains essentially wasting compute as a pod really isn't running on it.

```
Events:
  Type    Reason                 Age                      From       Message
  ----    ------                 ----                     ----       -------
  Normal  DeprovisioningBlocked  6m14s (x1239 over 2d6h)  karpenter  Cannot deprovision machine due to pod namespace/pod-name-28244370-qkvpp has do not evict annotation
```

I don't see why Karpenter could not choose to ignore the annotation in this case as the pod is not really running and as such the node could be a good candidate to deprovision.

**How important is this feature to you?**
I would mark this as a nice to have - it would allow a platform to continue "drifting" nodes even if a consuming team incorrectly sets their image.

**Comment by ellistarn** [comment] 2023-09-18 16:00
Duplicate of https://github.com/aws/karpenter/issues/3537

**Closed by ellistarn** 2023-09-18 16:00 UTC
Labels: feature
