### ISSUE TITLE
Enable the feature that PDB Bypass After Timeout in Karpenter

### ISSUE THREAD

**Issue by mallow111** [aws/karpenter#4542] opened 2023-09-01 21:28 UTC
### Description

**What problem are you trying to solve?**
What we want to is that for choosen namespace/deployment, we can bypass its pdb after timeout, we can for example delete those broken pods, the goal is to let karpenter continue recycling nodes instead of hanging there.

**How important is this feature to you?**
Our company is trying to adopt karpenter for node patching, we have huge amount of clusters, we noticed sometimes the patching take a long time is because the pdb issue, we would like to provide some flexibility for some known deployment to bypass its pdb, and the whole patching can continue in the cluster.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment] 2023-09-02 00:08
Looks like a duplicate of #2481. Can you add any additional thoughts that you might have there on this issue? Feel free to re-open if marking this as a duplicate was incorrect.

**Closed by jonathan-innis** 2023-09-02 00:08 UTC
Labels: feature

**Comment by mallow111** [comment] 2023-09-05 16:45
sure, i will comment in ticket #2481, thx!
