### ISSUE TITLE
Karpenter replicas cause metrics service to wrongly route requests

### ISSUE THREAD

**Issue by tlk-kayrros** [aws/karpenter#2480] opened 2022-09-08 20:48 UTC
## Version

**Karpenter**: v0.16.1

**Kubernetes**: v1.22.11-eks-18ef993

## Expected Behavior
When a controller is using replicas=2 or more the metrics should be available in any of the replicas.

## Actual Behavior
By adding replicas in #2311 the idea was to implement the rolling update strategy and improve the availability of the Karpenter controller. When implementing this change we realised our Karpenter metrics were no longer properly collected by Prometheus. We discovered that the controller which is not currently active doesn't export metrics correctly and exports mainly zeroes and NaN. If the service route the traffic of http-metrics to the inactive controller, it wrongly exposes incomplete metrics causing metric collection disruption.

## Steps to Reproduce the Problem
Add replicas=2 and check metric exposition at the service level.

**Comment by jonathan-innis** [comment] 2022-09-13 18:26
Hi @tlk-kayrros, can you describe what the specific issue is here? If you are using a `ServiceMonitor`, Prometheus will just use the service for endpoint discovery, but will still scrape metrics from all pods so I don't believe the routing issue that you described above will occur with Prometheus `ServiceMonitor`

**Comment by dewjam** [comment] 2022-09-22 16:28
Hello @tlk-kayrros ,
I looked into this a bit further and this seems to be related to how our Prometheus scrape targets are configured.  The "karpenter" service is added as a static target which means we are not scraping each Karpenter pod individually. In short, only one of the pods will be scraped at each scrape interval.  

Here is the config I'm referring to:  https://github.com/aws/karpenter/blob/main/website/content/en/preview/getting-started/getting-started-with-eksctl/prometheus-values.yaml#L10-L14

I think the best option here is use the [pod](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#pod) or [endpoint](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#endpoints) service discovery mechanism to scrape both pods at every scrape interval.  Then make sure the predefined queries for Karpenter are aggregating those metrics properly.

**Comment by dewjam** [comment] 2022-10-20 18:35
Hello tlk-kayrros@,
I just pushed up a PR which changes the scrape target to use endpoint discovery instead of a static scrape target.  Let me know if you think this will solve your problem.

**Comment by tlk-kayrros** [comment] 2022-10-21 07:32
It will probably solve the issue, yes. Thanks a lot

**Comment by dewjam** [comment] 2022-10-24 20:19
Closing this out as the PR is now merged.  Feel free to reopen if you feel the issue is not solved.

**Closed by dewjam** 2022-10-24 20:19 UTC
Labels: bug
