### ISSUE TITLE
metric karpenter_pods_state shows wrong data

### ISSUE THREAD

**Issue by arnoldyahad** [aws/karpenter#2498] opened 2022-09-13 13:05 UTC
### Version

Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.16-eks-a05fdea", GitCommit:"a05fdea9a04815782f9c4b08eed73bb2d78b07e3", GitTreeState:"clean", BuildDate:"2022-06-09T21:50:47Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}

### Expected Behavior

Hello,
We are using karpenter v0.16 and are utilizing the metrics for monitoring purposes.
We have noticed that we have a pod that is in `ContainerCreating` state but the `karpenter_pods_state` shows it as `pending`. 

for example we will use a pod named: `sleep-db77db456-drf92`

the pod is in ContainerCreating:
```
kubectl get pods -A | grep sleep-db
devops-apps-01                  sleep-db77db456-drf92                                             0/2     ContainerCreating   0          2d3h
```

But the metric shows it as Pending:

<img width="1347" alt="image" src="https://user-images.githubusercontent.com/18227724/189907891-adf15f53-20ed-442a-964e-19668a068d98.png">

We want the metric to be fixed to show the current `phase` of the pod.

### Actual Behavior

Metric shows wrong status as described in `Expected Behaviour`

### Steps to Reproduce the Problem

to reproduce the problem, i think you need to have a pod in `ContainerCreating` phase and watch the metric karpenter_pods_state

### Resource Specs and Logs

nothing in the logs of karpenter.

**Comment by jonathan-innis** [comment] 2022-09-13 18:21
This is by design. The `phase` parameter matches the `.status.phase` of each of the pods. In the case of a pod that is in a `ContainerCreating` state, the `.status.phase` will be `pending`

```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/psp: eks.privileged
  creationTimestamp: "2022-09-13T18:14:23Z"
  generateName: inflate-6d4b6466f8-
  labels:
    app: inflate
    app.kubernetes.io/name: inflate
    pod-template-hash: 6d4b6466f8
  name: inflate-6d4b6466f8-68wss
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: inflate-6d4b6466f8
    uid: 19e3f68c-3843-4399-8b91-ccc97348b30a
  resourceVersion: "12125880"
  uid: 4d5a8967-a04f-4f0b-a228-3bc4f2402ded
spec:
  containers:
  - image: public.ecr.aws/eks-distro/kubernetes/pause:3.2
    imagePullPolicy: IfNotPresent
    name: inflate
    resources:
      requests:
        cpu: "1"
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/config
      name: config-vol
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-qn8jn
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: ip-172-31-4-156.us-west-2.compute.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 0
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - configMap:
      defaultMode: 420
      items:
      - key: log_level
        path: log_level
      name: log-config
    name: config-vol
  - name: kube-api-access-qn8jn
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-09-13T18:14:23Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-09-13T18:14:23Z"
    message: 'containers with unready status: [inflate]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-09-13T18:14:23Z"
    message: 'containers with unready status: [inflate]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-09-13T18:14:23Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: public.ecr.aws/eks-distro/kubernetes/pause:3.2
    imageID: ""
    lastState: {}
    name: inflate
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        reason: ContainerCreating
  hostIP: 172.31.4.156
  phase: Pending
  qosClass: Burstable
  startTime: "2022-09-13T18:14:23Z"
```

**Comment by jonathan-innis** [comment] 2022-09-16 22:48
Closing since this is expected behavior based on the Pod phase

**Closed by jonathan-innis** 2022-09-16 22:48 UTC
Labels: bug
