### ISSUE TITLE
recheck spot price after interval

### ISSUE THREAD

**Issue by pdeva** [aws/karpenter#3812] opened 2023-04-26 02:59 UTC
### Tell us about your request

Consider this scenario, where larger node Node type A is `m6gd.xlarge` and smaller Node type B is `m6g.xlarge`.

1. Karpenter picks an A node instead of a B node even though the workload would run fine on a B node cause at the time of choosing the A node is cheaper in terms of spot pricing.
2. After a few hours though node B types are available on Spot for cheaper than node type A.
3. However, Karpenter doesnt know about this and we continue paying for larget Node A even though cheaper Node B is now available. We have to wait till `ttlSecondsUntilExpired` until Karpenter will check for another node, which could be weeks from now!

I propose a new option: `recheckSpotAvailabilityAfter` which takes a number of minutes as parameter.
After specifying `recheckSpotAvailabilityAfter: 180`:

1. Karpenter will now check every 3 hours if a better node is available on Spot for the workload on Node A. 
2. Since it will notice Node type B is now available which is cheaper and has enough capacity, it will switch nodes to Node type B, thus allowing us to gain the cost savings without waiting for node expiry for weeks.

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

Trying to get the best cost for the cluster based on updated Spot pricing. Currently Karpenter doesnt check for this after a node has been spun up, but the Spot market is constantly changing. This change would allow Karpenter to truly offer best pricing depending on Spot market changes.

### Are you currently working around this issue?

Currently the only workaround is to set lower and lower `ttlSecondsUntilExpired` value which causes unnecessary churn in the cluster.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by FernandoMiguel** [comment] 2023-04-26 13:37
karpenter does not consolidate spot instances for cheaper ones.
it only does this for ON-DEMAND

**Comment by FernandoMiguel** [comment] 2023-04-26 15:23
the reason why it doesn't consolidate on SPOT is because there are no guarantees newer (cheaper) nodes will live for as long as the current one they are replacing, potentially causing more churm

**Comment by jonathan-innis** [comment] 2023-04-26 17:37
I think this falls under the bucket of #2741. @pdeva Can you add some of your thoughts on that tracking issue? I think we can consider closing this issue as a duplicate.

**Comment by jonathan-innis** [comment] 2023-05-01 21:01
Closing as a duplicate of #2741

**Closed by jonathan-innis** 2023-05-01 21:01 UTC
Labels: feature
