### ISSUE TITLE
Add documentation that calls attention to containerd being the default runtime when you don't configure a launch template. 

### ISSUE THREAD

**Issue by jicowan** [aws/karpenter#1466] opened 2022-03-03 20:07 UTC
Docker will be the default runtime in EKS until 1.23. Customers who want to run containerd have to set it using the flag `--container-runtime`. If nodes provisioned through Karpenter are going to use containerd by default, it should be documented. 

https://github.com/aws/karpenter/blob/5e8dc24f8cbd86e8440060b8961c07bc6d3dadf5/pkg/cloudprovider/aws/launchtemplate.go#L343

**Comment by bwagner5** [comment] 2022-03-04 19:30
Duplicate of https://github.com/aws/karpenter/issues/1056

**Closed by bwagner5** 2022-03-04 19:30 UTC
Labels: documentation
