### ISSUE TITLE
Tag Keys with `/` in them fail to work on global tag configuration

### ISSUE THREAD

**Issue by sidewinder12s** [aws/karpenter#3197] opened 2023-01-11 00:50 UTC
### Version

__Karpenter Version:__ v0.22.0

__Kubernetes Version:__ v1.22

### Expected Behavior

I should be able to use any valid tag key characters in the aws global tag configuration.

### Actual Behavior

The configmap cannot take a `/` based on how the helm chart and Karpenter expect the config.

### Steps to Reproduce the Problem

Helm Values:

```yaml
settings:
  aws:
    tags:
      my-tag/contact: my-name
      my-tag/project: thingy
```

Error messgae:

```log
one or more objects failed to apply, reason: ConfigMap "karpenter-global-settings" is invalid: [data[aws.tags.my-tag/project]: Invalid value: "aws.tags.my-tag/project": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[aws.tags.my-tag/contact]: Invalid value: "aws.tags.my-tag/contact": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+')]
```

### Resource Specs and Logs

https://karpenter.sh/v0.22.0/concepts/settings/#aws-parameters

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment] 2023-01-12 20:34
This looks to be intended from Kubernetes. https://kubernetes.io/docs/concepts/configuration/configmap/#configmap-object

If your tag keys are unable to be used without the forward slashes, then you can opt to include tags on your AWSNodeTemplate (More [here](https://karpenter.sh/v0.22.1/concepts/node-templates/#spectags)). Otherwise, refer how to set global tags on your AWS resources [here](https://karpenter.sh/v0.22.1/concepts/settings/#aws-parameters)

Since this is expected behavior, I'll close this issue. Feel free to re-open if you need.

**Comment by sidewinder12s** [comment] 2023-01-12 20:43
I mean, this seems like a deficiency in how to configure Karpenter and might not be the first time config cannot be set due to explicitly using the configmap key/value structure instead of more generic format.

**Comment by ellistarn** [comment] 2023-01-12 22:29
@njtran @jonathan-innis maybe we need to adopt the same approach as config-logging? 
https://github.com/aws/karpenter/blob/main/charts/karpenter/templates/configmap-logging.yaml

Painful incompat change, but a bummer as is.

**Comment by jonathan-innis** [comment] 2023-01-18 18:50
@sidewinder12s I think we probably don't want to completely overhaul the ConfigMap yet. I'm thinking we can just pare down to using the key `aws.tags` and the value to be JSON map of tag keys to tag

**Comment by sidewinder12s** [comment] 2023-01-18 22:26
Ya, I had actually tried doing that as well until I realized it was breaking out each tag into a seperate line key. 

Also realized that I was using the wrong cost allocation tags internally cause they are different for us between AWS and Kubernetes, so I don't even have `/`'s in our AWS cost tags 🤦 

But I would not be surprised at all if someone else ran into this.

**Comment by jonathan-innis** [comment] 2023-01-19 19:16
Yeah, this is definitely a bug regardless. The summary here is that we can't do tags like the current way we are doing it in the ConfigMap.

**Comment by igor-nikiforov** [comment] 2023-01-22 19:48
I have the same issue. Tried use global tags but realized that tags with slashes does not work.

As a workaround I'm using tags setting at `AWSNodeTemplate` which is inconvenient because I'm need to repeat each of my global tag in every new template.

**Comment by fascenvi** [comment] 2023-01-23 17:25
The same here....I tried to add a tag karpenter.sh/discovery :(

Have we a possibility to add the default tag "karpenter.sh/discovery", like defaults tags from Nodes ? (it's tag is the same tag used by default in the IAM conditional "terraform-aws-modules/eks/aws//modules/karpenter" to manage the launch-templates and ec2)

**Comment by jonathan-innis** [comment] 2023-01-23 17:32
@fascenvi Using the `karpenter.sh/discovery` tag isn't required. You can use any tag and values in the selectors that you want. `karpenter.sh/discovery` is more of a placeholder/an example tag that we use by default across all of our documentation.

**Comment by fascenvi** [comment] 2023-01-23 17:44
Tks to explain  @jonathan-innis!
I just suggested it to match with the default values on sub-module terraform-aws-modules/eks/aws//modules/karpenter. I waste some time until see the problem.

**Closed** 2023-02-01 23:19 UTC
Labels: bug
