### ISSUE TITLE
EC2 Spot to On-Demand fallback does not work as expected by using soft affinity (preferred) in Pod manifest

### ISSUE THREAD

**Issue by ashwinikumar-sa** [aws/karpenter#1233] opened 2022-01-28 13:41 UTC
Karpenter Version: v0.5.6
Kubernetes: v1.20.7

**Expected Behavior**
If we create a provisioner with both ["on-demand","spot"] capacity type options and workloads are also flexible on Spot/OD (through soft affinity in Pod manifest), Karpenter should fall back to OD capacity, after trying for Spot capacity first and if Spot is not available

**Actual Behavior**
Despite of using soft affinity in Pod manifest with preferredDuringSchedulingIgnoredDuringExecution with "Spot" capacity type label,  Karpenter did not fall back to On-demand capacity and kept trying for Spot capacity. Provisioner had both ["on-demand","spot"] options for karpenter.sh/capacity-type.

**Steps to Reproduce the Problem**
- Enabled debug logging
`kubectl patch configmap config-logging -n karpenter --patch '{"data":{"loglevel.controller":"debug"}}'`

- Created a Provisioner with both ["on-demand","spot"] options for karpenter.sh/capacity-type and with GPU instances for which Spot capacity is hard to get but On-demand capacity may be available. Provisioner spec file name - "provisioner-gpu.yaml"
`kubectl apply -f provisioner-gpu.yaml`
 
- Created a Pod manifest with soft affinity (preferredDuringSchedulingIgnoredDuringExecution with "Spot" capacity type label) and create a pod deployment - Pod manifest file name - "inflate-gpu.yaml"
`kubectl apply -f inflate-gpu.yaml`

**Resource Specs and Logs**

**Provisioner spec for provisioner-gpu.yaml**

```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: provisioner-gpu
spec:
  ttlSecondsAfterEmpty: 30
  labels:
    intent: apps
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand","spot"]
    - key: node.kubernetes.io/instance-type
      operator: In
      values: ["g4dn.xlarge"]
  limits:
    resources:
      cpu: 256
  provider:
    instanceProfile: KarpenterNodeInstanceProfile-eksworkshop-eksctl
    tags:
      accountingEC2Tag: KarpenterDevEnvironmentEC2
    securityGroupSelector:
      karpenter.sh/discovery: eksworkshop-eksctl
    subnetSelector:
      karpenter.sh/discovery: eksworkshop-eksctl
```

**Pod manifest inflate-gpu.yaml**
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate-gpu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inflate-gpu
  template:
    metadata:
      labels:
        app: inflate-gpu
    spec:
      nodeSelector:
        intent: apps
        karpenter.sh/provisioner-name: provisioner-gpu
      affinity: 
        nodeAffinity: 
          preferredDuringSchedulingIgnoredDuringExecution: 
          - weight: 1
            preference: 
              matchExpressions: 
              - key: karpenter.sh/capacity-type 
                operator: In 
                values: 
                - spot
      containers:
        - name: inflate-gpu
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.2
          resources:
            limits:
              nvidia.com/gpu: "1"
              # aws.amazon.com/neuron: "1"
            requests:
              cpu: 1500m
              memory: 6Gi 
``` 

**Karpenter controller logs extract**
2022-01-28T13:14:47.767Z        INFO    controller.provisioning Batched 1 pods in 1.00028814s   {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:14:48.168Z        DEBUG   controller.provisioning Discovered subnets: [subnet-00d26d958f2e37222 (us-east-1a) subnet-09a7943d66a9d6a1b (us-east-1b) subnet-0ffe96b0ecd05ff71 (us-east-1c) subnet-03832a499b0326725 (us-east-1d)]    {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:14:48.174Z        INFO    controller.provisioning Computed packing of 1 node(s) for 1 pod(s) with instance type option(s) [g4dn.xlarge]    {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:14:48.368Z        DEBUG   controller.provisioning Discovered security groups: [sg-0aa637d62613334b8]      {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:14:48.373Z        DEBUG   controller.provisioning Discovered kubernetes version 1.20      {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:14:48.527Z        DEBUG   controller.provisioning Discovered ami ami-0d599dfae63ef9a11 for query /aws/service/eks/optimized-ami/1.20/amazon-linux-2-gpu/recommended/image_id       {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:14:48.527Z        DEBUG   controller.provisioning Discovered caBundle, length 1025        {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:14:48.573Z        DEBUG   controller.provisioning Discovered launch template Karpenter-eksworkshop-eksctl-18338213868441572111     {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
**2022-01-28T13:14:51.172Z        DEBUG   controller.provisioning InsufficientInstanceCapacity for offering { instanceType: g4dn.xlarge, zone: us-east-1c, capacityType: spot }, avoiding for 45s  {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:14:51.172Z        DEBUG   controller.provisioning InsufficientInstanceCapacity for offering { instanceType: g4dn.xlarge, zone: us-east-1d, capacityType: spot }, avoiding for 45s  {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:14:51.172Z        ERROR   controller.provisioning Could not launch node, launching instances, with fleet error(s), InsufficientInstanceCapacity: There is no Spot capacity available that matches your request.; InsufficientInstanceCapacity: We currently do not have sufficient g4dn.xlarge capacity in the Availability Zone you requested (us-east-1d). Our system will be working on provisioning additional capacity. You can currently get g4dn.xlarge capacity by not specifying an Availability Zone in your request or choosing us-east-1a, us-east-1b, us-east-1c, us-east-1f.; UnfulfillableCapacity: Unable to fulfill capacity due to your request configuration. Please adjust your request and try again.     {"commit": "2346ed5", "provisioner": "provisioner-gpu"}**
2022-01-28T13:14:51.172Z        INFO    controller.provisioning Waiting for unschedulable pods  {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
**2022-01-28T13:14:56.173Z        DEBUG   controller.selection    Relaxing soft constraints for default/inflate-gpu-564bffdf6d-cm7pn since it previously failed to schedule, removing: spec.affinity.nodeAffinity.preferredDuringSchedulingIgnoredDuringExecution[0]={"weight":1,"preference":{"matchExpressions":[{"key":"karpenter.sh/capacity-type","operator":"In","values":["spot"]}]}}        {"commit": "2346ed5", "pod": "default/inflate-gpu-564bffdf6d-cm7pn"}**
2022-01-28T13:14:57.173Z        INFO    controller.provisioning Batched 1 pods in 1.000365205s  {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:14:57.181Z        INFO    controller.provisioning Computed packing of 1 node(s) for 1 pod(s) with instance type option(s) [g4dn.xlarge]    {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:14:57.181Z        DEBUG   controller.provisioning Discovered caBundle, length 1025        {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
**2022-01-28T13:14:57.475Z        ERROR   controller.provisioning Could not launch node, launching instances, with fleet error(s), UnfulfillableCapacity: Unable to fulfill capacity due to your request configuration. Please adjust your request and try again.  {"commit": "2346ed5", "provisioner": "provisioner-gpu"}**
2022-01-28T13:14:57.475Z        INFO    controller.provisioning Waiting for unschedulable pods  {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:15:03.476Z        INFO    controller.provisioning Batched 1 pods in 1.000083909s  {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:15:03.483Z        INFO    controller.provisioning Computed packing of 1 node(s) for 1 pod(s) with instance type option(s) [g4dn.xlarge]    {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:15:03.484Z        DEBUG   controller.provisioning Discovered caBundle, length 1025        {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
**2022-01-28T13:15:03.784Z        ERROR   controller.provisioning Could not launch node, launching instances, with fleet error(s), UnfulfillableCapacity: Unable to fulfill capacity due to your request configuration. Please adjust your request and try again.  {"commit": "2346ed5", "provisioner": "provisioner-gpu"}**
2022-01-28T13:15:03.784Z        INFO    controller.provisioning Waiting for unschedulable pods  {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:15:09.786Z        INFO    controller.provisioning Batched 1 pods in 1.000782308s  {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:15:09.792Z        INFO    controller.provisioning Computed packing of 1 node(s) for 1 pod(s) with instance type option(s) [g4dn.xlarge]    {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:15:09.793Z        DEBUG   controller.provisioning Discovered caBundle, length 1025        {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
**2022-01-28T13:15:10.153Z        ERROR   controller.provisioning Could not launch node, launching instances, with fleet error(s), UnfulfillableCapacity: Unable to fulfill capacity due to your request configuration. Please adjust your request and try again.  {"commit": "2346ed5", "provisioner": "provisioner-gpu"}**
2022-01-28T13:15:10.153Z        INFO    controller.provisioning Waiting for unschedulable pods  {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:15:16.155Z        INFO    controller.provisioning Batched 1 pods in 1.000985996s  {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:15:16.161Z        INFO    controller.provisioning Computed packing of 1 node(s) for 1 pod(s) with instance type option(s) [g4dn.xlarge]    {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:15:16.161Z        DEBUG   controller.provisioning Discovered caBundle, length 1025        {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
**2022-01-28T13:15:16.621Z        ERROR   controller.provisioning Could not launch node, launching instances, with fleet error(s), UnfulfillableCapacity: Unable to fulfill capacity due to your request configuration. Please adjust your request and try again.  {"commit": "2346ed5", "provisioner": "provisioner-gpu"}**
2022-01-28T13:15:16.621Z        INFO    controller.provisioning Waiting for unschedulable pods  {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:15:21.989Z        DEBUG   controller.provisioning Discovered EC2 instance types zonal offerings   {"commit": "2346ed5", "provisioner": "default"}
2022-01-28T13:15:22.623Z        INFO    controller.provisioning Batched 1 pods in 1.000719828s  {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:15:22.629Z        INFO    controller.provisioning Computed packing of 1 node(s) for 1 pod(s) with instance type option(s) [g4dn.xlarge]    {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:15:22.629Z        DEBUG   controller.provisioning Discovered caBundle, length 1025        {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:15:22.959Z        ERROR   controller.provisioning Could not launch node, launching instances, with fleet error(s), UnfulfillableCapacity: Unable to fulfill capacity due to your request configuration. Please adjust your request and try again.  {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:15:22.959Z        INFO    controller.provisioning Waiting for unschedulable pods  {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:15:28.960Z        INFO    controller.provisioning Batched 1 pods in 1.000566211s  {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:15:28.967Z        INFO    controller.provisioning Computed packing of 1 node(s) for 1 pod(s) with instance type option(s) [g4dn.xlarge]    {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:15:28.968Z        DEBUG   controller.provisioning Discovered caBundle, length 1025        {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:15:29.244Z        ERROR   controller.provisioning Could not launch node, launching instances, with fleet error(s), UnfulfillableCapacity: Unable to fulfill capacity due to your request configuration. Please adjust your request and try again.  {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:15:29.244Z        INFO    controller.provisioning Waiting for unschedulable pods  {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:15:31.205Z        DEBUG   controller.provisioning Discovered 363 EC2 instance types       {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:15:35.245Z        INFO    controller.provisioning Batched 1 pods in 1.000232858s  {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:15:35.251Z        INFO    controller.provisioning Computed packing of 1 node(s) for 1 pod(s) with instance type option(s) [g4dn.xlarge]    {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:15:35.252Z        DEBUG   controller.provisioning Discovered caBundle, length 1025        {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
**2022-01-28T13:15:36.057Z        ERROR   controller.provisioning Could not launch node, launching instances, with fleet error(s), UnfulfillableCapacity: Unable to fulfill capacity due to your request configuration. Please adjust your request and try again.  {"commit": "2346ed5", "provisioner": "provisioner-gpu"}**
2022-01-28T13:15:36.057Z        INFO    controller.provisioning Waiting for unschedulable pods  {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:15:42.059Z        INFO    controller.provisioning Batched 1 pods in 1.000938274s  {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:15:42.064Z        INFO    controller.provisioning Computed packing of 1 node(s) for 1 pod(s) with instance type option(s) [g4dn.xlarge]    {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:15:42.064Z        DEBUG   controller.provisioning Discovered caBundle, length 1025        {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
**2022-01-28T13:15:43.351Z        DEBUG   controller.provisioning InsufficientInstanceCapacity for offering { instanceType: g4dn.xlarge, zone: us-east-1c, capacityType: spot }, avoiding for 45s  {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:15:43.351Z        ERROR   controller.provisioning Could not launch node, launching instances, with fleet error(s), InsufficientInstanceCapacity: We currently do not have sufficient g4dn.xlarge capacity in the Availability Zone you requested (us-east-1c). Our system will be working on provisioning additional capacity. You can currently get g4dn.xlarge capacity by not specifying an Availability Zone in your request or choosing us-east-1a, us-east-1b, us-east-1d, us-east-1f.; UnfulfillableCapacity: Unable to fulfill capacity due to your request configuration. Please adjust your request and try again.  {"commit": "2346ed5", "provisioner": "provisioner-gpu"}**
2022-01-28T13:15:43.351Z        INFO    controller.provisioning Waiting for unschedulable pods  {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:15:49.352Z        INFO    controller.provisioning Batched 1 pods in 1.000570552s  {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:15:49.401Z        DEBUG   controller.provisioning Discovered subnets: [subnet-00d26d958f2e37222 (us-east-1a) subnet-09a7943d66a9d6a1b (us-east-1b) subnet-0ffe96b0ecd05ff71 (us-east-1c) subnet-03832a499b0326725 (us-east-1d)]    {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:15:49.407Z        INFO    controller.provisioning Computed packing of 1 node(s) for 1 pod(s) with instance type option(s) [g4dn.xlarge]    {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:15:49.448Z        DEBUG   controller.provisioning Discovered security groups: [sg-0aa637d62613334b8]      {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:15:49.453Z        DEBUG   controller.provisioning Discovered kubernetes version 1.20      {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:15:49.509Z        DEBUG   controller.provisioning Discovered ami ami-0d599dfae63ef9a11 for query /aws/service/eks/optimized-ami/1.20/amazon-linux-2-gpu/recommended/image_id       {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:15:49.509Z        DEBUG   controller.provisioning Discovered caBundle, length 1025        {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:15:49.548Z        DEBUG   controller.provisioning Discovered launch template Karpenter-eksworkshop-eksctl-18338213868441572111     {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
**2022-01-28T13:15:49.891Z        ERROR   controller.provisioning Could not launch node, launching instances, with fleet error(s), UnfulfillableCapacity: Unable to fulfill capacity due to your request configuration. Please adjust your request and try again.  {"commit": "2346ed5", "provisioner": "provisioner-gpu"}**
2022-01-28T13:15:49.891Z        INFO    controller.provisioning Waiting for unschedulable pods  {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:15:55.892Z        INFO    controller.provisioning Batched 1 pods in 1.000213014s  {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:15:55.900Z        INFO    controller.provisioning Computed packing of 1 node(s) for 1 pod(s) with instance type option(s) [g4dn.xlarge]    {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:15:55.900Z        DEBUG   controller.provisioning Discovered caBundle, length 1025        {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
**2022-01-28T13:15:56.221Z        ERROR   controller.provisioning Could not launch node, launching instances, with fleet error(s), UnfulfillableCapacity: Unable to fulfill capacity due to your request configuration. Please adjust your request and try again.  {"commit": "2346ed5", "provisioner": "provisioner-gpu"}**
2022-01-28T13:15:56.221Z        INFO    controller.provisioning Waiting for unschedulable pods  {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:16:02.223Z        INFO    controller.provisioning Batched 1 pods in 1.001010641s  {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:16:02.230Z        INFO    controller.provisioning Computed packing of 1 node(s) for 1 pod(s) with instance type option(s) [g4dn.xlarge]    {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:16:02.230Z        DEBUG   controller.provisioning Discovered caBundle, length 1025        {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
**2022-01-28T13:16:02.694Z        ERROR   controller.provisioning Could not launch node, launching instances, with fleet error(s), UnfulfillableCapacity: Unable to fulfill capacity due to your request configuration. Please adjust your request and try again.  {"commit": "2346ed5", "provisioner": "provisioner-gpu"}**

**Comment by ellistarn** [comment] 2022-01-28 17:50
First, Karpenter identifies that capacity is unavailable in us-east-1c and us-east-1d, and adds them to the unavailable cache for 45 seconds. 
```
2022-01-28T13:14:51.172Z DEBUG controller.provisioning InsufficientInstanceCapacity for offering { instanceType: g4dn.xlarge, zone: us-east-1c, capacityType: spot }, avoiding for 45s {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:14:51.172Z DEBUG controller.provisioning InsufficientInstanceCapacity for offering { instanceType: g4dn.xlarge, zone: us-east-1d, capacityType: spot }, avoiding for 45s {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:14:51.172Z ERROR controller.provisioning Could not launch node, launching instances, with fleet error(s), InsufficientInstanceCapacity: There is no Spot capacity available that matches your request.; InsufficientInstanceCapacity: We currently do not have sufficient g4dn.xlarge capacity in the Availability Zone you requested (us-east-1d). Our system will be working on provisioning additional capacity. You can currently get g4dn.xlarge capacity by not specifying an Availability Zone in your request or choosing us-east-1a, us-east-1b, us-east-1c, us-east-1f.; UnfulfillableCapacity: Unable to fulfill capacity due to your request configuration. Please adjust your request and try again. {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
```
Then, Karpenter relaxes the preferred scheduling rule after failing to schedule the pod, enabling on demand on the next retry
```
2022-01-28T13:14:56.173Z DEBUG controller.selection Relaxing soft constraints for default/inflate-gpu-564bffdf6d-cm7pn since it previously failed to schedule, removing: spec.affinity.nodeAffinity.preferredDuringSchedulingIgnoredDuringExecution[0]={"weight":1,"preference":{"matchExpressions":[{"key":"karpenter.sh/capacity-type","operator":"In","values":["spot"]}]}} {"commit": "2346ed5", "pod": "default/inflate-gpu-564bffdf6d-cm7pn"}
```

Then, Karpenter gets UnfulfillableCapacity for the on-demand request  
```
2022-01-28T13:14:57.475Z ERROR controller.provisioning Could not launch node, launching instances, with fleet error(s), UnfulfillableCapacity: Unable to fulfill capacity due to your request configuration. Please adjust your request and try again. {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
```

Notice that `InsufficientInstanceCapacity: There is no Spot capacity available that matches your request` is returned from spot unavailability, and is different from `UnfulfillableCapacity: Unable to fulfill capacity due to your request configuration` due to on demand unavailability.

**Comment by ellistarn** [comment] 2022-01-28 17:52
What's curious to me, is that it looks like you're flexible to zones, a,b,c,d, but the cache only tried c and d.

**Comment by ellistarn** [comment] 2022-01-28 18:05
Is it possible to increase flexibility to more instance types?

**Comment by ashwinikumar-sa** [comment] 2022-01-28 19:23
**> What's curious to me, is that it looks like you're flexible to zones, a,b,c,d, but the cache only tried c and d.**
Yes, am using 4 subnets in zones a,b,c,d (through subnetSelector in Provisioner)
2022-01-28T13:14:48.168Z DEBUG controller.provisioning Discovered subnets: [subnet-00d26d958f2e37222 (us-east-1a) subnet-09a7943d66a9d6a1b (us-east-1b) subnet-0ffe96b0ecd05ff71 (us-east-1c) subnet-03832a499b0326725 (us-east-1d)] {"commit": "2346ed5", "provisioner": "provisioner-gpu"}

**> Is that your full pod spec? Can you share additional log lines above the top that you linked?**
Yes, that's the full pod spec. I had provided log lines starting from the time when pod was launched. additional log lines before **2022-01-28T13:14:47.767Z.** are below.

2022-01-28T12:55:03.088Z	DEBUG	controller.provisioning	Discovered subnets: [subnet-00d26d958f2e37222 (us-east-1a) subnet-09a7943d66a9d6a1b (us-east-1b) subnet-0ffe96b0ecd05ff71 (us-east-1c) subnet-03832a499b0326725 (us-east-1d)]	{"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T12:55:20.384Z	DEBUG	controller.provisioning	Discovered EC2 instance types zonal offerings	{"commit": "2346ed5", "provisioner": "default"}
2022-01-28T12:55:27.688Z	DEBUG	controller.provisioning	Discovered 363 EC2 instance types	{"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:00:20.558Z	DEBUG	controller.provisioning	Discovered subnets: [subnet-00d26d958f2e37222 (us-east-1a) subnet-09a7943d66a9d6a1b (us-east-1b) subnet-0ffe96b0ecd05ff71 (us-east-1c) subnet-03832a499b0326725 (us-east-1d)]	{"commit": "2346ed5", "provisioner": "default"}
2022-01-28T13:00:20.753Z	DEBUG	controller.provisioning	Discovered EC2 instance types zonal offerings	{"commit": "2346ed5", "provisioner": "default"}
2022-01-28T13:00:28.638Z	DEBUG	controller.provisioning	Discovered 363 EC2 instance types	{"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:05:21.048Z	DEBUG	controller.provisioning	Discovered subnets: [subnet-00d26d958f2e37222 (us-east-1a) subnet-09a7943d66a9d6a1b (us-east-1b) subnet-0ffe96b0ecd05ff71 (us-east-1c) subnet-03832a499b0326725 (us-east-1d)]	{"commit": "2346ed5", "provisioner": "default"}
2022-01-28T13:05:21.233Z	DEBUG	controller.provisioning	Discovered EC2 instance types zonal offerings	{"commit": "2346ed5", "provisioner": "default"}
2022-01-28T13:05:29.437Z	DEBUG	controller.provisioning	Discovered 363 EC2 instance types	{"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:10:21.568Z	DEBUG	controller.provisioning	Discovered subnets: [subnet-00d26d958f2e37222 (us-east-1a) subnet-09a7943d66a9d6a1b (us-east-1b) subnet-0ffe96b0ecd05ff71 (us-east-1c) subnet-03832a499b0326725 (us-east-1d)]	{"commit": "2346ed5", "provisioner": "default"}
2022-01-28T13:10:21.788Z	DEBUG	controller.provisioning	Discovered EC2 instance types zonal offerings	{"commit": "2346ed5", "provisioner": "default"}
2022-01-28T13:10:30.323Z	DEBUG	controller.provisioning	Discovered 363 EC2 instance types	{"commit": "2346ed5", "provisioner": "provisioner-gpu"}
**2022-01-28T13:14:47.767Z**	INFO	controller.provisioning	Batched 1 pods in 1.00028814s	{"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T13:14:48.168Z	DEBUG	controller.provisioning	Discovered subnets: [subnet-00d26d958f2e37222 (us-east-1a) subnet-09a7943d66a9d6a1b (us-east-1b) subnet-0ffe96b0ecd05ff71 (us-east-1c) subnet-03832a499b0326725 (us-east-1d)]	{"commit": "2346ed5", "provisioner": "provisioner-gpu"}

**Comment by ashwinikumar-sa** [comment] 2022-01-28 19:58
**> Is it possible to increase flexibility to more instance types?**
Increased instance pools flexibility in my provisioner with 3 sizes of g4dn - ["g4dn.xlarge","g4dn.2xlarge","g4dn.4xlarge"] Now, Karpenter found and launched a g4dn.4xlarge on Spot. Looking at logs below, looks like it first tried g4dn.xlarge in all zones a,b,c,d and then g4dn.2xlarge in 2 zones (b and c) and then tried g4dn.4xlarge in zone [c] and found Spot capacity there and launched it. could not simulate switching to OD in this case. 

2022-01-28T19:26:31.746Z        DEBUG   controller.provisioning Discovered 363 EC2 instance types       {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T19:26:31.789Z        DEBUG   controller.provisioning Discovered subnets: [subnet-00d26d958f2e37222 (us-east-1a) subnet-09a7943d66a9d6a1b (us-east-1b) subnet-0ffe96b0ecd05ff71 (us-east-1c) subnet-03832a499b0326725 (us-east-1d)]    {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T19:26:48.863Z        INFO    controller.provisioning Batched 1 pods in 1.000881597s  {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T19:26:48.870Z        INFO    controller.provisioning Computed packing of 1 node(s) for 1 pod(s) with instance type option(s) [g4dn.xlarge g4dn.2xlarge g4dn.4xlarge]  {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T19:26:49.090Z        DEBUG   controller.provisioning Discovered security groups: [sg-0aa637d62613334b8]      {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T19:26:49.093Z        DEBUG   controller.provisioning Discovered kubernetes version 1.20      {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T19:26:49.162Z        DEBUG   controller.provisioning Discovered ami ami-0d599dfae63ef9a11 for query /aws/service/eks/optimized-ami/1.20/amazon-linux-2-gpu/recommended/image_id       {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T19:26:49.162Z        DEBUG   controller.provisioning Discovered caBundle, length 1025        {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T19:26:49.205Z        DEBUG   controller.provisioning Discovered launch template Karpenter-eksworkshop-eksctl-18338213868441572111     {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T19:26:57.848Z        DEBUG   controller.provisioning InsufficientInstanceCapacity for offering { instanceType: g4dn.xlarge, zone: us-east-1c, capacityType: spot }, avoiding for 45s  {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T19:26:57.848Z        DEBUG   controller.provisioning InsufficientInstanceCapacity for offering { instanceType: g4dn.xlarge, zone: us-east-1b, capacityType: spot }, avoiding for 45s  {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T19:26:57.848Z        DEBUG   controller.provisioning InsufficientInstanceCapacity for offering { instanceType: g4dn.xlarge, zone: us-east-1d, capacityType: spot }, avoiding for 45s  {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T19:26:57.848Z        DEBUG   controller.provisioning InsufficientInstanceCapacity for offering { instanceType: g4dn.xlarge, zone: us-east-1a, capacityType: spot }, avoiding for 45s  {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T19:26:57.848Z        DEBUG   controller.provisioning InsufficientInstanceCapacity for offering { instanceType: g4dn.2xlarge, zone: us-east-1b, capacityType: spot }, avoiding for 45s {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T19:26:57.848Z        DEBUG   controller.provisioning InsufficientInstanceCapacity for offering { instanceType: g4dn.2xlarge, zone: us-east-1c, capacityType: spot }, avoiding for 45s {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T19:26:59.168Z        INFO    controller.provisioning Launched instance: i-0bb216510a050dc19, hostname: ip-192-168-220-48.ec2.internal, type: g4dn.4xlarge, zone: us-east-1c, capacityType: spot       {"commit": "2346ed5", "provisioner": "provisioner-gpu"}
2022-01-28T19:26:59.188Z        INFO    controller.provisioning Bound 1 pod(s) to node ip-192-168-220-48.ec2.internal   {"commit": "2346ed5", "provisioner": "provisioner-gpu"}

**Comment by ellistarn** [comment] 2022-01-31 17:55
Given the discussion so far, I think everything is working as intended. Karpenter is relaxing preferential affinity when pods cannot be scheduled, and will prioritize spot if both spot and on demand are allowed.

**Comment by ellistarn** [comment] 2022-02-02 20:37
Closing as I believe we've verified all behavior is working as expected.

**Closed** 2022-02-02 22:10 UTC
Labels: bug, burning

**Comment by ermiaqasemi** [comment] 2022-07-20 17:27
Well, in the scenario that Karpenter can not lunch the significant instances, should not try to lunch other instances that we provided in the Provisioner like auto scaler? 
So in my case, I get the below error from Karpenter that was not able to lunch c5n.18xlarge spot instance, it was not able failover to on-demand and what I expected is that trying to lunch c5n.4xlarge or the other instances that I provided. 

```
2022-07-20T17:11:59.753Z	ERROR	controller.provisioning	Could not launch node, launching instances, with fleet error(s), UnfulfillableCapacity: Unable to fulfill capacity due to your request configuration. Please adjust your request and try again.	{"commit": "78d3031", "provisioner": "worker"}
```

```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
spec:
  labels:
    eks.example.so/node-role: worker
  limits:
    resources:
      cpu: 1k
  provider:
    apiVersion: extensions.karpenter.sh/v1alpha1
    kind: AWS
    securityGroupSelector:
      karpenter.sh/discovery: development-us-east-1-neo
    subnetSelector:
      karpenter.sh/discovery: development-us-east-1-neo
    tags:
      karpenter.sh/discovery: development-us-east-1-neo
  requirements:
    - key: node.kubernetes.io/instance-type
      operator: In
      values:
        - c5n.4xlarge
        - c5n.9xlarge
        - c5n.18xlarge
    - key: karpenter.sh/capacity-type
      operator: In
      values:
        - on-demand
        - spot
    - key: kubernetes.io/arch
      operator: In
      values:
        - amd64
  ttlSecondsAfterEmpty: 120
  ttlSecondsUntilExpired: 2592000

```

**Comment by ellistarn** [comment] 2022-07-21 03:58
Can you show some more logs? It looks like you may be running into this https://github.com/aws/karpenter/pull/2002.

**Comment by bwagner5** [comment] 2022-07-21 14:14
@ermiaqasemi This is fixed in newer versions of Karpenter. Try the latest v0.13.2 and it should work as you expect.
