### ISSUE TITLE
Karpenter is not deleting instances after scale down of Pods

### ISSUE THREAD

**Issue by premsgr6** [aws/karpenter#4429] opened 2023-08-14 11:30 UTC
### Description

**Observed Behavior**: when user scale down the numer of pods then one pod is running on new node and drain and cordon of new node with just one pod is not happening.

**Expected Behavior**: when some workload on new is less or only one pod is running on node then it should move that pod to another node which can handle that much of load and should remove the new node which had only single pod running.

**Reproduction Steps** (Please include YAML):

**Versions**:
- Chart Version: v0.29.0
- Kubernetes Version (`kubectl version`): v1.27.1-eks

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment] 2023-08-14 12:43
Can you provide:
- pod specs
- output of `kubectl describe node the-node-name` for the involved nodes
- the Karpenter controller logs

**Comment by premsgr6** [comment] 2023-08-15 11:22
> * Karpenter c

please find below requried information:
k describe pod/karpenter-65d5c5c786-b45kw
Name:                 karpenter-65d5c5c786-b45kw
Namespace:            karpenter
Priority:             2000000000
Priority Class Name:  system-cluster-critical
Service Account:      karpenter
Node:                 ip-10-xxx-5-68.eu-test-1.compute.internal/10.xxx.5.68
Start Time:           Mon, 14 Aug 2023 13:19:31 +0100
Labels:               app.kubernetes.io/instance=karpenter
                      app.kubernetes.io/name=karpenter
                      pod-template-hash=65d5c5c786
Annotations:          checksum/settings: 4422487afdf0289837cda9bcedcxxxa5b07a301212918ba157cd5475d0498bb3
                      kubectl.kubernetes.io/restartedAt: 2023-08-11T16:38:33+01:00
Status:               Running
IP:                   10.xxx.5.56
IPs:
  IP:           10.xxx.5.56
Controlled By:  ReplicaSet/karpenter-65d5c5c786
Containers:
  controller:
    Container ID:   containerd://e4394f1997ef787c813b53c91aca760cac40afde926e8b59b13e0ae9d96be8c5
    Image:          public.ecr.aws/karpenter/controller:v0.29.0@sha256:3009f10487d9338f77c325adee3c208513cd06c7f191653327ef3a44006bf9c8
    Image ID:       public.ecr.aws/karpenter/controller@sha256:3009f10487d9338f77c325adee3c208513cd06c7f191653327ef3a44006bf9c8
    Ports:          8000/TCP, 8081/TCP, 8443/TCP
    Host Ports:     0/TCP, 0/TCP, 0/TCP
    State:          Running
      Started:      Mon, 14 Aug 2023 13:19:47 +0100
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:http/healthz delay=30s timeout=30s period=10s #success=1 #failure=3
    Readiness:      http-get http://:http/readyz delay=0s timeout=30s period=10s #success=1 #failure=3
    Environment:
      KUBERNETES_MIN_VERSION:       1.19.0-0
      KARPENTER_SERVICE:            karpenter
      WEBHOOK_PORT:                 8443
      METRICS_PORT:                 8000
      HEALTH_PROBE_PORT:            8081
      SYSTEM_NAMESPACE:             karpenter (v1:metadata.namespace)
      MEMORY_LIMIT:                 node allocatable (limits.memory)
      AWS_STS_REGIONAL_ENDPOINTS:   regional
      AWS_DEFAULT_REGION:           eu-test-1
      AWS_REGION:                   eu-test-1
      AWS_ROLE_ARN:                 arn:aws:iam::xxxxxxxxxxxx:role/KarpenterIRSA-eks-202308xxx5
      AWS_WEB_IDENTITY_TOKEN_FILE:  /var/run/secrets/eks.amazonaws.com/serviceaccount/token
    Mounts:
      /var/run/secrets/eks.amazonaws.com/serviceaccount from aws-iam-token (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-xjtth (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  aws-iam-token:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  86400
  kube-api-access-xjtth:
    Type:                     Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:   3607
    ConfigMapName:            kube-root-ca.crt
    ConfigMapOptional:        <nil>
    DownwardAPI:              true
QoS Class:                    BestEffort
Node-Selectors:               kubernetes.io/os=linux
Tolerations:                  CriticalAddonsOnly op=Exists
                              node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                              node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Topology Spread Constraints:  topology.kubernetes.io/zone:ScheduleAnyway when max skew 1 is exceeded for selector app.kubernetes.io/instance=karpenter,app.kubernetes.io/name=karpenter
Events:                       <none>

------------------------------------------------------------------------------

k describe no ip-10-xxx-5-68.eu-test-1.compute.internal
Name:               ip-10-xxx-5-68.eu-test-1.compute.internal
Roles:              <none>
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=t3a.xlarge
                    beta.kubernetes.io/os=linux
                    failure-domain.beta.kubernetes.io/region=eu-test-1
                    failure-domain.beta.kubernetes.io/zone=eu-test-1c
                    k8s.io/cloud-provider-aws=797019a6c020d05c9dc3241f0b57b7a1
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=ip-10-xxx-5-68.eu-test-1.compute.internal
                    kubernetes.io/os=linux
                    node.kubernetes.io/instance-type=t3a.xlarge
                    topology.ebs.csi.aws.com/zone=eu-test-1c
                    topology.kubernetes.io/region=eu-test-1
                    topology.kubernetes.io/zone=eu-test-1c
Annotations:        alpha.kubernetes.io/provided-node-ip: 10.xxx.5.68
                    csi.volume.kubernetes.io/nodeid: {"ebs.csi.aws.com":"i-2f85b1ac08db6"}
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Mon, 14 Aug 2023 13:16:30 +0100
Taints:             <none>
Unschedulable:      false
Lease:
  HolderIdentity:  ip-10-xxx-5-68.eu-test-1.compute.internal
  AcquireTime:     <unset>
  RenewTime:       Tue, 15 Aug 2023 12:12:17 +0100
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  MemoryPressure   False   Tue, 15 Aug 2023 12:07:54 +0100   Mon, 14 Aug 2023 13:16:29 +0100   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Tue, 15 Aug 2023 12:07:54 +0100   Mon, 14 Aug 2023 13:16:29 +0100   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Tue, 15 Aug 2023 12:07:54 +0100   Mon, 14 Aug 2023 13:16:29 +0100   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            True    Tue, 15 Aug 2023 12:07:54 +0100   Mon, 14 Aug 2023 13:16:43 +0100   KubeletReady                 kubelet is posting ready status
Addresses:
  InternalIP:   10.xxx.5.68
  InternalDNS:  ip-10-xxx-5-68.eu-test-1.compute.internal
  Hostname:     ip-10-xxx-5-68.eu-test-1.compute.internal
Capacity:
  cpu:                4
  ephemeral-storage:  20959212Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             16226788Ki
  pods:               58
Allocatable:
  cpu:                3920m
  ephemeral-storage:  18242267924
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             15209956Ki
  pods:               58
System Info:
  Machine ID:                 ec2f6771efba25bc75ef116e82262f38
  System UUID:                ec2f6771-efba-25bc-75ef-116e82262f38
  Boot ID:                    3023ac2c-b06b-4c0d-a1be-eda37c860e05
  Kernel Version:             5.10.178-162.673.amzn2.x86_64
  OS Image:                   Amazon Linux 2
  Operating System:           linux
  Architecture:               amd64
  Container Runtime Version:  containerd://1.6.19
  Kubelet Version:            v1.27.1-eks-2f008fe
  Kube-Proxy Version:         v1.27.1-eks-2f008fe
ProviderID:                   aws:///eu-test-1c/i-2f85b1ac08db6
Non-terminated Pods:          (29 in total)
  Namespace                   Name                                               CPU Requests  CPU Limits  Memory Requests  Memory Limits  Age
  ---------                   ----                                               ------------  ----------  ---------------  -------------  ---
  cert-manager                cert-manager-964c76795-v86qr                       0 (0%)        0 (0%)      0 (0%)           0 (0%)         22h
  cert-manager                cert-manager-cainjector-b86ffd6cd-2z4jq            0 (0%)        0 (0%)      0 (0%)           0 (0%)         22h
  cert-manager                cert-manager-webhook-5f85f5b7c9-jp89c              0 (0%)        0 (0%)      0 (0%)           0 (0%)         22h
  default                     details-v1-7b67fd5877-pzzff                        0 (0%)        0 (0%)      0 (0%)           0 (0%)         22h
  default                     productpage-v1-7cc98bb9c5-wfbdl                    0 (0%)        0 (0%)      0 (0%)           0 (0%)         22h
  default                     ratings-v1-5f77f7f669-q7hvq                        0 (0%)        0 (0%)      0 (0%)           0 (0%)         22h
  default                     reviews-v1-56fd4696d6-z69p6                        0 (0%)        0 (0%)      0 (0%)           0 (0%)         22h
  default                     reviews-v2-77989b4fb8-q8k2k                        0 (0%)        0 (0%)      0 (0%)           0 (0%)         22h
  default                     reviews-v3-84d5f9d978-jgrms                        0 (0%)        0 (0%)      0 (0%)           0 (0%)         22h
  echo                        echo-v1-555d75d654-gwn25                           0 (0%)        0 (0%)      0 (0%)           0 (0%)         22h
  fluentbit                   aws-for-fluent-bit-5h8m8                           50m (1%)      0 (0%)      50Mi (0%)        250Mi (1%)     22h
  gloo-system                 discovery-57d95494f9-7hfbm                         0 (0%)        0 (0%)      0 (0%)           0 (0%)         22h
  gloo-system                 gateway-proxy-564df5b464-6xb6w                     0 (0%)        0 (0%)      0 (0%)           0 (0%)         22h
  gloo-system                 gloo-977789d87-9vrjt                               500m (12%)    0 (0%)      256Mi (1%)       0 (0%)         22h
  httpbin                     httpbin-698cc5f69-bmgck                            0 (0%)        0 (0%)      0 (0%)           0 (0%)         22h
  karpenter                   karpenter-65d5c5c786-b45kw                         0 (0%)        0 (0%)      0 (0%)           0 (0%)         22h
  kube-system                 aws-load-balancer-controller-546f54b844-7w2h5      0 (0%)        0 (0%)      0 (0%)           0 (0%)         22h
  kube-system                 aws-load-balancer-controller-546f54b844-hrd4x      0 (0%)        0 (0%)      0 (0%)           0 (0%)         22h
  kube-system                 aws-node-m6mr2                                     25m (0%)      0 (0%)      0 (0%)           0 (0%)         22h
  kube-system                 coredns-6b4f66d5fb-gf7vv                           100m (2%)     0 (0%)      70Mi (0%)        170Mi (1%)     22h
  kube-system                 coredns-6b4f66d5fb-p5nwv                           100m (2%)     0 (0%)      70Mi (0%)        170Mi (1%)     22h
  kube-system                 ebs-csi-controller-5d4fdfffc7-7mzwn                60m (1%)      600m (15%)  240Mi (1%)       1536Mi (10%)   22h
  kube-system                 ebs-csi-controller-5d4fdfffc7-h9ndc                60m (1%)      600m (15%)  240Mi (1%)       1536Mi (10%)   22h
  kube-system                 ebs-csi-node-jlzzp                                 30m (0%)      300m (7%)   120Mi (0%)       768Mi (5%)     22h
  kube-system                 external-dns-79c76c6fbc-qs6rg                      10m (0%)      50m (1%)    50Mi (0%)        50Mi (0%)      22h
  kube-system                 kube-proxy-l2vrw                                   100m (2%)     0 (0%)      0 (0%)           0 (0%)         22h
  metrics-server              metrics-server-6d699889f4-mcm79                    0 (0%)        0 (0%)      0 (0%)           0 (0%)         22h
  nginx-ingress               nginx-ingress-nginx-controller-6667cc9b8b-84fx4    100m (2%)     0 (0%)      90Mi (0%)        0 (0%)         22h
  nginx-ingress               nginx-ingress-nginx-controller-6667cc9b8b-cklg5    100m (2%)     0 (0%)      90Mi (0%)        0 (0%)         22h
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests     Limits
  --------           --------     ------
  cpu                1235m (31%)  1550m (39%)
  memory             1276Mi (8%)  4480Mi (30%)
  ephemeral-storage  0 (0%)       0 (0%)
  hugepages-1Gi      0 (0%)       0 (0%)
  hugepages-2Mi      0 (0%)       0 (0%)
Events:              <none>

----------------------------------------------------------------------------------
controller pod logs:
2023-08-15T10:33:39.625Z        DEBUG   controller.deprovisioning       discovered instance types       {"commit": "61cc8f7-dirty", "count": 670}
2023-08-15T10:38:41.489Z        DEBUG   controller.deprovisioning       discovered instance types       {"commit": "61cc8f7-dirty", "count": 672}
2023-08-15T10:43:43.468Z        DEBUG   controller.deprovisioning       discovered instance types       {"commit": "61cc8f7-dirty", "count": 671}
2023-08-15T10:48:45.492Z        DEBUG   controller.deprovisioning       discovered instance types       {"commit": "61cc8f7-dirty", "count": 680}
2023-08-15T11:09:36.003Z        INFO    controller.provisioner  found provisionable pod(s)      {"commit": "61cc8f7-dirty", "pods": 21}
2023-08-15T11:09:36.003Z        INFO    controller.provisioner  computed new machine(s) to fit pod(s)   {"commit": "61cc8f7-dirty", "machines": 1, "pods": 21}
2023-08-15T11:09:36.098Z        INFO    controller.provisioner  created machine {"commit": "61cc8f7-dirty", "provisioner": "default", "requests": {"cpu":"205m","memory":"170Mi","pods":"25"}, "instance-types": "c3.large, c3.xlarge, c4.large, c4.xlarge, c5.2xlarge and 95 other(s)"}
2023-08-15T11:09:36.348Z        DEBUG   controller.machine.lifecycle    discovered subnets      {"commit": "61cc8f7-dirty", "machine": "default-4ccsn", "provisioner": "default", "subnets": ["subnet-0b41afc07635 (eu-test-1c)", "subnet-f78bd967ff2 (eu-test-1b)", "subnet-5a11d59357 (eu-test-1a)", "subnet-09452b2a5f93 (eu-test-1b)", "subnet-55039d28900 (eu-test-1a)", "subnet-0d29b178ffc1 (eu-test-1c)"]}
2023-08-15T11:09:37.027Z        DEBUG   controller.machine.lifecycle    created launch template {"commit": "61cc8f7-dirty", "machine": "default-4ccsn", "provisioner": "default", "launch-template-name": "karpenter.k8s.aws/17079xxx166853205527", "id": "lt-0bfcffbed50f73c21"}
2023-08-15T11:09:37.222Z        DEBUG   controller.machine.lifecycle    created launch template {"commit": "61cc8f7-dirty", "machine": "default-4ccsn", "provisioner": "default", "launch-template-name": "karpenter.k8s.aws/16272564820493801953", "id": "lt-0488467989a81c729"}
2023-08-15T11:09:39.359Z        INFO    controller.machine.lifecycle    launched machine        {"commit": "61cc8f7-dirty", "machine": "default-4ccsn", "provisioner": "default", "provider-id": "aws:///eu-test-1a/i-9a2ccaced847", "instance-type": "c5.large", "zone": "eu-test-1a", "capacity-type": "spot", "allocatable": {"cpu":"1930m","ephemeral-storage":"17Gi","memory":"3114Mi","pods":"29"}}
2023-08-15T11:10:03.031Z        DEBUG   controller.machine.lifecycle    registered machine      {"commit": "61cc8f7-dirty", "machine": "default-4ccsn", "provisioner": "default", "provider-id": "aws:///eu-test-1a/i-9a2ccaced847", "node": "ip-10-xxx-3-119.eu-test-1.compute.internal"}
2023-08-15T11:10:15.465Z        DEBUG   controller.machine.lifecycle    initialized machine     {"commit": "61cc8f7-dirty", "machine": "default-4ccsn", "provisioner": "default", "provider-id": "aws:///eu-test-1a/i-9a2ccaced847", "node": "ip-10-xxx-3-119.eu-test-1.compute.internal"}
2023-08-15T11:13:03.513Z        DEBUG   controller.awsnodetemplate      discovered subnets      {"commit": "61cc8f7-dirty", "awsnodetemplate": "default", "subnets": ["subnet-0b41afc07635 (eu-test-1c)", "subnet-f78bd967ff2 (eu-test-1b)", "subnet-5a11d59357 (eu-test-1a)", "subnet-09452b2a5f93 (eu-test-1b)", "subnet-55039d28900 (eu-test-1a)", "subnet-0d29b178ffc1 (eu-test-1c)"]}
2023-08-15T11:19:50.684Z        DEBUG   controller      deleted launch template {"commit": "61cc8f7-dirty", "id": "lt-0bfcffbed50f73c21", "name": "karpenter.k8s.aws/17079111166853205527"}
2023-08-15T11:19:50.782Z        DEBUG   controller      deleted launch template {"commit": "61cc8f7-dirty", "id": "lt-0488467989a81c729", "name": "karpenter.k8s.aws/16272564820493801953"}

**Comment by premsgr6** [comment] 2023-08-16 11:03
seems node was terminated by spot instance termination policy after 7 hours, below are the logs:
k get provisioners -o yaml
apiVersion: v1
items:
- apiVersion: karpenter.sh/v1alpha5
  kind: Provisioner
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"karpenter.sh/v1alpha5","kind":"Provisioner","metadata":{"annotations":{},"name":"default"},"spec":{"limits":{"resources":{"cpu":1000}},"providerRef":{"name":"default"},"requirements":[{"key":"karpenter.sh/capacity-type","operator":"In","values":["spot"]}],"ttlSecondsAfterEmpty":30}}
    creationTimestamp: "2023-08-11T15:16:57Z"
    generation: 1
    name: default
    resourceVersion: "43296334"
    uid: 5f44f202-591e-481a-8303-869749b342fe
  spec:
    limits:
      resources:
        cpu: 1k
    providerRef:
      name: default
    requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values:
      - spot
    - key: kubernetes.io/os
      operator: In
      values:
      - linux
    - key: kubernetes.io/arch
      operator: In
      values:
      - amd64
    - key: karpenter.k8s.aws/instance-category
      operator: In
      values:
      - c
      - m
      - r
    - key: karpenter.k8s.aws/instance-generation
      operator: Gt
      values:
      - "2"
    ttlSecondsAfterEmpty: 30
  status: {}
kind: List
metadata:
  resourceVersion: ""
  
  --------
  kubectl get awsnodetemplates -o yaml
apiVersion: v1
items:
- apiVersion: karpenter.k8s.aws/v1alpha1
  kind: AWSNodeTemplate
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"karpenter.k8s.aws/v1alpha1","kind":"AWSNodeTemplate","metadata":{"annotations":{},"name":"default"},"spec":{"securityGroupSelector":{"kubernetes.io/cluster/eks-test":"owned"},"subnetSelector":{"kubernetes.io/cluster/eks-test":"shared"},"tags":{"karpenter.sh/discovery":"eks-test"}}}
    creationTimestamp: "2023-08-11T15:23:25Z"
    generation: 1
    name: default
    resourceVersion: "43567879"
    uid: 43ecaeee-2222-4be1-a27f-88374fd2425b
  spec:
    securityGroupSelector:
      kubernetes.io/cluster/eks-test: owned
    subnetSelector:
      kubernetes.io/cluster/eks-test: shared
    tags:
      karpenter.sh/discovery: eks-test
kind: List
metadata:
  resourceVersion: ""

**Comment by ckhelifi** [comment] 2023-08-17 14:52
@premsgr6 i think you do not have set any of `.spec.consolidation.enabled` or `.spec.ttlSecondsAfterEmpty` in your provisioner spec, [see this documentation](https://karpenter.sh/docs/concepts/deprovisioning/#automated-methods)

`Automated deprovisioning is configured through the ProvisionerSpec .ttlSecondsAfterEmpty, .ttlSecondsUntilExpired and .consolidation.enabled fields. If these are not configured, Karpenter will not set default values for them and will not terminate nodes for that purpose.`

**Comment by premsgr6** [comment] 2023-08-17 17:01
> @premsgr6 i think you do not have set any of `.spec.consolidation.enabled` or `.spec.ttlSecondsAfterEmpty` in your provisioner spec, [see this documentation](https://karpenter.sh/docs/concepts/deprovisioning/#automated-methods)
> 
> `Automated deprovisioning is configured through the ProvisionerSpec .ttlSecondsAfterEmpty, .ttlSecondsUntilExpired and .consolidation.enabled fields. If these are not configured, Karpenter will not set default values for them and will not terminate nodes for that purpose.`

.ttlSecondsAfterEmpty is configured for default provisioner:
![image](https://github.com/aws/karpenter/assets/46933846/d41fbe28-ef75-4ebf-8ec7-c9d6ec841a15)

**Comment by bwagner5** [comment] 2023-08-21 19:31
Is the provisioner you pasted above a different one? Because it looks like that one does not have ttlSsecondsAfterEmpty? Or did it just get dropped from the copy/paste?

**Comment by bwagner5** [comment] 2023-08-21 19:45
`ttlSecondsAfterEmpty` will only terminate the node if there are 0 pods running on the node (other than daemonsets). Do you know if the only pod running on the node was a daemonset or not?  

Are you able to reproduce this issue?

**Comment by architectaj** [comment] 2023-08-22 09:01
I am also facing similar kind of issue, is there a way to move/migrate least load on new node to existing node and remove the new node. e.g. if existing nodes are capable to run enough load  while the karpenter provisioned new node has only one pod left apart from deamonsets, is it possible for karpenter to move that one pod to existing nodes and remove the karpenter provisioned node.

**Comment by jonathan-innis** [comment] 2023-08-29 20:44
Tracking through this issue, it seems like consolidation wasn't enabled in the Provisioner, which would explain why the node wasn't deprovisioning when the node was _almost_ empty but wasn't completely empty. I'm going to close this since it looks like the remediation for the behavior is to enable consolidation.

**Closed by jonathan-innis** 2023-08-29 20:44 UTC
Labels: question
