### ISSUE TITLE
Report Events on Pods that Karpenter is making decisions for

### ISSUE THREAD

**Issue by diranged** [aws/karpenter#1894] opened 2022-06-03 16:56 UTC
**Tell us about your request**

The `cluster-autoscaler` reports back to application owners about how and why Pods were or were not schedulable for hardware. I would like to see Karpenter write out events for each Pod that it's making decisions on... these events would be incredibly useful for application owners, as well as administrators. I could imagine events like:

* `Launched ip-10-10-10-10.ec2.internal, Pod scheduled to host'
* `No provisioners match Pod hardware requirements, not launching any new hardware`
* `Existing capacity exists for Pod (nodes ip-10-10-10-10, ip-10-11-10-10, ...), letting kube-scheduler handle scheduling`
* `Scheduling pod on existing capacity (node ip-10-10-10-10...)`

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

Scanning logs is useful for cluster administrators ... but when a developer launches a Pod and cannot get hardware, we want them to be able to fish for themselves and find the answer to what went wrong. Pod events seem like the natural place to put these kinds of events, as we can directly pass information to the end-user.

**Are you currently working around this issue?**
We're not yet solving this... :/

**Additional context**
This is a wish-list item, but it applies to PRs like https://github.com/aws/karpenter/issues/1887 and https://github.com/aws/karpenter/issues/1888.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment] 2022-06-03 18:24
I agree :) Closing as a duplicate of #1584  Feel free to add any details that are missing there.

**Closed by tzneal** 2022-06-03 18:24 UTC
Labels: feature

**Comment by diranged** [comment] 2022-06-03 18:33
Ah, thank you.. sorry I missed that!
