### ISSUE TITLE
Karpenter never creates nodes, no errors in logs

### ISSUE THREAD

**Issue by henrikuittinen** [aws/karpenter#5165] opened 2023-11-26 11:21 UTC
For some unknown reason Karpenter never creates new nodes, no matter how big I scale my deployments. There are no errors in logs, only looping nodeclaim creation and destruction:

```
{"level":"INFO","time":"2023-11-26T11:09:15.704Z","logger":"controller.provisioner","message":"found provisionable pod(s)","commit":"1072d3b","pods":"sdfadsa/sdfadsa-deployment-758b677c6c-qrsrc, sdfadsa/sdfadsa-deployment-758b677c6c-pmcq8, sdfadsa/sdfadsa-deployment-758b677c6c-4cqjh, werws/werws-deployment-85d75b75cd-rzq2m, werws/werws-deployment-85d75b75cd-z698s and 5 other(s)","duration":"26.498365ms"}
{"level":"INFO","time":"2023-11-26T11:09:15.704Z","logger":"controller.provisioner","message":"computed new nodeclaim(s) to fit pod(s)","commit":"1072d3b","nodeclaims":1,"pods":10}
{"level":"INFO","time":"2023-11-26T11:09:15.735Z","logger":"controller.provisioner","message":"created nodeclaim","commit":"1072d3b","nodepool":"default","nodeclaim":"default-pmmb4","requests":{"cpu":"4350m","memory":"11626Mi","pods":"14"},"instance-types":"c5.2xlarge, c5.4xlarge, c5.9xlarge, c5a.2xlarge, c5a.4xlarge and 95 other(s)"}
{"level":"DEBUG","time":"2023-11-26T11:09:15.960Z","logger":"controller.nodeclaim.lifecycle","message":"created launch template","commit":"1072d3b","nodeclaim":"default-pmmb4","nodepool":"default","launch-template-name":"karpenter.k8s.aws/11179330346297813","id":"lt-0e5a6196ade459879"}
{"level":"DEBUG","time":"2023-11-26T11:09:16.147Z","logger":"controller.nodeclaim.lifecycle","message":"created launch template","commit":"1072d3b","nodeclaim":"default-pmmb4","nodepool":"default","launch-template-name":"karpenter.k8s.aws/14482476379175885742","id":"lt-013bf64ad50be125a"}
{"level":"DEBUG","time":"2023-11-26T11:09:16.342Z","logger":"controller.nodeclaim.lifecycle","message":"created launch template","commit":"1072d3b","nodeclaim":"default-pmmb4","nodepool":"default","launch-template-name":"karpenter.k8s.aws/5115586301854157719","id":"lt-0644ea33e46147e3c"}
{"level":"DEBUG","time":"2023-11-26T11:09:16.509Z","logger":"controller.nodeclaim.lifecycle","message":"created launch template","commit":"1072d3b","nodeclaim":"default-pmmb4","nodepool":"default","launch-template-name":"karpenter.k8s.aws/12462910484757937866","id":"lt-0822fc21eedcc9f84"}
{"level":"INFO","time":"2023-11-26T11:09:18.940Z","logger":"controller.nodeclaim.lifecycle","message":"launched nodeclaim","commit":"1072d3b","nodeclaim":"default-pmmb4","nodepool":"default","provider-id":"aws:///eu-north-1c/a-1233315555","instance-type":"t4g.2xlarge","zone":"eu-north-1c","capacity-type":"on-demand","allocatable":{"cpu":"7910m","ephemeral-storage":"17Gi","memory":"29258Mi","pods":"58"}}
{"level":"DEBUG","time":"2023-11-26T11:09:24.888Z","logger":"controller.disruption","message":"discovered subnets","commit":"1072d3b","subnets":["subnet-3209af4299cda (eu-north-1a)","subnet-9823989898abb (eu-north-1c)","subnet-9872344accaa223 (eu-north-1b)"]}
{"level":"DEBUG","time":"2023-11-26T11:10:25.044Z","logger":"controller.disruption","message":"discovered subnets","commit":"1072d3b","subnets":["subnet-3209af4299cda (eu-north-1a)","subnet-9823989898abb (eu-north-1c)","subnet-9872344accaa223 (eu-north-1b)"]}
{"level":"DEBUG","time":"2023-11-26T11:11:08.262Z","logger":"controller.nodeclaim.garbagecollection","message":"garbage collecting nodeclaim with no cloudprovider representation","commit":"1072d3b","nodeclaim":"default-pmmb4","provider-id":"aws:///eu-north-1c/a-1233315555","nodepool":"default"}
{"level":"INFO","time":"2023-11-26T11:11:08.620Z","logger":"controller.nodeclaim.termination","message":"deleted nodeclaim","commit":"1072d3b","nodeclaim":"default-pmmb4","nodepool":"default","node":"","provider-id":"aws:///eu-north-1c/a-1233315555"}
```

**Comment by jonathan-innis** [comment] 2023-11-30 20:04
I agree. I think we can close this, though, as a duplicate of https://github.com/aws/karpenter/issues/5145. I'd ideally like to see us do both: Handle a better log message from Karpenter's side and also update our docs to be more clear.

**Closed by jonathan-innis** 2023-11-30 20:04 UTC
