### ISSUE TITLE
waitForFirstConsumer PVCs fail to bind ebs gp3 (gp2) PV for newly created node

### ISSUE THREAD

**Issue by lbvffvbl** [aws/karpenter#1158] opened 2022-01-17 11:26 UTC
## Version

**Karpenter**: v0.5.3

**Kubernetes**: v1.20.7-eks-d88609

## Expected Behavior

PV will be bound when statefullset encourages karpenter to scale up a new node
## Actual Behavior

when you create statefulset with volumeClaimTemplates for ebs storage which encourages karpenter to scale up a new node. Scheduler doesn't annotate PVC with volume.kubernetes.io/selected-node and ebs controller doesn't bound PV with node.
but if you annotate PVC manualy, or recreate pod with PVC - PV will bound. It happen only for newly created node which was created for pending pod for current statefulset
```
$ k get pvc -n asg-test
NAME                              STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS    AGE
default-gp3-encrypted-webapp2-0   Pending                                      gp3-encrypted   9m21s
default-gp3-encrypted-webapp3-0   Pending                                      gp3-encrypted   9m44s
```

```
$ k describe pvc -n asg-test  default-gp3-encrypted-webapp3-0
Name:          default-gp3-encrypted-webapp3-0
Namespace:     asg-test
StorageClass:  gp3-encrypted
Status:        Pending
Volume:
Labels:        app=webapp3
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Used By:       webapp3-0
Events:
  Type    Reason                Age                 From                         Message
  ----    ------                ----                ----                         -------
  Normal  WaitForFirstConsumer  36s (x42 over 10m)  persistentvolume-controller  waiting for first consumer to be created before binding
```

## Steps to Reproduce the Problem

create statefulset with volumeClaimTemplates for ebs storage

## Resource Specs and Logs

Provisioner
```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: dedicated-for-clickhouse-m5-large
spec:
  kubeletConfiguration: {}
  labels:
    node.alpha.altinity.com/dedicated: clickhouse
  limits: {}
  provider:
    apiVersion: extensions.karpenter.sh/v1alpha1
    instanceProfile: KarpenterNodeInstanceProfile-asg-test
    kind: AWS
    securityGroupSelector:
      kubernetes.io/cluster/asg-test: '*'
    subnetSelector:
      kubernetes.io/cluster/asg-test: '*'
  requirements:
  - key: node.kubernetes.io/instance-type
    operator: In
    values:
    - m5.large
  - key: topology.kubernetes.io/zone
    operator: In
    values:
    - us-west-1a
    - us-west-1c
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - on-demand
  - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
  taints:
  - effect: NoSchedule
    key: dedicated
    value: clickhouse
  ttlSecondsAfterEmpty: 60
```
storageClass
```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: gp3-encrypted
parameters:
  encrypted: "true"
  fsType: ext4
  type: gp3
provisioner: ebs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```
statefulSet:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: webapp3
  namespace: asg-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp3
  serviceName: webapp3
  template:
    metadata:
      labels:
        app: webapp3
      name: webapp3
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                - us-west-1a
      containers:
      - command:
        - /bin/bash
        - -c
        - "while true; do sleep 6000;  done;"
        image: httpd:2.4
        name: webapp3
        volumeMounts:
        - mountPath: /var/lib/webapp3
          name: default-gp3-encrypted
      nodeSelector:
        node.kubernetes.io/instance-type: m5.large
      securityContext:
        fsGroup: 101
        runAsGroup: 101
        runAsUser: 101
      tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: clickhouse
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      labels:
        app: webapp3
      name: default-gp3-encrypted
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
      storageClassName: gp3-encrypted
      volumeMode: Filesystem
```

**Comment by lbvffvbl** [comment] 2022-01-17 11:32
It happens only with karpenter and doesn't happen when a new node is created by a cluster autoscaler. Can it be related to the node in Unknown state right after karpenter decided to scale up before the instance will be joined cluster?

**Comment by ellistarn** [comment] 2022-01-17 16:55
Karpenter currently sets the selected node annotation here: https://github.com/aws/karpenter/blob/main/pkg/controllers/persistentvolumeclaim/controller.go#L82. This is normally done by the kube scheduler, but Karpenter does it when it binds, since the kube scheduler is not in the loop.

> Can it be related to the node in Unknown state right after karpenter decided to scale up before the instance will join the cluster

I don't think so.

**Comment by ellistarn** [comment] 2022-01-17 16:58
I will attempt to reproduce on Tuesday.

**Comment by lbvffvbl** [comment] 2022-01-17 17:09
> Are you using the in-tree provider, or the https://github.com/kubernetes-sigs/aws-ebs-csi-driver? I will attempt to reproduce on Tuesday.

aws-ebs-csi-driver

**Comment by lbvffvbl** [comment] 2022-01-19 11:02
> Karpenter currently sets the selected node annotation here: https://github.com/aws/karpenter/blob/main/pkg/controllers/persistentvolumeclaim/controller.go#L82. This is normally done by the kube scheduler, but Karpenter does it when it binds, since the kube scheduler is not in the loop.
> 
> > Can it be related to the node in Unknown state right after karpenter decided to scale up before the instance will join the cluster
> 
> I don't think so. Let me dig in and see where this is breaking down.

I think it can be because karpenter does it too fast. I tried annotating it manually but it doesn't affect until the node in an unknown state 

```
$ k annotate pvc default-gp2-encrypted-chi-kate14-kate14-0-0-0  volume.kubernetes.io/selected-node=ip-10-3-41-207.us-west-2.compute.internal
persistentvolumeclaim/default-gp2-encrypted-chi-kate14-kate14-0-0-0 annotated

$ k get pvc default-gp2-encrypted-chi-kate14-kate14-0-0-0 -o yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/aws-ebs
  creationTimestamp: "2022-01-19T10:57:05Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: chop
    chi: kate14
  name: default-gp2-encrypted-chi-kate14-kate14-0-0-0
  namespace: default
  resourceVersion: "43103"
  uid: 802b531d-bb72-4f61-8649-3b3eb17c7792
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: gp2-encrypted
  volumeMode: Filesystem
status:
  phase: Pending
```

**Comment by ellistarn** [comment] 2022-01-19 18:24
I know this works without stateful sets. Let me see if something is meaningfully different in this case. Minimally, we can always wait for the node to be ready.

**Comment by ellistarn** [comment] 2022-01-19 18:34
I attempted to reproduce your exact setup and was successful
```
k get pods
NAME        READY   STATUS    RESTARTS   AGE
webapp3-0   1/1     Running   0          2m55s
```
What version of the ebs csi driver are you using?

**Comment by lbvffvbl** [comment] 2022-01-19 19:18
v1.0.0

**Comment by lbvffvbl** [comment] 2022-01-19 19:50
Actually i did not see in logs any messages from controller.volume
```
lbvf@lbvf-XPS-15-9550:~$ k logs -n karpenter-autoscaler  karpenter-controller-767bccffd-jwcth  -f
2022-01-19T19:40:49.139Z        INFO    Successfully created the logger.
2022-01-19T19:40:49.139Z        INFO    Logging level set to: debug
{"level":"info","ts":1642621249.2515757,"logger":"fallback","caller":"injection/injection.go:61","msg":"Starting informers..."}
2022-01-19T19:40:49.251Z        DEBUG   controller      Using AWS region us-west-2      {"commit": "5047f3c"}
I0119 19:40:49.287877       1 leaderelection.go:243] attempting to acquire leader lease karpenter-autoscaler/karpenter-leader-election...
2022-01-19T19:40:49.288Z        INFO    controller      starting metrics server {"commit": "5047f3c", "path": "/metrics"}
I0119 19:40:49.314691       1 leaderelection.go:253] successfully acquired lease karpenter-autoscaler/karpenter-leader-election
2022-01-19T19:40:49.314Z        DEBUG   controller.events       Normal  {"commit": "5047f3c", "object": {"kind":"ConfigMap","namespace":"karpenter-autoscaler","name":"karpenter-leader-election","uid":"7ecd2ee6-0f7c-453d-a9cc-de7ac4213dfb","apiVersion":"v1","resourceVersion":"255533"}, "reason": "LeaderElection", "message": "karpenter-controller-767bccffd-jwcth_fac0e9a3-8a22-4f63-ad63-4321f415bec0 became leader"}
2022-01-19T19:40:49.314Z        DEBUG   controller.events       Normal  {"commit": "5047f3c", "object": {"kind":"Lease","namespace":"karpenter-autoscaler","name":"karpenter-leader-election","uid":"8d2e2e70-e4d8-48a5-9046-a8b73890cc97","apiVersion":"coordination.k8s.io/v1","resourceVersion":"255534"}, "reason": "LeaderElection", "message": "karpenter-controller-767bccffd-jwcth_fac0e9a3-8a22-4f63-ad63-4321f415bec0 became leader"}
2022-01-19T19:40:49.388Z        INFO    controller.controller.counter   Starting EventSource    {"commit": "5047f3c", "reconciler group": "karpenter.sh", "reconciler kind": "Provisioner", "source": "kind source: /, Kind="}
2022-01-19T19:40:49.388Z        INFO    controller.controller.counter   Starting EventSource    {"commit": "5047f3c", "reconciler group": "karpenter.sh", "reconciler kind": "Provisioner", "source": "kind source: /, Kind="}
2022-01-19T19:40:49.388Z        INFO    controller.controller.counter   Starting Controller     {"commit": "5047f3c", "reconciler group": "karpenter.sh", "reconciler kind": "Provisioner"}
2022-01-19T19:40:49.389Z        INFO    controller.controller.provisioning      Starting EventSource    {"commit": "5047f3c", "reconciler group": "karpenter.sh", "reconciler kind": "Provisioner", "source": "kind source: /, Kind="}
2022-01-19T19:40:49.389Z        INFO    controller.controller.provisioning      Starting Controller     {"commit": "5047f3c", "reconciler group": "karpenter.sh", "reconciler kind": "Provisioner"}
2022-01-19T19:40:49.389Z        INFO    controller.controller.termination       Starting EventSource    {"commit": "5047f3c", "reconciler group": "", "reconciler kind": "Node", "source": "kind source: /, Kind="}
2022-01-19T19:40:49.389Z        INFO    controller.controller.termination       Starting Controller     {"commit": "5047f3c", "reconciler group": "", "reconciler kind": "Node"}
2022-01-19T19:40:49.390Z        INFO    controller.controller.node      Starting EventSource    {"commit": "5047f3c", "reconciler group": "", "reconciler kind": "Node", "source": "kind source: /, Kind="}
2022-01-19T19:40:49.390Z        INFO    controller.controller.node      Starting EventSource    {"commit": "5047f3c", "reconciler group": "", "reconciler kind": "Node", "source": "kind source: /, Kind="}
2022-01-19T19:40:49.390Z        INFO    controller.controller.node      Starting EventSource    {"commit": "5047f3c", "reconciler group": "", "reconciler kind": "Node", "source": "kind source: /, Kind="}
2022-01-19T19:40:49.390Z        INFO    controller.controller.node      Starting Controller     {"commit": "5047f3c", "reconciler group": "", "reconciler kind": "Node"}
2022-01-19T19:40:49.390Z        INFO    controller.controller.metrics   Starting EventSource    {"commit": "5047f3c", "reconciler group": "karpenter.sh", "reconciler kind": "Provisioner", "source": "kind source: /, Kind="}
2022-01-19T19:40:49.390Z        INFO    controller.controller.metrics   Starting Controller     {"commit": "5047f3c", "reconciler group": "karpenter.sh", "reconciler kind": "Provisioner"}
2022-01-19T19:40:49.490Z        INFO    controller.controller.metrics   Starting workers        {"commit": "5047f3c", "reconciler group": "karpenter.sh", "reconciler kind": "Provisioner", "worker count": 10}
2022-01-19T19:40:49.490Z        INFO    controller.controller.counter   Starting workers        {"commit": "5047f3c", "reconciler group": "karpenter.sh", "reconciler kind": "Provisioner", "worker count": 10}
2022-01-19T19:40:49.507Z        INFO    controller.controller.termination       Starting workers        {"commit": "5047f3c", "reconciler group": "", "reconciler kind": "Node", "worker count": 10}
2022-01-19T19:40:49.509Z        INFO    controller.controller.provisioning      Starting workers        {"commit": "5047f3c", "reconciler group": "karpenter.sh", "reconciler kind": "Provisioner", "worker count": 10}
2022-01-19T19:40:49.509Z        INFO    controller.controller.node      Starting workers        {"commit": "5047f3c", "reconciler group": "", "reconciler kind": "Node", "worker count": 10}
2022-01-19T19:42:27.304Z        DEBUG   controller.provisioning Discovered 350 EC2 instance types       {"commit": "5047f3c", "provisioner": "dedicated-for-clickhouse-m5-large"}
2022-01-19T19:42:27.319Z        DEBUG   controller.provisioning Discovered 350 EC2 instance types       {"commit": "5047f3c", "provisioner": "dedicated-for-clickhouse-m5-xlarge"}
2022-01-19T19:42:27.360Z        DEBUG   controller.provisioning Discovered 350 EC2 instance types       {"commit": "5047f3c", "provisioner": "dedicated-for-clickhouse-m5-4xlarge"}
2022-01-19T19:42:27.366Z        DEBUG   controller.provisioning Discovered subnets: [subnet-069552bb9ccbbd42c (us-west-2b) subnet-0147d332aca16ca35 (us-west-2a) subnet-00853a3952a256b66 (us-west-2c)] {"commit": "5047f3c", "provisioner": "dedicated-for-clickhouse-m5-large"}
2022-01-19T19:42:27.426Z        DEBUG   controller.provisioning Discovered 350 EC2 instance types       {"commit": "5047f3c", "provisioner": "dedicated-for-clickhouse-m5-2xlarge"}
2022-01-19T19:42:27.602Z        DEBUG   controller.provisioning Discovered 350 EC2 instance types       {"commit": "5047f3c", "provisioner": "dedicated-for-clickhouse-m5-8xlarge"}
2022-01-19T19:42:27.608Z        INFO    controller.provisioning Waiting for unschedulable pods  {"commit": "5047f3c", "provisioner": "dedicated-for-clickhouse-m5-8xlarge"}
2022-01-19T19:42:27.670Z        DEBUG   controller.provisioning Discovered EC2 instance types zonal offerings   {"commit": "5047f3c", "provisioner": "dedicated-for-clickhouse-m5-xlarge"}
2022-01-19T19:42:27.688Z        DEBUG   controller.provisioning Discovered EC2 instance types zonal offerings   {"commit": "5047f3c", "provisioner": "dedicated-for-clickhouse-m5-4xlarge"}
2022-01-19T19:42:27.694Z        INFO    controller.provisioning Waiting for unschedulable pods  {"commit": "5047f3c", "provisioner": "dedicated-for-clickhouse-m5-xlarge"}
2022-01-19T19:42:27.694Z        INFO    controller.provisioning Waiting for unschedulable pods  {"commit": "5047f3c", "provisioner": "dedicated-for-clickhouse-m5-4xlarge"}
2022-01-19T19:42:27.747Z        DEBUG   controller.provisioning Discovered EC2 instance types zonal offerings   {"commit": "5047f3c", "provisioner": "dedicated-for-clickhouse-m5-2xlarge"}
2022-01-19T19:42:27.753Z        INFO    controller.provisioning Waiting for unschedulable pods  {"commit": "5047f3c", "provisioner": "dedicated-for-clickhouse-m5-2xlarge"}
2022-01-19T19:42:27.775Z        DEBUG   controller.provisioning Discovered EC2 instance types zonal offerings   {"commit": "5047f3c", "provisioner": "dedicated-for-clickhouse-m5-large"}
2022-01-19T19:42:27.794Z        INFO    controller.provisioning Waiting for unschedulable pods  {"commit": "5047f3c", "provisioner": "dedicated-for-clickhouse-m5-large"}
2022-01-19T19:44:05.589Z        INFO    controller.provisioning Batched 1 pods in 1.011132514s  {"commit": "5047f3c", "provisioner": "dedicated-for-clickhouse-m5-large"}
2022-01-19T19:44:05.708Z        INFO    controller.provisioning Computed packing of 1 node(s) for 1 pod(s) with instance type option(s) [m5.large]      {"commit": "5047f3c", "provisioner": "dedicated-for-clickhouse-m5-large"}
2022-01-19T19:44:05.838Z        DEBUG   controller.provisioning Discovered security groups: [sg-09b629cc692803353 sg-0d9f5db69652bdded] {"commit": "5047f3c", "provisioner": "dedicated-for-clickhouse-m5-large"}
2022-01-19T19:44:05.838Z        DEBUG   controller.provisioning Ignoring security group sg-0d9f5db69652bdded, only one group with tag kubernetes.io/cluster/k-autoscaler-1 is allowed   {"commit": "5047f3c", "provisioner": "dedicated-for-clickhouse-m5-large"}
2022-01-19T19:44:05.843Z        DEBUG   controller.provisioning Discovered kubernetes version 1.20      {"commit": "5047f3c", "provisioner": "dedicated-for-clickhouse-m5-large"}
2022-01-19T19:44:05.909Z        DEBUG   controller.provisioning Discovered ami ami-07854b27891cd310f for query /aws/service/eks/optimized-ami/1.20/amazon-linux-2/recommended/image_id  {"commit": "5047f3c", "provisioner": "dedicated-for-clickhouse-m5-large"}
2022-01-19T19:44:05.909Z        DEBUG   controller.provisioning Discovered caBundle, length 1066        {"commit": "5047f3c", "provisioner": "dedicated-for-clickhouse-m5-large"}
2022-01-19T19:44:05.943Z        DEBUG   controller.provisioning Discovered launch template Karpenter-k-autoscaler-1-14227098493288535441        {"commit": "5047f3c", "provisioner": "dedicated-for-clickhouse-m5-large"}
2022-01-19T19:44:10.933Z        ERROR   controller.provisioning Could not launch node, launching instances, All attempts fail:
#1: got instance i-0ea8de58646cc306f but PrivateDnsName was not set
#2: got instance i-0ea8de58646cc306f but PrivateDnsName was not set
#3: got instance i-0ea8de58646cc306f but PrivateDnsName was not set     {"commit": "5047f3c", "provisioner": "dedicated-for-clickhouse-m5-large"}
2022-01-19T19:44:10.933Z        INFO    controller.provisioning Waiting for unschedulable pods  {"commit": "5047f3c", "provisioner": "dedicated-for-clickhouse-m5-large"}
2022-01-19T19:44:12.935Z        INFO    controller.provisioning Batched 1 pods in 1.000642345s  {"commit": "5047f3c", "provisioner": "dedicated-for-clickhouse-m5-large"}
2022-01-19T19:44:12.945Z        INFO    controller.provisioning Computed packing of 1 node(s) for 1 pod(s) with instance type option(s) [m5.large]      {"commit": "5047f3c", "provisioner": "dedicated-for-clickhouse-m5-large"}
2022-01-19T19:44:12.946Z        DEBUG   controller.provisioning Ignoring security group sg-0d9f5db69652bdded, only one group with tag kubernetes.io/cluster/k-autoscaler-1 is allowed   {"commit": "5047f3c", "provisioner": "dedicated-for-clickhouse-m5-large"}
2022-01-19T19:44:12.947Z        DEBUG   controller.provisioning Discovered caBundle, length 1066        {"commit": "5047f3c", "provisioner": "dedicated-for-clickhouse-m5-large"}
2022-01-19T19:44:14.844Z        INFO    controller.provisioning Launched instance: i-048edbd1d6c041029, hostname: ip-10-3-41-248.us-west-2.compute.internal, type: m5.large, zone: us-west-2a, capacityType: on-demand  {"commit": "5047f3c", "provisioner": "dedicated-for-clickhouse-m5-large"}
2022-01-19T19:44:14.869Z        INFO    controller.provisioning Bound 1 pod(s) to node ip-10-3-41-248.us-west-2.compute.internal        {"commit": "5047f3c", "provisioner": "dedicated-for-clickhouse-m5-large"}
2022-01-19T19:44:14.869Z        INFO    controller.provisioning Waiting for unschedulable pods  {"commit": "5047f3c", "provisioner": "dedicated-for-clickhouse-m5-large"}
2022-01-19T19:45:14.776Z        INFO    controller.node Added TTL to empty node {"commit": "5047f3c", "node": "ip-10-3-41-41.us-west-2.compute.internal"}
2022-01-19T19:46:14.821Z        INFO    controller.node Triggering termination after 1m0s for empty node        {"commit": "5047f3c", "node": "ip-10-3-41-41.us-west-2.compute.internal"}
2022-01-19T19:46:14.882Z        INFO    controller.termination  Cordoned node   {"commit": "5047f3c", "node": "ip-10-3-41-41.us-west-2.compute.internal"}
2022-01-19T19:46:15.121Z        INFO    controller.termination  Deleted node    {"commit": "5047f3c", "node": "ip-10-3-41-41.us-west-2.compute.internal"}
2022-01-19T19:47:29.493Z        DEBUG   controller.provisioning Discovered 350 EC2 instance types       {"commit": "5047f3c", "provisioner": "dedicated-for-clickhouse-m5-4xlarge"}
2022-01-19T19:47:29.527Z        DEBUG   controller.provisioning Discovered 350 EC2 instance types       {"commit": "5047f3c", "provisioner": "dedicated-for-clickhouse-m5-8xlarge"}
2022-01-19T19:47:29.573Z        DEBUG   controller.provisioning Discovered 350 EC2 instance types       {"commit": "5047f3c", "provisioner": "dedicated-for-clickhouse-m5-xlarge"}
2022-01-19T19:47:29.611Z        DEBUG   controller.provisioning Discovered subnets: [subnet-069552bb9ccbbd42c (us-west-2b) subnet-0147d332aca16ca35 (us-west-2a) subnet-00853a3952a256b66 (us-west-2c)] {"commit": "5047f3c", "provisioner": "dedicated-for-clickhouse-m5-4xlarge"}
2022-01-19T19:47:29.614Z        DEBUG   controller.provisioning Discovered subnets: [subnet-069552bb9ccbbd42c (us-west-2b) subnet-0147d332aca16ca35 (us-west-2a) subnet-00853a3952a256b66 (us-west-2c)] {"commit": "5047f3c", "provisioner": "dedicated-for-clickhouse-m5-xlarge"}
2022-01-19T19:47:29.695Z        DEBUG   controller.provisioning Discovered subnets: [subnet-069552bb9ccbbd42c (us-west-2b) subnet-00853a3952a256b66 (us-west-2c) subnet-0147d332aca16ca35 (us-west-2a)] {"commit": "5047f3c", "provisioner": "dedicated-for-clickhouse-m5-8xlarge"}
2022-01-19T19:47:29.707Z        DEBUG   controller.provisioning Discovered 350 EC2 instance types       {"commit": "5047f3c", "provisioner": "dedicated-for-clickhouse-m5-large"}
2022-01-19T19:47:29.738Z        DEBUG   controller.provisioning Discovered 350 EC2 instance types       {"commit": "5047f3c", "provisioner": "dedicated-for-clickhouse-m5-2xlarge"}
2022-01-19T19:47:29.874Z        DEBUG   controller.provisioning Discovered EC2 instance types zonal offerings   {"commit": "5047f3c", "provisioner": "dedicated-for-clickhouse-m5-4xlarge"}
2022-01-19T19:47:30.022Z        DEBUG   controller.provisioning Discovered EC2 instance types zonal offerings   {"commit": "5047f3c", "provisioner": "dedicated-for-clickhouse-m5-8xlarge"}
2022-01-19T19:47:30.193Z        DEBUG   controller.provisioning Discovered EC2 instance types zonal offerings   {"commit": "5047f3c", "provisioner": "dedicated-for-clickhouse-m5-large"}
2022-01-19T19:47:30.334Z        DEBUG   controller.provisioning Discovered EC2 instance types zonal offerings   {"commit": "5047f3c", "provisioner": "dedicated-for-clickhouse-m5-2xlarge"}
2022-01-19T19:47:30.384Z        DEBUG   controller.provisioning Discovered EC2 instance types zonal offerings   {"commit": "5047f3c", "provisioner": "dedicated-for-clickhouse-m5-xlarge"}
```

**Comment by lbvffvbl** [comment] 2022-01-19 20:06
I upgraded karpenter to 0.5.4 version and the problem is gone. Look like you should actualize information there 
https://karpenter.sh/

**Comment by ellistarn** [comment] 2022-01-19 20:22
Aha! This was released in v0.5.4: https://github.com/aws/karpenter/releases/tag/v0.5.4.

**Comment by lbvffvbl** [comment] 2022-01-19 20:22
> I upgraded karpenter to 0.5.4 version and the problem is gone. Look like you should actualize information there https://karpenter.sh/

https://github.com/aws/karpenter/blob/v0.5.3/cmd/controller/main.go#L91 PVC controller was not runned

**Comment by ellistarn** [comment] 2022-01-19 20:23
It wasn't even implemented then. I'm trying to track this down in the docs too, since I could've sworn I documented this.

**Comment by lbvffvbl** [comment] 2022-01-19 20:27
> Documented here: https://karpenter.sh/preview/tasks/scheduling/#persistent-volume-topology

yep. but everywhere is pointed 0.5.3 version
https://karpenter.sh/preview/getting-started-with-terraform/
https://karpenter.sh/preview/getting-started/

It confused me. And as I see actual version is 0.5.5 already :)

**Comment by lbvffvbl** [comment] 2022-01-19 20:32
Anyway thanks for helping. I think we can try to migrate on it

**Comment by ellistarn** [comment] 2022-01-19 20:33
We had some docs issues that should be sorted out in v0.5.5. Good to work this out with you!

**Closed** 2022-01-19 20:32 UTC
Labels: bug
