### ISSUE TITLE
EC2 spot instance interruption handling

### ISSUE THREAD

**Issue by zeagord** [aws/karpenter#974] opened 2021-12-13 04:50 UTC
**Tell us about your request**
What do you want us to build?
Currently Karpenter doesn't have spot instance interruption handling mechanism. Users have to to install node termination handler (https://github.com/aws/aws-node-termination-handler) along with karpenter. It would be useful if this is built natively within karpenter

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.
Users have to install NTH and karpenter separately and maintain

**Are you currently working around this issue?**
No

How are you currently solving this problem?
By using the NTH 
**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment] 2021-12-13 05:02
I'd love to do this. We'd need some concept of provider specific controllers. Alternatively, I could imagine wiring this through the cloud provider API like:

```
// AwaitInterruptions terminates nodes when notified by the provider of a force shutdown
AwaitInterruptions(provisioner *v1alpha5.Provisioner) chan string
```

We may also want to wire through a concept of duration to differentiate between rebalance and interrupt.

**Comment by ellistarn** [comment] 2021-12-13 22:19
Closing as duplicate of https://github.com/aws/karpenter/issues/702

**Closed by ellistarn** 2021-12-13 22:19 UTC
Labels: feature, aws
