### ISSUE TITLE
Question: How does the drift mechanism works?

### ISSUE THREAD

**Issue by Rez0k** [aws/karpenter#5083] opened 2023-11-13 22:31 UTC
Hi,

I want to add the drift feature flag to my cluster, I tried it on a test cluster and I seen that karpenter creates 2 or 3 nodes at a time and then terminate 2 / 3 exists nodes when the new nodes are ready.

I want to control this kind of behavior and change it to drift one by one according to my needs.

Can someone explain the current mechanism of the drift feature flag and how many nodes at a time karpenter replace and how (if possible) I can adjust this?

I couldn't find specific docs on this matter

**Comment by tzneal** [comment] 2023-11-14 15:30
Closing as a duplicate of https://github.com/aws/karpenter/issues/1738, there are some links to a doc at https://github.com/aws/karpenter-core/pull/516 where the potential implementation for controlling this is discussed.

**Closed by tzneal** 2023-11-14 15:30 UTC
