### ISSUE TITLE
Karpenter not provisioning new nodes after instances become unreachable/NotReady

### ISSUE THREAD

**Issue by aaronborden-rivian** [aws/karpenter#2570] opened 2022-09-30 19:05 UTC
### Version

__Karpenter Version:__ v0.16.1

__Kubernetes Version:__ v1.23.7-eks-4721010

### Expected Behavior

When a node transitions from Ready -> NotReady and there are pods pending, Karpenter should spin up new nodes

### Actual Behavior

Node transitions from Ready -> NotReady and Karpenter does not spin up new nodes
```
7 node(s) didn't match Pod's node affinity/selector."
316Waiting for pod vt-arm64/runner-s2ryk2jg-project-3928-concurrent-0qf92m to be running, status is Pending
317	Unschedulable: "0/8 nodes are available: 1 node(s) had taint {[node.kubernetes.io/unreachable](http://node.kubernetes.io/unreachable): }, that the pod didn't tolerate, 7 node(s) didn't match Pod's node affinity/selector."
318Waiting for pod vt-arm64/runner-s2ryk2jg-project-3928-concurrent-0qf92m to be running, status is Pending
319	Unschedulable: "0/8 nodes are available: 1 node(s) had taint {[node.kubernetes.io/unreachable](http://node.kubernetes.io/unreachable): }, that the pod didn't tolerate, 7 node(s) didn't match Pod's node affinity/selector."
```

Pod events
```
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  45s   default-scheduler  0/9 nodes are available: 1 node(s) had taint {node.kubernetes.io/unreachable: }, that the pod didn't tolerate, 8 node(s) didn't match Pod's node affinity/selector.
  Normal   Nominate          43s   karpenter          Pod should schedule on ip-100-64-76-217.us-east-2.compute.internal
```

### Steps to Reproduce the Problem

1. Include a1.4xlarge in instance type
2. Create a pod with nodeSelector kubernetes.io/arch=arm64
3. Wait for instance to become unreachable
4.  Create a pod with nodeSelector kubernetes.io/arch=arm64

### Resource Specs and Logs

```
$ prod get provisioner vt-runners -o yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: vt-runners
spec:
  consolidation:
    enabled: false
  kubeletConfiguration:
    containerRuntime: dockerd
  limits:
    resources:
      cpu: 48k
      memory: 196Ti
  providerRef:
    name: default
  requirements:
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - on-demand
  - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
    - arm64
  - key: karpenter.k8s.aws/instance-family
    operator: In
    values:
    - a1
    - c6a
    - c6i
    - m6a
    - m6g
    - m6i
    - m5
  - key: karpenter.k8s.aws/instance-size
    operator: In
    values:
    - 4xlarge
    - 8xlarge
    - 12xlarge
    - 16xlarge
    - 24xlarge
  taints:
  - effect: NoSchedule
    key: vt.goriv.co/runners
  ttlSecondsAfterEmpty: 3600
  ttlSecondsUntilExpired: 2592000
  weight: 20
```

Pod
```
apiVersion: v1
kind: Pod
metadata:
  name: arm-test
spec:
  containers:
  - command:
    - echo
    - ok
    image: arm64v8/busybox:latest
    imagePullPolicy: Always
    name: arm
    securityContext:
      capabilities:
        drop:
        - NET_RAW
      privileged: true
  nodeSelector:
    kubernetes.io/arch: arm64
    kubernetes.io/os: linux
  preemptionPolicy: PreemptLowerPriority
  restartPolicy: Never
  tolerations:
  - effect: NoSchedule
    key: vt.goriv.co/runners
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment] 2022-10-05 23:43
Why is this instance becoming unreachable? We currently treat unreachable nodes as "InFlight" and wait for them to recover. It essentially shirks the responsibility of detecting whether or not the node is healthy to another solution like the https://github.com/kubernetes/node-problem-detector. That said, I think we probably want to be responsible for determining node healthiness as an e2e management solution. There's a related PR with some discussion here: https://github.com/aws/karpenter/pull/2235

**Comment by omgapuppy** [comment] 2022-10-25 16:16
We've recently run into the same. The scheduled node never became `Ready`, leaving Karpenter in a state where it just kept waiting to schedule the workload. A `TTLSecondsAfterNotReady` attribute as implemented in #2235 would've avoided such a scenario. I'm not convinced `node-problem-detector` would help in such a scenario, since there's no guarantee it itself is up and running on a node that is failing to become ready / bootstrap fully. Unfortunately we don't have the root cause of the failing to provision node as it was terminated by the owner of the affected workload, but for what it's worth the AMI used was a vanilla EKS Bottlerocket 1.22 image.

**Comment by omgapuppy** [comment] 2022-11-03 14:33
We just ran into this again - the only details are that affected region was once again `ap-southeast-2`, the instance family `c5a` and other than Karpenter waiting forever (resulting in an unready node alarm) the main symptom was the EC2 instance being stuck in a "Pending" state for excessive time (30ish minutes). This happened across a number of clusters in that region (separate accounts) and around the same time. Smells like capacity issues or something up with EC2 in Sydney that's not being communicated publicly.

**Comment by jalaziz** [comment] 2023-01-27 07:53
Just ran into this too, but in `eu-west-2` 😞

**Comment by ellistarn** [comment] 2023-01-29 16:24
Thanks for the reports! Can we consolidate discussion here: https://github.com/aws/karpenter/issues/2021? Closing as duplicate.

**Closed by ellistarn** 2023-01-29 16:24 UTC
Labels: bug
