### ISSUE TITLE
After a fallback to on-demand Karpenter doesn't replace back to spot

### ISSUE THREAD

**Issue by liorfranko** [aws/karpenter#3480] opened 2023-02-28 04:49 UTC
### Version

__Karpenter Version:__ v0.23.0

__Kubernetes Version:__ v1.24.0

### Expected Behavior

After a fallback to on-demand due to capacity issues, once the Spot market is available once again Karpenter should replace the on-demand with spot.

### Actual Behavior

After a fallback to on-demand due to capacity issues, the on-demand nodes are left in the cluster for ever.

### Steps to Reproduce the Problem

Run a provisioner and trigger a fallback from spot to on-demand.

### Resource Specs and Logs

None.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by liorfranko** [comment] 2023-02-28 12:07
Here is the provisioner config:
```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"karpenter.sh/v1alpha5","kind":"Provisioner","metadata":{"annotations":{},"labels":{"argocd.argoproj.io/instance":"karpenter-resources"},"name":"ds-infra-network-online-spot"},"spec":{"consolidation":{"enabled":true},"labels":{"intent":"apps","nodegroup-name":"ds-infra-network-online-spot","project":"mobile-ds-infra-network-online"},"providerRef":{"name":"ds-infra-network-online-spot"},"requirements":[{"key":"topology.kubernetes.io/zone","operator":"In","values":["us-east-1b","us-east-1d","us-east-1e","us-east-1f"]},{"key":"karpenter.sh/capacity-type","operator":"In","values":["spot","on-demand"]},{"key":"karpenter.k8s.aws/instance-size","operator":"NotIn","values":["nano","micro","small","large","48xlarge","metal"]},{"key":"karpenter.k8s.aws/instance-family","operator":"In","values":["c5","c5d","c5n","c6i","c6id","c6in","c6a","m6i","m6id","m6idn","m6in","m6a","r6i","r6id","r6in","r6idn","r6a"]},{"key":"kubernetes.io/arch","operator":"In","values":["amd64"]},{"key":"kubernetes.io/os","operator":"In","values":["linux"]}]}}
  creationTimestamp: '2023-01-31T10:45:51Z'
  generation: 2
  labels:
    argocd.argoproj.io/instance: karpenter-resources
  name: ds-infra-network-online-spot
  resourceVersion: '193739333'
  uid: 02875d66-bd25-4e93-bb9b-6a293dfdbf0a
spec:
  consolidation:
    enabled: true
  labels:
    intent: apps
    nodegroup-name: ds-infra-network-online-spot
    project: mobile-ds-infra-network-online
  providerRef:
    name: ds-infra-network-online-spot
  requirements:
    - key: topology.kubernetes.io/zone
      operator: In
      values:
        - us-east-1b
        - us-east-1d
        - us-east-1e
        - us-east-1f
    - key: karpenter.sh/capacity-type
      operator: In
      values:
        - spot
        - on-demand
    - key: karpenter.k8s.aws/instance-size
      operator: NotIn
      values:
        - nano
        - micro
        - small
        - large
        - 32xlarge
        - 48xlarge
        - metal
    - key: karpenter.k8s.aws/instance-family
      operator: In
      values:
        - c5
        - c5d
        - c5n
        - c6i
        - c6id
        - c6in
        - c6a
        - m6i
        - m6id
        - m6idn
        - m6in
        - m6a
        - r6i
        - r6id
        - r6in
        - r6idn
        - r6a
    - key: kubernetes.io/arch
      operator: In
      values:
        - amd64
    - key: kubernetes.io/os
      operator: In
      values:
        - linux
status:
  resources:
    attachable-volumes-aws-ebs: '20719'
    cpu: '48360'
    ephemeral-storage: 11548525812Ki
    memory: 209830629644Ki
    pods: '377624'
```

**Comment by tzneal** [comment] 2023-02-28 13:55
Are you using the `aws.isolatedVPC` setting? And can you provide the Karpenter logs for a period of time when you have on-demand nodes and expect them to be replaced with spot?

**Comment by liorfranko** [comment] 2023-02-28 15:00
`aws.isolatedVPC` is set to `false`
Logs attached.
You can look at ip-10-207-10-112.ec2.internal

At 7AM I manually deleted it.
[Untitled discover search.csv](https://github.com/aws/karpenter/files/10851642/Untitled.discover.search.csv)

**Comment by tzneal** [comment] 2023-02-28 15:29
If this happens again, can you run `kubectl describe node node-name` on the node that should be replaced?  There should be events registered against the node that indicate why its not being consolidated.

**Comment by liorfranko** [comment] 2023-03-04 12:12
Here is the node's information:
```
ubectl describe nodes ip-10-207-99-108.ec2.internal
Name:               ip-10-207-99-108.ec2.internal
Roles:              <none>
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=m6i.24xlarge
                    beta.kubernetes.io/os=linux
                    failure-domain.beta.kubernetes.io/region=us-east-1
                    failure-domain.beta.kubernetes.io/zone=us-east-1d
                    intent=apps
                    k8s.io/cloud-provider-aws=7e43c8d478ffdd4cb3168691ff335629
                    karpenter.k8s.aws/instance-ami-id=ami-01ced323515f177b0
                    karpenter.k8s.aws/instance-category=m
                    karpenter.k8s.aws/instance-cpu=96
                    karpenter.k8s.aws/instance-encryption-in-transit-supported=true
                    karpenter.k8s.aws/instance-family=m6i
                    karpenter.k8s.aws/instance-generation=6
                    karpenter.k8s.aws/instance-hypervisor=nitro
                    karpenter.k8s.aws/instance-memory=393216
                    karpenter.k8s.aws/instance-pods=737
                    karpenter.k8s.aws/instance-size=24xlarge
                    karpenter.sh/capacity-type=on-demand
                    karpenter.sh/initialized=true
                    karpenter.sh/provisioner-name=ds-infra-network-online-spot
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=ip-10-207-99-108.ec2.internalec2ssa.info
                    kubernetes.io/os=linux
                    node.kubernetes.io/instance-type=m6i.24xlarge
                    nodegroup-name=ds-infra-network-online-spot
                    project=mobile-ds-infra-network-online
                    topology.ebs.csi.aws.com/zone=us-east-1d
                    topology.kubernetes.io/region=us-east-1
                    topology.kubernetes.io/zone=us-east-1d
Annotations:        alpha.kubernetes.io/provided-node-ip: 10.207.99.108
                    csi.volume.kubernetes.io/nodeid: {"ebs.csi.aws.com":"i-0fe9face3a9494021","secrets-store.csi.k8s.io":"ip-10-207-99-108.ec2.internal"}
                    management.cattle.io/pod-limits: {"cpu":"9","memory":"181628Mi"}
                    management.cattle.io/pod-requests: {"cpu":"91705m","memory":"176820Mi","pods":"13"}
                    node.alpha.kubernetes.io/ttl: 60
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Thu, 02 Mar 2023 21:07:41 +0200
Taints:             <none>
Unschedulable:      false
Lease:
  HolderIdentity:  ip-10-207-99-108.ec2.internal
  AcquireTime:     <unset>
  RenewTime:       Sat, 04 Mar 2023 14:06:58 +0200
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  Ready            True    Sat, 04 Mar 2023 14:05:08 +0200   Thu, 02 Mar 2023 21:08:52 +0200   KubeletReady                 kubelet is posting ready status
  MemoryPressure   False   Sat, 04 Mar 2023 14:05:08 +0200   Thu, 02 Mar 2023 21:08:16 +0200   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Sat, 04 Mar 2023 14:05:08 +0200   Thu, 02 Mar 2023 21:08:16 +0200   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Sat, 04 Mar 2023 14:05:08 +0200   Thu, 02 Mar 2023 21:08:16 +0200   KubeletHasSufficientPID      kubelet has sufficient PID available
Addresses:
  InternalIP:   10.207.99.108
  ExternalIP:   54.90.136.191
  Hostname:     ip-10-207-99-108.ec2.internal
  InternalDNS:  ip-10-207-99-108.ec2.internal
  InternalDNS:  ip-10-207-99-108.ec2ssa.info
  ExternalDNS:  ec2-54-90-136-191.compute-1.amazonaws.com
Capacity:
  attachable-volumes-aws-ebs:  39
  cpu:                         96
  ephemeral-storage:           98553836Ki
  hugepages-1Gi:               0
  hugepages-2Mi:               0
  memory:                      390006640Ki
  pods:                        737
Allocatable:
  attachable-volumes-aws-ebs:  39
  cpu:                         95690m
  ephemeral-storage:           89753473284
  hugepages-1Gi:               0
  hugepages-2Mi:               0
  memory:                      381341552Ki
  pods:                        737
System Info:
  Machine ID:                 ec28ecb31a2d05119dc6d06de90ac2a2
  System UUID:                ec28ecb3-1a2d-0511-9dc6-d06de90ac2a2
  Boot ID:                    c7c352b4-6957-43d5-85dd-32d3fe1c4ee8
  Kernel Version:             5.10.165-143.735.amzn2.x86_64
  OS Image:                   Amazon Linux 2
  Operating System:           linux
  Architecture:               amd64
  Container Runtime Version:  containerd://1.6.6
  Kubelet Version:            v1.24.10-eks-48e63af
  Kube-Proxy Version:         v1.24.10-eks-48e63af
ProviderID:                   aws:///us-east-1d/i-0fe9face3a9494021
Non-terminated Pods:          (13 in total)
  Namespace                   Name                                                             CPU Requests  CPU Limits  Memory Requests  Memory Limits  Age
  ---------                   ----                                                             ------------  ----------  ---------------  -------------  ---
  devops                      csi-secrets-store-provider-aws-76dg2                             50m (0%)      0 (0%)      100Mi (0%)       100Mi (0%)     40h
  devops                      csi-secrets-store-provider-aws-secrets-store-csi-driver-q9fnv    70m (0%)      0 (0%)      140Mi (0%)       400Mi (0%)     40h
  ds-infra-apps               is-ds-online-6bfc4756c7-g7bw4                                    45500m (47%)  4 (4%)      87028Mi (23%)    87028Mi (23%)  41h
  ds-infra-apps               rv-ds-online-6ffbfbb794-tg24k                                    45500m (47%)  4 (4%)      88564Mi (23%)    88564Mi (23%)  25h
  granulate-agent             granulate-agent-lg65t                                            50m (0%)      1 (1%)      256Mi (0%)       2Gi (0%)       40h
  istio-system                istio-cni-node-gvxqz                                             10m (0%)      0 (0%)      50Mi (0%)        256Mi (0%)     40h
  kube-system                 aws-node-78cs6                                                   25m (0%)      0 (0%)      0 (0%)           0 (0%)         40h
  kube-system                 aws-node-termination-handler-fc56q                               50m (0%)      0 (0%)      128Mi (0%)       128Mi (0%)     40h
  kube-system                 ebs-csi-node-rf8sr                                               150m (0%)     0 (0%)      120Mi (0%)       144Mi (0%)     40h
  kube-system                 kube-proxy-dpwdf                                                 100m (0%)     0 (0%)      0 (0%)           0 (0%)         40h
  kubecost                    kubecost-network-costs-6p79k                                     50m (0%)      0 (0%)      256Mi (0%)       2Gi (0%)       40h
  logging                     filebeat-88db2                                                   100m (0%)     0 (0%)      128Mi (0%)       512Mi (0%)     40h
  monitoring                  kube-prometheus-stack-prometheus-node-exporter-nm4tr             50m (0%)      0 (0%)      50Mi (0%)        400Mi (0%)     40h
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource                    Requests        Limits
  --------                    --------        ------
  cpu                         91705m (95%)    9 (9%)
  memory                      176820Mi (47%)  181628Mi (48%)
  ephemeral-storage           0 (0%)          0 (0%)
  hugepages-1Gi               0 (0%)          0 (0%)
  hugepages-2Mi               0 (0%)          0 (0%)
  attachable-volumes-aws-ebs  0               0
Events:                       <none>
```
We have enough PDB:
```
kubectl -n ds-infra-apps get pdb
NAME                            MIN AVAILABLE   MAX UNAVAILABLE   ALLOWED DISRUPTIONS   AGE
is-ds-online                    10%             N/A               544                   32d
rv-ds-online                    10%             N/A               529                   25d
```

Here is the pod's labels and annotations:
```
kubectl -n ds-infra-apps describe pods is-ds-online-6bfc4756c7-g7bw4
Name:         is-ds-online-6bfc4756c7-g7bw4
Namespace:    ds-infra-apps
Priority:     0
Node:         ip-10-207-99-108.ec2.internal/10.207.99.108
Start Time:   Thu, 02 Mar 2023 21:09:20 +0200
Labels:       adUnit=is
              app=is-ds-online
              app.kubernetes.io/managed-by=spinnaker
              app.kubernetes.io/name=is-ds-online
              canary=false
              chart_version=2.0.42
              commit=5bc00987f0ca62262ed728fa10f23fb9bc3724e6
              envType=sonic-prod
              environment=prod
              name=is-ds-online
              owner=demand
              project=network-online
              role=stable
              rollouts-pod-template-hash=6bfc4756c7
              security.istio.io/tlsMode=istio
              service.istio.io/canonical-name=is-ds-online
              service.istio.io/canonical-revision=latest
              sidecar.istio.io/inject=true
              stack=request
              team=ds-infra
              topic=app
              type=ds-online
Annotations:  artifact.spinnaker.io/location: ds-infra-apps
              artifact.spinnaker.io/name: is-ds-online
              artifact.spinnaker.io/type: kubernetes/Rollout.argoproj.io
              artifact.spinnaker.io/version:
              checksum/config: 0e6094aca5c03b4cf35a188e5a73881d76c42157c6ac88429ce9cf8c00d84483
              k8s.v1.cni.cncf.io/networks: istio-cni
              kubectl.kubernetes.io/default-container: telegraf
              kubectl.kubernetes.io/default-logs-container: telegraf
              kubernetes.io/psp: eks.privileged
              moniker.spinnaker.io/application: is-ds-online
              moniker.spinnaker.io/cluster: Rollout.argoproj.io is-ds-online
              prometheus.io/path: /stats/prometheus
              prometheus.io/port: 15020
              prometheus.io/scrape: true
              sidecar.istio.io/interceptionMode: REDIRECT
              sidecar.istio.io/proxyCPU: 1000m
              sidecar.istio.io/proxyMemory: 512Mi
              sidecar.istio.io/proxyMemoryLimit: 512Mi
              sidecar.istio.io/status:
                {"initContainers":["istio-validation"],"containers":["istio-proxy"],"volumes":["workload-socket","credential-socket","workload-certs","ist...
              traffic.sidecar.istio.io/excludeInboundPorts: 15020
              traffic.sidecar.istio.io/includeInboundPorts: 80, 8080
              traffic.sidecar.istio.io/includeOutboundIPRanges: *
              traffic.sidecar.istio.io/includeOutboundPorts: 80, 8080
kubectl -n ds-infra-apps describe pods rv-ds-online-6ffbfbb794-tg24k
Name:         rv-ds-online-6ffbfbb794-tg24k
Namespace:    ds-infra-apps
Priority:     0
Node:         ip-10-207-99-108.ec2.internal/10.207.99.108
Start Time:   Fri, 03 Mar 2023 12:18:54 +0200
Labels:       adUnit=rv
              app=rv-ds-online
              app.kubernetes.io/managed-by=spinnaker
              app.kubernetes.io/name=rv-ds-online
              chart_version=2.0.42
              commit=5bc00987f0ca62262ed728fa10f23fb9bc3724e6
              envType=sonic-prod
              environment=prod
              name=rv-ds-online
              owner=demand
              project=network-online
              rollouts-pod-template-hash=6ffbfbb794
              sidecar.istio.io/inject=false
              stack=request
              team=ds-infra
              topic=app
              type=ds-online
Annotations:  artifact.spinnaker.io/location: ds-infra-apps
              artifact.spinnaker.io/name: rv-ds-online
              artifact.spinnaker.io/type: kubernetes/Rollout.argoproj.io
              artifact.spinnaker.io/version:
              checksum/config: a372bd021f84d7671174a6d5ab3c2c807c0ecd300d476bff9615ab2fca5b752d
              kubernetes.io/psp: eks.privileged
              moniker.spinnaker.io/application: rv-ds-online
              moniker.spinnaker.io/cluster: Rollout.argoproj.io rv-ds-online
              yourkit:
```

**Comment by tzneal** [comment] 2023-03-04 18:10
That's very odd, I'm running v0.23.0 just to test the same version and I get events on nodes periodically identifying why they aren't being consolidated.  It's acting like consolidation is turned off, or skipping these nodes for some reason.  I'll dig into it.

```
Events:
  Type    Reason            Age                   From       Message
  ----    ------            ----                  ----       -------
  Normal  Unconsolidatable  10m (x13 over 3h12m)  karpenter  can't replace with a cheaper node
```

**Comment by tzneal** [comment] 2023-03-06 15:18
I forgot, some older versions of kubectl won't display the events. Can you check:

**Comment by tzneal** [comment] 2023-03-07 13:25
Can you try restarting the Karpenter deployment (e.g. `kubectl rollout restart deployment -n karpenter karpenter`) to see if:
a) any nodes are immediately consolidated
b) node events start getting reported?

I did find a bug that caused the events to not be reported yesterday and fixed it with https://github.com/aws/karpenter-core/pull/232, but it shouldn't have been in the v0.23.0 release. From what I can tell it was introduced in v0.24.0

**Comment by liorfranko** [comment] 2023-03-09 20:58
I upgraded to version 0.27 and have the same issue.
6 hours after a fallback from Spot to On-demand, the market is already stable, but the OD nodes are still in the cluster.
I restarted Karpenter pods and 10 minutes after, the OD instances haven't been replaced.

**Comment by tzneal** [comment] 2023-03-09 21:00
Are events being reported against the node?

**Comment by liorfranko** [comment] 2023-03-09 21:08
None and I fixed the kubectl version.
Could it be possible that it's blocked by this https://github.com/aws/karpenter/issues/3561 or it's related?

**Comment by tzneal** [comment] 2023-03-09 21:45
Yes, that is it if you now have a large batch of expired nodes that need to be replaced.  We won't try to consolidate until all of the expired nodes are replaced, the code is at https://github.com/aws/karpenter-core/blob/7c33b1678a585e8d6d3399867663881ceaa4fa16/pkg/controllers/deprovisioning/controller.go#L85 .

The theory when we did that was it made more sense to replace expired nodes since they were going away, vs potentially packing pods onto nodes that would soon expire.

**Comment by liorfranko** [comment] 2023-03-10 03:57
I think that fallback from on-demand to spot should have a much higher priority than expired nodes.

**Comment by liorfranko** [comment] 2023-03-10 06:59
I removed the TTL from the provisioner and restarted Karpenter, but the OD nodes were not removed.
Again, without any events.

**Comment by ODudek** [comment] 2023-03-14 07:12
Is there any follow up in this thread? I'm facing the same problem

**Comment by maxforasteiro** [comment] 2023-04-03 11:43
Interestingly enough, I didn't find this behaviour anywhere in the documentation. I was about to implement two providers with different weights to achieve the behaviour described on the issue.

Just to confirm: if a provider is configured with both `spot` and `on-demand` capacity-type, it will prefer the spot instances *always* unless there are no spot instances that can fulfill the requirements for the provider, meaning that having both values set for `karpenter.sh/capacity-type` should be the default configuration for most cases, correct?

**Comment by ellistarn** [comment] 2023-04-03 21:07
@ODudek, there are multiple issues discussed in this thread. Can you open a fresh issue with what you're facing to avoid muddying the water?

**Comment by ellistarn** [comment] 2023-04-03 21:09
From my understanding the root cause is:
1. Consolidation cannot occur, since nodes are expired
2. Nodes are expired because the TTL is short enough that they're in a permanent expire loop.

We're exploring two improvements to solve this long term:
1. Prioritize consolidation ahead of Expiration
2. Expand multi-node-consolidation to support multi-node-deprovisioning (e.g. expiration, utilization, drift, etc)

**Comment by njtran** [comment] 2023-04-03 21:32
That's right @ellistarn, thanks for writing that up. Long term I'm thinking we can do some smarter prioritization logic, where everything is a function of Consolidation. 

In the meantime, it's clear that the deprovisioning logic's optimism of one-at-a-time is proving not quick enough. In larger batches of nodes that need deprovisioning, we may be able to simply rely on similar code as used for multi-node consolidation. This would make expiration and drift much quicker as well, which we've heard many times in the past that expiring/drifting all eligible nodes simultaneously is too disruptive. The solution here should work well with all sizes of clusters.

**Comment by ahoze-r7** [comment] 2023-04-11 08:33
Hi, when this bug should be fix?

**Comment by njtran** [comment] 2023-09-13 18:51
Hey @liorfranko @ahoze-r7, this should be fixed as part of (1) https://github.com/aws/karpenter-core/issues/370 and (2) https://github.com/aws/karpenter/issues/2741. As I understand it, the rate that nodes were marked as expired for the previously set `ttlSecondsUntilExpired` was too fast for Karpenter to keep up. We're tracking performance improvements in (1) and (2) should fix the use-case that you had set. 

I'm going to close this, feel free to re-open if you disagree.

**Closed by njtran** 2023-09-13 18:51 UTC
Labels: bug
