### ISSUE TITLE
webhook container resetting DELETE operation in defaulting.webhook.provisioners.karpenter.sh

### ISSUE THREAD

**Issue by pyromaniac3010** [aws/karpenter#1971] opened 2022-06-22 08:31 UTC
## Version

**Karpenter**: v0.12.0

**Kubernetes**: v1.22.9-eks-a64ea69

## Expected Behavior
The defaulting.webhook.provisioners.karpenter.sh deployed via helm chart should not change after starting up of the karpenter webhook container.

## Actual Behavior
We deploy the karpenter helm chart via argo-cd which monitors all changes to the resources. After upgrading from 0.9.0 to 0.11.0 yesterday and to 0.12.0 today, the defaulting.webhook.provisioners.karpenter.sh resource permanently shows "out of sync".
I found that a "DELETE" was added to defaulting.webhook.provisioners.karpenter.sh in the helm chart template https://github.com/aws/karpenter/blob/main/charts/karpenter/templates/webhooks.yaml. This is rolled out by argo-cd as it should. But after starting up of the karpenter deployment containers the webhook is rewritten and both `- DELETE` lines from defaulting.webhook.provisioners.karpenter.sh are removed.

## Steps to Reproduce the Problem

Install the helm chart as is without starting the deployment yet.
The webhook looks like this:
```
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  labels:
    app.kubernetes.io/instance: karpenter
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: karpenter
    app.kubernetes.io/version: 0.12.0
    argocd.astack.xyz/applicationInstance: mgmt-k8s1-karpenter
    helm.sh/chart: karpenter-0.12.0
  name: defaulting.webhook.provisioners.karpenter.sh
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: karpenter
        namespace: karpenter
    failurePolicy: Fail
    name: defaulting.webhook.provisioners.karpenter.sh
    rules:
      - apiGroups:
          - karpenter.k8s.aws
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - awsnodetemplates
          - awsnodetemplates/status
        scope: '*'
      - apiGroups:
          - karpenter.sh
        apiVersions:
          - v1alpha5
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - provisioners
          - provisioners/status
    sideEffects: None
```
Start the deployment. The webhook container will modify defaulting.webhook.provisioners.karpenter.sh to this:
```
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  labels:
    app.kubernetes.io/instance: karpenter
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: karpenter
    app.kubernetes.io/version: 0.12.0
    argocd.astack.xyz/applicationInstance: mgmt-k8s1-karpenter
    helm.sh/chart: karpenter-0.12.0
  name: defaulting.webhook.provisioners.karpenter.sh
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: karpenter
        namespace: karpenter
    failurePolicy: Fail
    name: defaulting.webhook.provisioners.karpenter.sh
    rules:
      - apiGroups:
          - karpenter.k8s.aws
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - awsnodetemplates
          - awsnodetemplates/status
        scope: '*'
      - apiGroups:
          - karpenter.sh
        apiVersions:
          - v1alpha5
        operations:
          - CREATE
          - UPDATE
        resources:
          - provisioners
          - provisioners/status
    sideEffects: None
```
operations.DELETE is now missing.

## Resource Specs and Logs
```
2022/06/22 08:10:11 Registering 2 clients
2022/06/22 08:10:11 Registering 2 informer factories
2022/06/22 08:10:11 Registering 3 informers
2022/06/22 08:10:11 Registering 4 controllers
2022-06-22T08:10:11.262Z	INFO	Successfully created the logger.
2022-06-22T08:10:11.263Z	INFO	Logging level set to: info
2022-06-22T08:10:11.263Z	INFO	webhook	Profiling enabled: false	{"commit": "588d4c8"}
2022-06-22T08:10:11.271Z	INFO	webhook	Running with Standard leader election	{"commit": "588d4c8"}
2022-06-22T08:10:11.293Z	INFO	webhook	Starting configuration manager...	{"commit": "588d4c8"}
{"level":"info","ts":1655885411.3948314,"logger":"fallback","caller":"injection/injection.go:61","msg":"Starting informers..."}
2022-06-22T08:10:11.495Z	INFO	webhook	Informers have been synced, unblocking admission webhooks.	{"commit": "588d4c8"}
2022-06-22T08:10:11.495Z	INFO	webhook	Starting controllers...	{"commit": "588d4c8"}
2022-06-22T08:10:11.495Z	INFO	webhook	webhook.configmapwebhook.00-of-01 will run in leader-elected mode with id "karpenter-cdd86f76f-jwtz7_366de70f-4110-4894-b2b5-875c9a38be4d"	{"commit": "588d4c8"}
2022-06-22T08:10:11.495Z	INFO	webhook.ConfigMapWebhook	Starting controller and workers	{"commit": "588d4c8"}
2022-06-22T08:10:11.495Z	INFO	webhook.ConfigMapWebhook	Started workers	{"commit": "588d4c8"}
2022-06-22T08:10:11.495Z	INFO	webhook	webhook.webhookcertificates.00-of-01 will run in leader-elected mode with id "karpenter-cdd86f76f-jwtz7_4a0982ed-1957-4325-8d05-6382273744c4"	{"commit": "588d4c8"}
2022-06-22T08:10:11.495Z	INFO	webhook.WebhookCertificates	Starting controller and workers	{"commit": "588d4c8"}
2022-06-22T08:10:11.495Z	INFO	webhook.WebhookCertificates	Started workers	{"commit": "588d4c8"}
2022-06-22T08:10:11.495Z	INFO	webhook	webhook.defaultingwebhook.00-of-01 will run in leader-elected mode with id "karpenter-cdd86f76f-jwtz7_c55e9b8a-a27f-4011-9037-90d55b17b4f9"	{"commit": "588d4c8"}
2022-06-22T08:10:11.495Z	INFO	webhook.DefaultingWebhook	Starting controller and workers	{"commit": "588d4c8"}
2022-06-22T08:10:11.495Z	INFO	webhook.DefaultingWebhook	Started workers	{"commit": "588d4c8"}
2022-06-22T08:10:11.495Z	INFO	webhook	webhook.validationwebhook.00-of-01 will run in leader-elected mode with id "karpenter-cdd86f76f-jwtz7_d43b415a-e1cc-438f-ad93-4c8de6f85d8d"	{"commit": "588d4c8"}
2022-06-22T08:10:11.495Z	INFO	webhook.ValidationWebhook	Starting controller and workers	{"commit": "588d4c8"}
2022-06-22T08:10:11.495Z	INFO	webhook.ValidationWebhook	Started workers	{"commit": "588d4c8"}
I0622 08:10:11.495689       1 leaderelection.go:243] attempting to acquire leader lease karpenter/webhook.configmapwebhook.00-of-01...
I0622 08:10:11.496009       1 leaderelection.go:243] attempting to acquire leader lease karpenter/webhook.webhookcertificates.00-of-01...
I0622 08:10:11.496217       1 leaderelection.go:243] attempting to acquire leader lease karpenter/webhook.defaultingwebhook.00-of-01...
I0622 08:10:11.496418       1 leaderelection.go:243] attempting to acquire leader lease karpenter/webhook.validationwebhook.00-of-01...
I0622 08:10:11.582972       1 leaderelection.go:253] successfully acquired lease karpenter/webhook.defaultingwebhook.00-of-01
I0622 08:10:11.583476       1 leaderelection.go:253] successfully acquired lease karpenter/webhook.webhookcertificates.00-of-01
I0622 08:10:11.583886       1 leaderelection.go:253] successfully acquired lease karpenter/webhook.configmapwebhook.00-of-01
I0622 08:10:11.584227       1 leaderelection.go:253] successfully acquired lease karpenter/webhook.validationwebhook.00-of-01
2022-06-22T08:10:11.584Z	INFO	webhook	"karpenter-cdd86f76f-jwtz7_c55e9b8a-a27f-4011-9037-90d55b17b4f9" has started leading "webhook.defaultingwebhook.00-of-01"	{"commit": "588d4c8"}
2022-06-22T08:10:11.585Z	INFO	webhook	"karpenter-cdd86f76f-jwtz7_4a0982ed-1957-4325-8d05-6382273744c4" has started leading "webhook.webhookcertificates.00-of-01"	{"commit": "588d4c8"}
2022-06-22T08:10:11.585Z	INFO	webhook.WebhookCertificates	Reconcile succeeded	{"commit": "588d4c8", "knative.dev/traceid": "7575fab2-f808-4dc2-9649-587d0db7bb33", "knative.dev/key": "karpenter/karpenter-cert", "duration": "241.795µs"}
2022-06-22T08:10:11.585Z	INFO	webhook	"karpenter-cdd86f76f-jwtz7_366de70f-4110-4894-b2b5-875c9a38be4d" has started leading "webhook.configmapwebhook.00-of-01"	{"commit": "588d4c8"}
2022-06-22T08:10:11.586Z	INFO	webhook	"karpenter-cdd86f76f-jwtz7_d43b415a-e1cc-438f-ad93-4c8de6f85d8d" has started leading "webhook.validationwebhook.00-of-01"	{"commit": "588d4c8"}
2022-06-22T08:10:11.689Z	INFO	webhook.ConfigMapWebhook	Webhook is valid	{"commit": "588d4c8", "knative.dev/traceid": "733d9569-d5d0-409d-8807-51148907067a", "knative.dev/key": "validation.webhook.config.karpenter.sh"}
2022-06-22T08:10:11.689Z	INFO	webhook.ConfigMapWebhook	Reconcile succeeded	{"commit": "588d4c8", "knative.dev/traceid": "733d9569-d5d0-409d-8807-51148907067a", "knative.dev/key": "validation.webhook.config.karpenter.sh", "duration": "103.597749ms"}
2022-06-22T08:10:11.887Z	INFO	webhook.ValidationWebhook	Updating webhook	{"commit": "588d4c8", "knative.dev/traceid": "7b0fc750-bee6-4751-80c4-d249f677eb92", "knative.dev/key": "validation.webhook.provisioners.karpenter.sh"}
2022-06-22T08:10:11.985Z	INFO	webhook.DefaultingWebhook	Updating webhook	{"commit": "588d4c8", "knative.dev/traceid": "92687cc3-7f1e-478a-8e14-843ee8e22394", "knative.dev/key": "defaulting.webhook.provisioners.karpenter.sh"}
2022-06-22T08:10:11.987Z	INFO	webhook.ValidationWebhook	Reconcile succeeded	{"commit": "588d4c8", "knative.dev/traceid": "7b0fc750-bee6-4751-80c4-d249f677eb92", "knative.dev/key": "validation.webhook.provisioners.karpenter.sh", "duration": "401.543671ms"}
2022-06-22T08:10:11.997Z	INFO	webhook.DefaultingWebhook	Reconcile succeeded	{"commit": "588d4c8", "knative.dev/traceid": "92687cc3-7f1e-478a-8e14-843ee8e22394", "knative.dev/key": "defaulting.webhook.provisioners.karpenter.sh", "duration": "413.177673ms"}
2022-06-22T08:10:12.102Z	INFO	webhook.DefaultingWebhook	Updating webhook	{"commit": "588d4c8", "knative.dev/traceid": "c2bd5fdc-1574-4ce0-8221-7d7077c046ac", "knative.dev/key": "defaulting.webhook.provisioners.karpenter.sh"}
2022-06-22T08:10:12.192Z	INFO	webhook.DefaultingWebhook	Reconcile succeeded	{"commit": "588d4c8", "knative.dev/traceid": "c2bd5fdc-1574-4ce0-8221-7d7077c046ac", "knative.dev/key": "defaulting.webhook.provisioners.karpenter.sh", "duration": "193.578821ms"}
2022-06-22T08:10:30.954Z	INFO	webhook	Webhook ServeHTTP request=&http.Request{Method:"POST", URL:(*url.URL)(0xc000ae1d40), Proto:"HTTP/1.1", ProtoMajor:1, ProtoMinor:1, Header:http.Header{"Accept":[]string{"application/json, */*"}, "Accept-Encoding":[]string{"gzip"}, "Content-Length":[]string{"6639"}, "Content-Type":[]string{"application/json"}, "User-Agent":[]string{"kube-apiserver-admission"}}, Body:(*http.body)(0xc000b46740), GetBody:(func() (io.ReadCloser, error))(nil), ContentLength:6639, TransferEncoding:[]string(nil), Close:false, Host:"karpenter.karpenter.svc:443", Form:url.Values(nil), PostForm:url.Values(nil), MultipartForm:(*multipart.Form)(nil), Trailer:http.Header(nil), RemoteAddr:"10.113.79.216:53744", RequestURI:"/default-resource?timeout=10s", TLS:(*tls.ConnectionState)(0xc00054e8f0), Cancel:(<-chan struct {})(nil), Response:(*http.Response)(nil), ctx:(*context.cancelCtx)(0xc000b46780)}	{"commit": "588d4c8"}
2022-06-22T08:10:30.959Z	INFO	webhook	Kind: "karpenter.sh/v1alpha5, Kind=Provisioner" PatchBytes: null	{"commit": "588d4c8", "knative.dev/kind": "karpenter.sh/v1alpha5, Kind=Provisioner", "knative.dev/namespace": "", "knative.dev/name": "default-eu-central-1b-private-generic", "knative.dev/operation": "UPDATE", "knative.dev/resource": "karpenter.sh/v1alpha5, Resource=provisioners", "knative.dev/subresource": "status", "knative.dev/userinfo": "{system:serviceaccount:karpenter:karpenter fa943543-9314-4a1e-8779-8abe1eece96b [system:serviceaccounts system:serviceaccounts:karpenter system:authenticated] map[authentication.kubernetes.io/pod-name:[karpenter-cdd86f76f-jwtz7] authentication.kubernetes.io/pod-uid:[eb8fc390-21f8-41f2-b76e-c6357ed9b188]]}"}
2022-06-22T08:10:30.959Z	INFO	webhook	remote admission controller audit annotations=map[string]string(nil)	{"commit": "588d4c8", "knative.dev/kind": "karpenter.sh/v1alpha5, Kind=Provisioner", "knative.dev/namespace": "", "knative.dev/name": "default-eu-central-1b-private-generic", "knative.dev/operation": "UPDATE", "knative.dev/resource": "karpenter.sh/v1alpha5, Resource=provisioners", "knative.dev/subresource": "status", "knative.dev/userinfo": "{system:serviceaccount:karpenter:karpenter fa943543-9314-4a1e-8779-8abe1eece96b [system:serviceaccounts system:serviceaccounts:karpenter system:authenticated] map[authentication.kubernetes.io/pod-name:[karpenter-cdd86f76f-jwtz7] authentication.kubernetes.io/pod-uid:[eb8fc390-21f8-41f2-b76e-c6357ed9b188]]}", "admissionreview/uid": "6e760107-5ef0-4d54-80c3-63ec99e552a1", "admissionreview/allowed": true, "admissionreview/result": "nil"}
2022-06-22T08:10:30.976Z	INFO	webhook	Webhook ServeHTTP request=&http.Request{Method:"POST", URL:(*url.URL)(0xc000c1bc20), Proto:"HTTP/1.1", ProtoMajor:1, ProtoMinor:1, Header:http.Header{"Accept":[]string{"application/json, */*"}, "Accept-Encoding":[]string{"gzip"}, "Content-Length":[]string{"6639"}, "Content-Type":[]string{"application/json"}, "User-Agent":[]string{"kube-apiserver-admission"}}, Body:(*http.body)(0xc000b47e80), GetBody:(func() (io.ReadCloser, error))(nil), ContentLength:6639, TransferEncoding:[]string(nil), Close:false, Host:"karpenter.karpenter.svc:443", Form:url.Values(nil), PostForm:url.Values(nil), MultipartForm:(*multipart.Form)(nil), Trailer:http.Header(nil), RemoteAddr:"10.113.79.216:53746", RequestURI:"/validate-resource?timeout=10s", TLS:(*tls.ConnectionState)(0xc00054eb00), Cancel:(<-chan struct {})(nil), Response:(*http.Response)(nil), ctx:(*context.cancelCtx)(0xc000b47ec0)}	{"commit": "588d4c8"}
2022-06-22T08:10:30.985Z	INFO	webhook	remote admission controller audit annotations=map[string]string(nil)	{"commit": "588d4c8", "knative.dev/kind": "karpenter.sh/v1alpha5, Kind=Provisioner", "knative.dev/namespace": "", "knative.dev/name": "default-eu-central-1b-private-generic", "knative.dev/operation": "UPDATE", "knative.dev/resource": "karpenter.sh/v1alpha5, Resource=provisioners", "knative.dev/subresource": "status", "knative.dev/userinfo": "{system:serviceaccount:karpenter:karpenter fa943543-9314-4a1e-8779-8abe1eece96b [system:serviceaccounts system:serviceaccounts:karpenter system:authenticated] map[authentication.kubernetes.io/pod-name:[karpenter-cdd86f76f-jwtz7] authentication.kubernetes.io/pod-uid:[eb8fc390-21f8-41f2-b76e-c6357ed9b188]]}", "admissionreview/uid": "b9afbf7d-1229-48d9-8e95-181998b940e5", "admissionreview/allowed": true, "admissionreview/result": "nil"}
```

**Comment by ellistarn** [comment] 2022-06-22 17:09
I believe a fix for this was just released. Can you try upgrading?

**Comment by spring1843** [comment] 2022-06-22 23:58
I was able to reproduce this with Karpenter v0.12.0, the DELETE operation is missing after a helm chart install.

Looks like Delete was added here: https://github.com/aws/karpenter/pull/1943

**Comment by pyromaniac3010** [comment] 2022-06-23 06:33
@ellistarn @spring1843 
As I pointed out: The DELETE is in the helm chart and successfully deployed. But AFTER the start of the deployment it gets changed to a version without the DELETE. So I think the karpenter webhook container changes it to a version without the DELETE here:
```
2022-06-22T08:10:11.985Z	INFO	webhook.DefaultingWebhook	Updating webhook	{"commit": "588d4c8", "knative.dev/traceid": "92687cc3-7f1e-478a-8e14-843ee8e22394", "knative.dev/key": "defaulting.webhook.provisioners.karpenter.sh"}
```
It is NOT a problem with the helm chart, but with the container image.

**Comment by spring1843** [comment] 2022-06-23 16:46
That seems viable, when you stop the Karpenter pod it no longer removed `DELETE`.

**Closed** 2022-06-24 23:19 UTC
Labels: bug, burning
