### ISSUE TITLE
Trouble scheduling parallel build pods

### ISSUE THREAD

**Issue by andromeda306** [aws/karpenter#3642] opened 2023-03-27 08:39 UTC
### Version

Karpenter Version: karpenter-v0.27.0 v0.27.0
Gitlab Runner Version:  gitlab-runner-0.47.1 v15.6.1
Kubernetes: v1.24.0

### Expected Behavior

Working with a setup based on EKS, I have deployed both the Karpenter and Gitlab Runner deployments on Fargate and expect runner executor nodes to be deployed on EC2. Generally this seems to function well and all pipeline jobs are completed as expected. As each job is created by the gitlab pipeline Karpenter is able to pick them up relatively quickly and create a new spot node on which the required pods can be run. The following pods are scheduled on each node - where the number of executor pods is dependent on their respective container spec:
```
cloudwatch-agent
aws-node
kube-proxy
X executor-pods
```
Below is an example of the provisioner logs during a successfully run job:
```
2023-03-27T07:38:11.073Z        DEBUG   controller.provisioner  298 out of 616 instance types were excluded because they would breach provisioner limits        {"commit": "dc3af1a"}
2023-03-27T07:38:11.082Z        INFO    controller.provisioner  found provisionable pod(s)      {"commit": "dc3af1a", "pods": 1}
2023-03-27T07:38:11.082Z        INFO    controller.provisioner  computed new node(s) to fit pod(s)      {"commit": "dc3af1a", "nodes": 1, "pods": 1}
2023-03-27T07:38:11.082Z        INFO    controller.provisioner  launching machine with 1 pods requesting {"cpu":"4325m","memory":"4296Mi","pods":"4"} from types m5a.2xlarge, m6a.2xlarge, c5a.4xlarge, c5.4xlarge, t3a.2xlarge and 9 other(s)  {"commit": "dc3af1a", "provisioner": "gitlab-node"}
2023-03-27T07:38:11.425Z        DEBUG   controller.provisioner.cloudprovider    created launch template {"commit": "dc3af1a", "provisioner": "gitlab-node", "launch-template-name": "Karpenter-karpenter-demo-1482795389705368122", "launch-template-id": "lt-0435e081136d187e6"}
2023-03-27T07:38:13.371Z        INFO    controller.provisioner.cloudprovider    launched new instance   {"commit": "dc3af1a", "provisioner": "gitlab-node", "id": "i-0c9dffe4b47529f8f", "hostname": "ip-<node-ip>.eu-west-1.compute.internal", "instance-type": "t3a.2xlarge", "zone": "eu-west-1a", "capacity-type": "spot"}
2023-03-27T07:40:07.445Z        INFO    controller.node added TTL to empty node {"commit": "dc3af1a", "node": "ip-<node-ip>.eu-west-1.compute.internal"}
```

### Actual Behavior

However I've noticed that sometimes when deploying a number of parallel build jobs (5+), the provisioner logs indicate that the pods cannot be scheduled, either at all or only partially. Leading to one of three scenarios taking place:

1. No nodes are created at all and none of the pods are scheduled, in which case error continues to appear until the pipeline is cancelled or times out.
2. At least one node is created, in which case several of the pods are scheduled. The remainder continue to produce the error until they can be scheduled on the existing nodes.
3. All pods are scheduled successfully and the error does not appear.

This is repeatable and does not seem to be related to any configured limits as far as I can tell, parallel jobs for other pipelines (just running container X) do not exhibit this behaviour as far as I can tell. It's worth noting that this exact same job works fine when run in lower number i.e. 1-5. Also, the subnets in which the nodes are being deployed have more than enough available IP addresses for all eventualities.

Despite configuring a wide range of instances available for both spot and on-demand, I continue to see the following error:
```
2023-03-27T07:04:24.263Z        DEBUG   controller.provisioner  525 out of 616 instance types were excluded because they would breach provisioner limits        {"commit": "dc3af1a"}
2023-03-27T07:04:24.355Z        ERROR   controller.provisioner  Could not schedule pod, incompatible with provisioner "gitlab-node", no instance type satisfied resources {"cpu":"4","memory":"4Gi","pods":"1"} and requirements node.kubernetes.io/instance-type In [c5.2xlarge c5.4xlarge c5.xlarge c5a.2xlarge c5a.4xlarge and 18 others], kubernetes.io/os In [linux], kubernetes.io/arch In [amd64], customer In [gitlab-aws], karpenter.sh/provisioner-name In [gitlab-node], topology.kubernetes.io/zone In [eu-west-1a eu-west-1b], karpenter.sh/capacity-type In [on-demand spot]      {"commit": "dc3af1a", "pod": "default/runner-ud-txenw-project-2389-concurrent-7v64v4"}
2023-03-27T07:04:24.355Z        ERROR   controller.provisioner  Could not schedule pod, incompatible with provisioner "gitlab-node", no instance type satisfied resources {"cpu":"4","memory":"4Gi","pods":"1"} and requirements node.kubernetes.io/instance-type In [c5.2xlarge c5.4xlarge c5.xlarge c5a.2xlarge c5a.4xlarge and 18 others], kubernetes.io/os In [linux], kubernetes.io/arch In [amd64], customer In [gitlab-aws], karpenter.sh/provisioner-name In [gitlab-node], topology.kubernetes.io/zone In [eu-west-1a eu-west-1b], karpenter.sh/capacity-type In [on-demand spot]      {"commit": "dc3af1a", "pod": "default/runner-ud-txenw-project-2389-concurrent-88vzsm"}
2023-03-27T07:04:24.355Z        ERROR   controller.provisioner  Could not schedule pod, incompatible with provisioner "gitlab-node", no instance type satisfied resources {"cpu":"4","memory":"4Gi","pods":"1"} and requirements kubernetes.io/arch In [amd64], customer In [gitlab-aws], karpenter.sh/provisioner-name In [gitlab-node], topology.kubernetes.io/zone In [eu-west-1a eu-west-1b], karpenter.sh/capacity-type In [on-demand spot], node.kubernetes.io/instance-type In [c5.2xlarge c5.4xlarge c5.xlarge c5a.2xlarge c5a.4xlarge and 18 others], kubernetes.io/os In [linux]      {"commit": "dc3af1a", "pod": "default/runner-ud-txenw-project-2389-concurrent-9g7w6t"}
```
On the EKS side of things, the following error can also be seen for pods that cannot be scheduled immediately.
I get the feeling that the ` 2 Insufficient cpu, 2 Insufficient memory, 2 Too many pods` is critical to resolving the underlying issue (all other output is expected), but am unsure how to approach it.
```
Warning	FailedScheduling	11 minutes	default-scheduler	0/9 nodes are available: 1 node(s) had untolerated taint {node.kubernetes.io/unreachable: }, 2 Insufficient cpu, 2 Insufficient memory, 2 Too many pods, 6 node(s) had untolerated taint {eks.amazonaws.com/compute-type: fargate}. preemption: 0/9 nodes are available: 2 No preemption victims found for incoming pod, 7 Preemption is not helpful for scheduling.
```

### Steps to Reproduce the Problem

Seeing as the issue is not related to InsufficientInstanceCapacity in either zone. I think that it someone configured a similar pod spec to the one provided and scheduled a number of jobs they should be able to reproduce the behaviour. I've also tried basing the provisioner spec on computer power rather than specific instance types but it does not seem to change anything.
```
    - key: "karpenter.k8s.aws/instance-cpu"
      operator: In
      values: ["2", "4", "8", "16", "32"]
    - key: "karpenter.k8s.aws/instance-memory"
      operator: In
      values: ["2", "4", "8", "16", "32"]
    - key: "karpenter.k8s.aws/instance-category"
      operator: In
      values: ["c", "m", "t"]
```

### Resource Specs and Logs

I've deployed the following Provisioner and AWSNodeTemplate onto the cluster.
```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: gitlab-node
spec:
  requirements:
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: ["eu-west-1a", "eu-west-1b"]
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot", "on-demand"]
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: [ "t3.xlarge", "t3a.2xlarge", "m5.xlarge", "m5a.xlarge", "m5.2xlarge", "m5a.2xlarge", "c5.xlarge", "c5a.xlarge", "c5.2xlarge", "c5a.2xlarge", "c5.4xlarge", "c5a.4xlarge", "c6a.xlarge", "c6a.2xlarge", "c6a.4xlarge", "m6i.xlarge", "m6a.xlarge", "m6i.2xlarge", "m6a.2xlarge", "m6i.4xlarge", "m6a.4xlarge", "m5n.xlarge", "m5n.2xlarge" ]
  limits:
    resources:
      cpu: 100
      memory: 100Gi
  providerRef:
    name: gitlab-node
  labels:
    customer: gitlab-aws
  annotations:
    customer: "gitlab-aws"
  ttlSecondsAfterEmpty: 30
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: gitlab-node
spec:
  subnetSelector:
    karpenter.sh/discovery: ${CLUSTER_NAME}
  securityGroupSelector:
    karpenter.sh/discovery: ${CLUSTER_NAME}
EOF

```
Below are some of the most relevant gitlab runner config entries. 
```
concurrent: 100
checkInterval: 30
    [[runners]]
      environment = [
        "DOCKER_DRIVER=overlay2",
        "DOCKER_TLS_CERTDIR=",
        "DOCKER_HOST=tcp://localhost:2375"
      ]

      [runners.kubernetes]
        namespace = "default"
        name = "executor"
        image = "public.ecr.aws/docker/library/docker:latest"
        privileged = true

        #helper containers
        helper_cpu_request = "2"
        helper_memory_request = "2Gi"
        helper_memory_limit = "2Gi"

        #builder containers
        build_cpu_request = "2"
        build_memory_request = "2Gi"
        build_memory_limit = "2Gi"

        #service containers
        service_cpu_request = "2"
        service_memory_request = "2Gi"
        service_memory_limit = "2Gi"

        [runners.kubernetes.node_selector]
          "customer" = "gitlab-aws"
        
        [runners.kubernetes.pod_security_context]
          allowPrivilegeEscalation = true
          readOnlyRootFilesystem = false
          privileged = true
```
The pipeline jobs:
```
# build simple image with DinD
.build-template:
  image: public.ecr.aws/docker/library/docker:dind
  when: manual
  services:
    - public.ecr.aws/docker/library/docker:stable-dind
  before_script:
    - apk add --no-cache curl jq python3 py3-pip gettext libintl
    - pip install awscli
  script:
    - docker build -f docker/Dockerfile -t $CI_PIPELINE_ID -t $CI_ENVIRONMENT_SLUG --load .

docker:parallel-build:
  stage: parallel-build-image
  extends: .build-template
  parallel: 10

```
Simple Dockerfile from above pipeline job
```
FROM debian
RUN apt-get update && apt install openssh-server -y
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment] 2023-03-27 17:06
The default-scheduler errors you're seeing look pretty standard. Karpenter will only engage if kube-scheduler is not able to schedule pods on your existing nodes. So for Karpenter to start doing anything, kube-scheduler needs to fail. 

Your provisioner is limited to 100 CPU and 100 GiB of memory:

```
  limits:
    resources:
      cpu: 100
      memory: 100Gi
```

It looks like the runners you're using consume 2 CPU and 2 GiB of memory per and the concurrency is 100. I'm not familiar with the gitlab runner config, but if this means you're launching 2*100 CPU, then you'll hit limits around half way through the runs.  Maybe this is a concurrency limit instead? 

Keep in mind that the limits in the provisioner means that Karpenter will add up all the nodes it has launched and won't launch past those resource limits. 

Curious if increasing the limit fixes the test you've been doing to trigger this problem?

**Comment by andromeda306** [comment] 2023-04-01 08:09
So after a weeks worth of testing it seems like increasing the values for those `limits:` as recommended above has made a difference. I've run through a number of pipeline jobs of all sorts and capacity and not once have I seen the `Could not schedule pod` error appear in the provisioner logs, that said I'm at a loss as to why that made such a difference. As far as I understand the cumulative resource requirements for the pipelines I was launching would not have been anywhere near those original limits - but it's possible I was missing something.

Either way I've another error to investigate. I'm now occasionally seeing jobs fail likely due to the underlying executor node being terminated prematurely `ERROR: Job failed: pod "runner-q9xapunl-project-2311-concurrent-1z96xd" status is "Failed"` - but only when running several jobs at once. I'm planing on getting proper logging to cloudwatch working this week to better see whats going on under the hood. In theory nodes should only be cordoned off when there's no pods running but there could be some sort of race event occurring - will report back with findings.

**Comment by tzneal** [comment] 2023-04-12 15:54
I'm going to close this now as it seems like it was limits and the problem is resolved. Feel free to open a new issue if you run into more problems.

**Closed by tzneal** 2023-04-12 15:54 UTC
Labels: bug
