### ISSUE TITLE
Configure Karpenter to be a custom scheduler

### ISSUE THREAD

**Issue by olemarkus** [aws/karpenter#1097] opened 2022-01-07 09:37 UTC
**Tell us about your request**

Instead of listening for unscheduled Pods, listen for Pods configured with karpenter as scheduler name (configurable).

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
In reality, this may be mostly useful for testing. When karpenter continuously race with kube-scheduler, it is hard to determine what behavior karpenter would have when it wins the race.
By explicitly specifying a scheduler on Pods, kube-scheduler would no longer participate in the race.

**Are you currently working around this issue?**
Repeating over and over again

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment] 2022-01-07 18:44
We thought about this as part of the original design. Practically, it was a ton more work to try to implement both a scheduler and provisioner as part of the MVP, so we relied on the kube-scheduler for scheduling to existing capacity. The race is actually quite rare -- since Karpenter waits for the kube scheduler to mark a pod as unschedulable, the race only occurs when capacity becomes available within a tiny period of time when karpenter is scheduling the pod to new capacity. Further, the system self-heals, and it shouldn't have any impact to pod availability -- just a couple errors in the logs. 

Some benefits:
- avoid all race conditions with the kube scheduler
- better decision making (pack vs spread) on existing capacity 

Some downsides:
- users would have to opt in to karpenter w/ a change to pod specs, which makes it harder to adopt for existing workloads
- karpenter now needs a full scheduler implementation (for existing capacity)

**Comment by pnjihia** [comment] 2022-02-11 06:39
@olemarkus I had the same exact problem, here's how I went about it:

1. Bring up  a provisioner with both `spec.taints` and `spec.labels`. Values must be unique across the cluster.
2. For the workloads meant for karpenter, tolerate the taint with `spec.tolerations` and also set node selection to match above label: `spec.nodeSelector`
3. The taint blocks 'other' pods from being scheduled in 'karpenter' nodes and the label blocks targeted pods from being scheduled elsewhere.

kube-scheduler will fail to schedule the pod and karpenter will be happy to pick that up. With capacity, I believe kube-scheduler will just place similar pods in "karpenter" nodes as intended. It's a workaround, but it separates your workloads especially with existing loaded clusters.

**Comment by ellistarn** [comment] 2022-04-20 00:28
Closing in favor of not binding pods. We have work in progress on this.

**Closed by ellistarn** 2022-04-20 00:28 UTC
Labels: feature
