### ISSUE TITLE
Avoid downtime of services introduced by karpenter consolidation in development environments

### ISSUE THREAD

**Issue by saitessell** [aws/karpenter#4849] opened 2023-10-18 07:12 UTC
### Description

**What problem are you trying to solve?**
I am trying karpenter for my development environments where most of the kubernetes deployments are single replicas. The pods usually take decent time to be ready before serving traffic. In such cases if consolidation kicks in there is an evident downtime for the pods that are being rescheduled because the old pod is terminated before scheduled pod is ready. If we set PDB for these single replica deployments then the consolidation logic is not considering these pods to be moved to a different node. Raising this a feature because i couldn't find any documentation which will allow me to configure how  and when the termination of the pods will start in the events of consolidation.

**How important is this feature to you?**

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment] 2023-10-18 17:56
PDBs use a label selector, so you can include the label selector to refer to many deployments at once. Otherwise, we're working on Disruption controls which will allow you to configure a node-based disruption budget with a cron schedule. 

The design for this is here if you want to check it out: https://github.com/aws/karpenter-core/pull/516

I'll close this as a duplicate of https://github.com/aws/karpenter/issues/1302 and https://github.com/aws/karpenter/issues/4529 and #1738

**Closed by njtran** 2023-10-18 17:56 UTC
Labels: feature
