### ISSUE TITLE
Deregistered Node Not Terminated

### ISSUE THREAD

**Issue by cmukai-cisco** [aws/karpenter#2832] opened 2022-11-10 16:58 UTC
### Version

__Karpenter Version:__ 0.18.1

__Kubernetes Version:__ v1.23

### Expected Behavior

Nodes deregisted from the K8s cluster should be terminated.

### Actual Behavior

A node that was deregistered from EKS was not terminated.

### Steps to Reproduce the Problem

1. Modify provisioner manifest to use smaller instance types.
2. Terminate worker node.
3. Karpenter launched 4 new nodes but consolidated 1 so that only 3 were registered with the cluster.
4. The node that was deregistered was not terminated (see screen shots from EC2 and EKS consoles).
<img width="758" alt="Screenshot 2022-11-10 at 8 31 46 AM" src="https://user-images.githubusercontent.com/30554470/201156810-230426b8-8fa4-4454-933a-df65fd501156.png">
<img width="734" alt="Screenshot 2022-11-10 at 8 39 25 AM" src="https://user-images.githubusercontent.com/30554470/201156855-f4c89a56-63a5-4956-9dea-c56020a4bc74.png">

### Resource Specs and Logs

The node that was not terminated is: ip-10-135-235-20.ec2.internal
[karpenter.log](https://github.com/aws/karpenter/files/9983058/karpenter.log)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment] 2022-11-11 01:45
Karpenter uses a finalizer to ensure that the instance is deleted before we allow the node object to delete. There's a known race condition, where if the node fails to register to the API server and the karpenter controller crashes, it's possible to leak a node. Do you have any logs you can share that might let us know what's going on?

**Comment by cmukai-cisco** [comment] 2022-11-11 16:41
I posted the Karpenter logs in the "Resource Specs and Logs" section.

**Comment by jonathan-innis** [comment] 2022-11-11 19:40
It look like the node was cordoned prior to the launching of a new node with the same host name. Do you know what caused that cordoning? Was this a manual action that you performed against the node to delete the node and the new node that was launched just happened to get the same IP?

**Comment by cmukai-cisco** [comment] 2022-11-11 22:00
I did terminate a node but can't confirm what its IP was. Since the VPC only has 256 possible IP addresses, the probability that an IP address was reused is probably higher than in most use cases.

**Comment by jonathan-innis** [comment] 2022-11-11 22:59
From the looks of it, it looks like the backing EC2 instance is gone, but the node stuck around on the cluster. Do you know if there was some process that might have deleted the instance without the node being involved?

This issue looks to relate to #2734 where we saw the same issue appear.

**Comment by cmukai-cisco** [comment] 2022-11-11 23:03
I terminated the instance from the EC2 console, so it was removed without calling any Karpenter or EKS APIs.

**Comment by jonathan-innis** [comment] 2022-11-11 23:08
Got it; then yes, that would be the issue. There is some latency between when the instance is terminated and when the cloud-controller-manager picks up the need to delete the node at the api-server. There are [some suggestions](https://github.com/aws/karpenter/issues/2734#issuecomment-1295311257) to workaround this issue (or to reduce the race for now).

As mentioned in #2734, we have longer-term solutions that are in a design phase for now (and should soon have an RFC) around how to fix issues like this that are leading to races.

**Comment by jonathan-innis** [comment] 2022-11-11 23:09
I'm closing this since I'm considering it a duplicate of #2734. Can you please 👍  that issue to let us know other users are hitting this?

**Closed by jonathan-innis** 2022-11-11 23:09 UTC
Labels: bug, burning

**Comment by jonathan-innis** [comment] 2022-11-30 19:12
@cmukai-cisco, we have a design doc up now that should address this issue: #2944

**Comment by jonathan-innis** [comment] 2023-05-17 06:50
@cmukai-cisco  Have you been able to install version `v0.28.0-rc.1` to try and see if the orphaned ec2 instance issue you were seeing is resolved?
